// Renders the four-tier sector tree as a nested Markdown outline.
//
// Kept as a pure function so `npm run taxonomy:outline` and the test suite
// produce byte-identical output: the committed outline can never drift away
// from the JSON it describes.

import type { TaxonomyNode } from './types'

const LEVEL_LABEL: Record<number, string> = {
  1: 'Macro-Sector (Level 1)',
  2: 'Industry Sector (Level 2)',
  3: 'Sub-Industry (Level 3)',
  4: 'Operational / Product Niche (Level 4)',
}

export function renderSectorOutline(nodes: TaxonomyNode[]): string {
  const childrenOf = new Map<string | null, TaxonomyNode[]>()
  for (const node of nodes) {
    const siblings = childrenOf.get(node.parentId) ?? []
    siblings.push(node)
    childrenOf.set(node.parentId, siblings)
  }

  const lines: string[] = [
    '# South African Corporate Taxonomy - Sector Tree Outline',
    '',
    'Generated by `npm run taxonomy:outline` from `markets/organizations/taxonomy/sector-tree.json`.',
    'Do not edit by hand: edit the JSON and regenerate.',
    '',
    'Architecture: **Macro-Sector (L1)** -> **Industry Sector (L2)** -> **Sub-Industry (L3)** -> **Operational / Product Niche (L4)**.',
    'Nodes marked _(informal economy)_ are where unregistered or informal operators are normal, so entity type and',
    'tax status carry the distinction instead of an assumption of CIPC registration.',
    '',
  ]

  const counts = new Map<number, number>()
  for (const node of nodes) counts.set(node.level, (counts.get(node.level) ?? 0) + 1)
  lines.push(
    `| Tier | Nodes |`,
    `|---|---|`,
    ...[1, 2, 3, 4].map((level) => `| ${LEVEL_LABEL[level]} | ${counts.get(level) ?? 0} |`),
    `| **Total** | **${nodes.length}** |`,
    '',
  )

  const walk = (parentId: string | null, depth: number) => {
    for (const node of childrenOf.get(parentId) ?? []) {
      const indent = '  '.repeat(depth)
      const suffixes = [node.informalRelevant ? ' _(informal economy)_' : '', node.sics ? ` — SIC ${node.sics}` : ''].join('')
      lines.push(`${indent}- **${node.name}** \`${node.id}\`${suffixes}`)
      if (node.saContext) lines.push(`${indent}  - ${node.saContext}`)
      if (node.synonyms && node.synonyms.length > 0) lines.push(`${indent}  - Also known as: ${node.synonyms.join(', ')}`)
      walk(node.id, depth + 1)
    }
  }

  walk(null, 0)
  return `${lines.join('\n')}\n`
}
