#!/usr/bin/env python3
"""Batch 6 — Western Cape CFOs/finance leadership + CIMA (ACMA/CGMA) cohort, all with
explicit designation evidence in LinkedIn headlines/educations. Uses db_lib.append_batch."""
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import db_lib  # noqa: E402

PEOPLE = []
COMPANIES = []
SOURCES = []

# ---- Western Cape — CONFIRMED CA(SA) ----
PEOPLE += [
    dict(name="Vincent Motholo", first="Vincent", surname="Motholo", des=["CA(SA)"],
         title="Chief Financial Officer", employer="University of Cape Town",
         role_family="Executive Finance", industry="Education", sub_industry="Tertiary education",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Vincent Motholo CA(SA)" — "Chief Financial Officer of the University of Cape Town and Chair of the South African Institute of Chartered Accountants (SAICA)"; Stanford GSB executive education.',
         academic=["Stanford University Graduate School of Business (executive education)"],
         linkedin="https://www.linkedin.com/in/vincent-motholo-ca-sa-842b7613/",
         source_urls=["https://www.linkedin.com/in/vincent-motholo-ca-sa-842b7613/"],
         notes="CFO of UCT and SAICA Board Chairman."),
    dict(name="Louis de Wet", first="Louis", surname="de Wet", des=["CA(SA)"],
         title="Chief Financial Officer", employer="TradeOn SA",
         role_family="Executive Finance", industry="Retail", sub_industry="KFC franchisee (QSR)",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         linkedin_location="Stellenbosch, Western Cape, South Africa",
         evidence='LinkedIn headline "CFO | CA (SA)": PwC South Africa "SAICA Articles | Chartered Accountant Trainee" Jan 2011–Dec 2013 (Cape Town); Stellenbosch University.',
         academic=["Stellenbosch University (2006–2010)"],
         linkedin="https://www.linkedin.com/in/louisdewetza/",
         source_urls=["https://www.linkedin.com/in/louisdewetza/"],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="PwC South Africa",
         articles_period="Jan 2011 – Dec 2013", articles_location="Cape Town",
         route="SAICA articles at PwC Cape Town (2011–2013) → CA(SA) → CFO",
         career=[{"employer": "PwC South Africa", "title": "Chartered Accountant Trainee (SAICA articles)", "years": "Jan 2011 – Dec 2013"},
                 {"employer": "Niveus Investments Limited", "title": "Financial Manager / Business Head / Operations Manager", "years": "Dec 2014 – Feb 2017"},
                 {"employer": "Stonehage Fleming", "title": "Relationship Manager — Family Office", "years": "Mar 2017 – Sep 2018"},
                 {"employer": "Private (family-office consulting)", "title": "Financial Consultant", "years": "Oct 2018 – Jun 2021"},
                 {"employer": "TradeOn SA", "title": "Chief Financial Officer (CFO)", "years": "Jun 2021 – present"}],
         yoe="10+", yoe_basis="PwC articles from Jan 2011.",
         notes="TradeOn SA: KFC franchisee with footprint in four provinces."),
    dict(name="Adriaan de Lange", first="Adriaan", surname="de Lange", des=["CA(SA)"],
         title="Executive Leader (CEO / COO / CFO roles)", employer="Adriaan de Lange Advisory (Private Capacity)",
         role_family="Executive Finance", industry="Manufacturing", sub_industry="Manufacturing, agri-tech & industrial",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Adriaan de Lange ... | CA(SA)" headline and About: "I’m a Chartered Accountant (CA)SA by training"; SAICA education; 20+ years as CEO/COO/CFO.',
         academic=["South African Institute of Chartered Accountants (SAICA)"],
         linkedin="https://www.linkedin.com/in/a3aandl/",
         source_urls=["https://www.linkedin.com/in/a3aandl/"],
         yoe="20+", yoe_basis="About: over two decades as CEO/COO/CFO/board-level leader.",
         notes="Executive leader across agribusiness, chemicals, fertiliser, industrial sectors; multi-country Africa exposure."),
    dict(name="Vanessa Rheeder", first="Vanessa", surname="Rheeder", des=["CA(SA)"],
         title="Fractional CFO", employer="The Modern CFO",
         role_family="Executive Finance", industry="Professional Services", sub_industry="Fractional CFO / advisory",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Vanessa Rheeder CA (SA)" — headline; "my work as a Fractional CFO"; Wharton Online education.',
         academic=["Wharton Online"],
         linkedin="https://www.linkedin.com/in/vanessa-rheeder-ca-sa/",
         source_urls=["https://www.linkedin.com/in/vanessa-rheeder-ca-sa/"],
         notes="Fractional CFO for founder-led and growth-stage businesses (The Modern CFO)."),
    dict(name="Nethin Karamchand", first="Nethin", surname="Karamchand", des=["CA(SA)"],
         title="Finance leader", employer="Deloitte (South Africa)",
         role_family="Other", industry="Professional Services", sub_industry="Audit & advisory (Big Four)",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: SAICA licence "SAICA CA(SA) Credential ID 20053119"; University of Cape Town; headline "Internationally experienced Chartered Accountant and finance leader".',
         academic=["University of Cape Town"],
         linkedin="https://www.linkedin.com/in/nethin/",
         source_urls=["https://www.linkedin.com/in/nethin/"],
         notes="Deloitte, Cape Town; prior London (UK) Big Four / financial-services roles."),
    dict(name="Bronvin Heuvel", first="Bronvin", surname="Heuvel", des=["CA(SA)"],
         title="(KPMG professional) — role not stated", employer="KPMG (South Africa)",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Big Four audit",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Bronvin Heuvel CA(SA) RA" — KPMG; University of the Western Cape.',
         academic=["University of the Western Cape"],
         linkedin="https://www.linkedin.com/in/bronvin-heuvel-ca-sa-ra-7b2475a9/",
         source_urls=["https://www.linkedin.com/in/bronvin-heuvel-ca-sa-ra-7b2475a9/"],
         notes="CA(SA) + Registered Auditor (RA), KPMG Cape Town."),
    dict(name="Morgan Gregory", first="Morgan", surname="Gregory", des=["CA(SA)"],
         title="Chief Financial Officer", employer="MK Aerospace SA",
         role_family="Executive Finance", industry="Technology", sub_industry="Aerospace / engineering",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Morgan Gregory CA(SA)"— ASL "Trainee Accountant | SAICA" Feb 2016–Dec 2018 (Somerset West); Stellenbosch University Bachelors Accounting/Finance 2010–2015; UNISA PG Dip Advanced Accounting Sciences 2016–2017.',
         academic=["Stellenbosch University — Bachelor's (Accounting & Finance) 2010–2015",
                   "UNISA — Postgraduate Diploma in Advanced Accounting Sciences 2016–2017"],
         linkedin="https://www.linkedin.com/in/morgan-gregory-ca-sa-64046117b/",
         source_urls=["https://www.linkedin.com/in/morgan-gregory-ca-sa-64046117b/"],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="ASL",
         articles_period="Feb 2016 – Dec 2018", articles_location="Somerset West",
         route="SAICA articles at ASL (Somerset West, 2016–2018) → CA(SA) → CFO",
         career=[{"employer": "ASL", "title": "Trainee Accountant (SAICA articles)", "years": "Feb 2016 – Dec 2018"},
                 {"employer": "ASL Advisory", "title": "Accounting Consultant", "years": "Jan 2019 – May 2019"},
                 {"employer": "MK Aerospace SA", "title": "Chief Financial Officer", "years": "present"}],
         notes="CFO of MK Aerospace SA."),
]

# ---- Western Cape — CONFIRMED CIMA (ACMA / CGMA) ----
PEOPLE += [
    dict(name="Chrizelda Visser", first="Chrizelda", surname="Visser", des=["ACMA", "CGMA"],
         title="Group Financial Manager", employer="Curated Beverages Ltd",
         role_family="Financial Control", industry="FMCG", sub_industry="Beverages",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Chrizelda Visser (ACMA,CGMA)" — "I am a qualified Chartered Management Accountant, registered with CIMA" (Oct 2015–present).',
         academic=[],
         linkedin="https://www.linkedin.com/in/chrizelda-visser-acma-cgma-3671b454/",
         source_urls=["https://www.linkedin.com/in/chrizelda-visser-acma-cgma-3671b454/"],
         articles_status="NOT_APPLICABLE", per="CIMA_PER",
         route="CIMA qualification + practical experience → ACMA/CGMA (registered with CIMA, Oct 2015)",
         notes="ACMA/CGMA; CIMA PER framework (no training contract)."),
    dict(name="Kyle Danster", first="Kyle", surname="Danster", des=["ACMA", "CGMA"],
         title="Finance (reporting & forecasting)", employer="Curro Holdings Ltd",
         role_family="Financial Control", industry="Education", sub_industry="Private education",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Kyle Danster ACMA, CGMA" — "lead reporting and forecasting"; CIMA education; award "CIMA A* programme member".',
         academic=["CIMA (Chartered Institute of Management Accountants)"],
         linkedin="https://www.linkedin.com/in/kyle-danster/",
         source_urls=["https://www.linkedin.com/in/kyle-danster/"],
         articles_status="NOT_APPLICABLE", per="CIMA_PER",
         route="CIMA qualification → ACMA/CGMA",
         notes="Reporting & forecasting role at Curro Holdings; CIMA A* programme member."),
    dict(name="Anton van Niekerk", first="Anton", surname="van Niekerk", des=["ACMA", "CGMA"],
         title="Finance Director", employer="Snapplify",
         role_family="Executive Finance", industry="Technology", sub_industry="EdTech",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Anton van Niekerk (ACMA)" — "A CIMA qualified Finance Director"; CIMA education (to 2008).',
         academic=["CIMA (to 2008)"],
         linkedin="https://www.linkedin.com/in/anton-van-niekerk-acma-b7503b87/",
         source_urls=["https://www.linkedin.com/in/anton-van-niekerk-acma-b7503b87/"],
         articles_status="NOT_APPLICABLE", per="CIMA_PER",
         route="CIMA qualification → ACMA (CGMA designation accompanies CIMA membership)",
         notes="Finance Director, Snapplify (EdTech, Cape Town)."),
    dict(name="Adrian Smith", first="Adrian", surname="Smith", des=["ACMA", "CGMA"],
         title="Head of Finance", employer="Bounty Apparel",
         role_family="Financial Control", industry="Manufacturing", sub_industry="Apparel / FMCG (Bounty Brands)",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Adrian Smith ACMA, CGMA" — The Chartered Institute of Management Accountants education.',
         academic=["The Chartered Institute of Management Accountants (CIMA)"],
         linkedin="https://www.linkedin.com/in/adrian-smith-acma-cgma-30942b59/",
         source_urls=["https://www.linkedin.com/in/adrian-smith-acma-cgma-30942b59/"],
         articles_status="NOT_APPLICABLE", per="CIMA_PER",
         route="CIMA qualification → ACMA/CGMA",
         notes="Head of Finance, Bounty Apparel (Bounty Brands), Cape Town."),
]

# ---- National — CONFIRMED CA(SA) ----
PEOPLE += [
    dict(name="Luke Woodhouse", first="Luke", surname="Woodhouse", des=["CA(SA)"],
         title="Chief Financial Officer", employer="GUUD GLOBAL",
         role_family="Executive Finance", industry="Technology", sub_industry="Trade-tech / digital trade platforms",
         province="Gauteng", city="Johannesburg", location_confidence="HIGH",
         linkedin_location="Johannesburg Metropolitan Area, Gauteng, South Africa",
         evidence='LinkedIn: "Luke Woodhouse CA (SA)" — CFO; SAICA education; "CFO with proven track record of driving sustainability and growth".',
         academic=["The South African Institute of Chartered Accountants (SAICA)"],
         linkedin="https://www.linkedin.com/in/luke-woodhouse-ca-sa-b31a0149/",
         source_urls=["https://www.linkedin.com/in/luke-woodhouse-ca-sa-b31a0149/"],
         notes="Profile location Johannesburg; employer GUUD GLOBAL is based City of Cape Town."),
]

# ---- HIGH_CONFIDENCE (designation in linkedin similar-profile headline only) ----
PEOPLE.append(dict(
    name="Elmarie Swanepoel", first="Elmarie", surname="Swanepoel", des=["CA(SA)"], status="HIGH_CONFIDENCE",
    designation_status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
    title="Faculty Member (Department of Accountancy)", employer="Stellenbosch University",
    role_family="Other", function="Education / academia", industry="Education", sub_industry="Tertiary education",
    province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
    linkedin_location="Cape Town, Western Cape, South Africa",
    evidence='LinkedIn "similar profiles" headline: "Elmarie Swanepoel — Chartered Accountant (CA (SA))"; ResearchGate: Faculty Member, Stellenbosch University Department of Accountancy. Individual LinkedIn URL not captured.',
    academic=[],
    source_urls=["https://www.researchgate.net/profile/Elmarie-Swanepoel"],
    notes="Stellenbosch University Accountancy faculty. CA(SA) designation per LinkedIn headline (full profile not captured).",
))

COMPANIES += [
    dict(id="cmp-0051", company_name="University of Cape Town", company_aliases=["UCT"],
         website="https://www.uct.ac.za/", industry="Education", sub_industry="Tertiary education",
         south_africa_locations=["Cape Town (Rondebosch Area)"],
         source_urls=["https://www.linkedin.com/in/vincent-motholo-ca-sa-842b7613/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0052", company_name="TradeOn SA", company_aliases=["TradeOn"],
         website=None, industry="Retail", sub_industry="KFC franchisee (QSR)",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/louisdewetza/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0053", company_name="Curro Holdings Ltd", company_aliases=["Curro"],
         website="https://www.curro.co.za/", industry="Education", sub_industry="Private education",
         south_africa_locations=["Cape Town (Durbanville)"],
         source_urls=["https://www.linkedin.com/in/kyle-danster/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0054", company_name="Snapplify", company_aliases=[],
         website="https://www.snapplify.com/", industry="Technology", sub_industry="EdTech / digital publishing",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/anton-van-niekerk-acma-b7503b87/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0055", company_name="Curated Beverages Ltd", company_aliases=["Curated Beverages"],
         website=None, industry="FMCG", sub_industry="Beverages",
         south_africa_locations=["Cape Town (Tyger Valley)"],
         source_urls=["https://www.linkedin.com/in/chrizelda-visser-acma-cgma-3671b454/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0056", company_name="Bounty Apparel", company_aliases=["Bounty Brands"],
         website=None, industry="Manufacturing", sub_industry="Apparel / FMCG",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/adrian-smith-acma-cgma-30942b59/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0057", company_name="The Modern CFO", company_aliases=[],
         website=None, industry="Professional Services", sub_industry="Fractional CFO / advisory",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/vanessa-rheeder-ca-sa/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0058", company_name="MK Aerospace SA", company_aliases=["MK Aerospace"],
         website=None, industry="Technology", sub_industry="Aerospace / engineering",
         south_africa_locations=["Cape Town (Somerset West area)"],
         source_urls=["https://www.linkedin.com/in/morgan-gregory-ca-sa-64046117b/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0059", company_name="Adriaan de Lange Advisory", company_aliases=[],
         website=None, industry="Professional Services", sub_industry="Executive advisory (private capacity)",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/a3aandl/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0060", company_name="GUUD GLOBAL", company_aliases=["GUUD"],
         website="https://guud.com/", industry="Technology", sub_industry="Trade-tech / digital trade platforms",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/luke-woodhouse-ca-sa-b31a0149/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0061", company_name="ASL", company_aliases=["ASL Advisory"],
         website=None, industry="Professional Services", sub_industry="Accounting / advisory (SME)",
         south_africa_locations=["Somerset West"],
         source_urls=["https://www.linkedin.com/in/morgan-gregory-ca-sa-64046117b/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0062", company_name="Stellenbosch University", company_aliases=["Universiteit Stellenbosch"],
         website="https://www.sun.ac.za/", industry="Education", sub_industry="Tertiary education",
         south_africa_locations=["Stellenbosch"],
         source_urls=["https://www.researchgate.net/profile/Elmarie-Swanepoel"], date_verified=db_lib.TODAY),
]

src_urls = [
    ("https://www.linkedin.com/in/vincent-motholo-ca-sa-842b7613/", "LinkedIn", "Vincent Motholo CA(SA) — CFO University of Cape Town; SAICA Board Chairman."),
    ("https://www.linkedin.com/in/louisdewetza/", "LinkedIn", "Louis de Wet CA(SA) — CFO TradeOn SA; PwC SAICA articles 2011–2013 (Cape Town)."),
    ("https://www.linkedin.com/in/a3aandl/", "LinkedIn", "Adriaan de Lange CA(SA) — executive leader (CEO/COO/CFO), Cape Town."),
    ("https://www.linkedin.com/in/vanessa-rheeder-ca-sa/", "LinkedIn", "Vanessa Rheeder CA(SA) — fractional CFO, The Modern CFO, Cape Town."),
    ("https://www.linkedin.com/in/nethin/", "LinkedIn", "Nethin Karamchand CA(SA) (SAICA credential ID 20053119), Deloitte, Cape Town."),
    ("https://www.linkedin.com/in/bronvin-heuvel-ca-sa-ra-7b2475a9/", "LinkedIn", "Bronvin Heuvel CA(SA) RA — KPMG, Cape Town."),
    ("https://www.linkedin.com/in/morgan-gregory-ca-sa-64046117b/", "LinkedIn", "Morgan Gregory CA(SA) — CFO MK Aerospace SA; ASL SAICA articles 2016–2018 (Somerset West)."),
    ("https://www.linkedin.com/in/chrizelda-visser-acma-cgma-3671b454/", "LinkedIn", "Chrizelda Visser ACMA,CGMA — Group Financial Manager, Curated Beverages; CIMA registered Oct 2015."),
    ("https://www.linkedin.com/in/kyle-danster/", "LinkedIn", "Kyle Danster ACMA,CGMA — Curro Holdings, Cape Town."),
    ("https://www.linkedin.com/in/anton-van-niekerk-acma-b7503b87/", "LinkedIn", "Anton van Niekerk ACMA — Finance Director, Snapplify, Cape Town."),
    ("https://www.linkedin.com/in/adrian-smith-acma-cgma-30942b59/", "LinkedIn", "Adrian Smith ACMA,CGMA — Head of Finance, Bounty Apparel, Cape Town."),
    ("https://www.linkedin.com/in/luke-woodhouse-ca-sa-b31a0149/", "LinkedIn", "Luke Woodhouse CA(SA) — CFO GUUD GLOBAL; profile location Johannesburg."),
    ("https://www.researchgate.net/profile/Elmarie-Swanepoel", "Profile/Directory", "Elmarie Swanepoel — Faculty Member, Stellenbosch University Department of Accountancy (CA(SA) per LinkedIn similar-profile headline)."),
]
sid = db_lib.next_id(db_lib.SOURCES_PATH, "src")
for url, typ, summ in src_urls:
    SOURCES.append(dict(id="src-%04d" % sid, url=url, source_type=typ, person_id=None, company_id=None,
                        evidence_type="GENERAL", evidence_summary=summ,
                        qualification_supported=True, skill_supported=None, system_supported=None,
                        employment_supported=True, accessed_date=db_lib.TODAY,
                        reliability="STRONG", status="USED"))
    sid += 1

people = db_lib.append_batch(PEOPLE, company_specs=COMPANIES, source_specs=SOURCES, label="Batch 6 (WC CFOs + CIMA)")
