#!/usr/bin/env python3
"""Batch 14 - gap-closing sweeps: Property & Real Estate, Hospitality, Media,
Banking, Platinum/Energy, Agri-processing cooperatives, Cold-chain logistics and
the SAICA Top 35 Under 35 2024 pipeline.

Designation basis for the SAICA cohort: the SAICA Top 35 Under 35 competition is
restricted to CAs(SA) ("Recognising young CAs(SA) achievers..."), and every entry
below appears on SAICA's own finalist page with an employer and role. Where a
source describes a person as a "qualified chartered accountant" without the
CA(SA) string, the record is carried at HIGH_CONFIDENCE rather than CONFIRMED.
"""
import json
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import db_lib  # noqa: E402

TODAY = "2026-10-01"
SAICA_2024 = "https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2024-2/2024-top-35-under-35-finalists/"

PROP_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Regulated", "Multi-site", "B2B"]
HOSP_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Multi-site", "B2C", "Asset Intensive", "Franchise"]
MEDIA_TAGS = ["JSE Listed", "Listed Company", "Multinational", "Subscription", "B2C", "Regulated"]
BANK_TAGS = ["JSE Listed", "Listed Company", "Multinational", "Regulated", "Multi-site", "B2C", "B2B", "Major Financial Institution"]
MINING_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Regulated", "B2B", "Import / Export", "Multi-site"]
AGRI_TAGS = ["Private Company", "Co-operative", "South African Group", "Asset Intensive", "Multi-site", "B2B", "High Inventory"]
COLD_TAGS = ["Private Company", "Private Equity Backed", "Asset Intensive", "Multi-site", "B2B", "Cold Storage"]

PEOPLE = [
    # ------------------------------------------------------------ Property & Real Estate
    dict(
        name="Raj Nana", first="Raj", surname="Nana", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Attacq Limited", employer_group="Attacq", role_family="Executive Finance",
        industry="Property", sub_industry="Real estate investment trust (commercial and mixed-use)",
        grouped_industry="Property & Real Estate", province="Gauteng", city="Midrand",
        location_confidence="PROBABLE",
        evidence='Attacq Limited annual financial statements FY2025: "The preparation of these annual financial statements was supervised by R Nana CA(SA), Chief Financial Officer of the Group"; SA REIT Association profile: "Raj Nana completed his bachelor\\u2019s degree in Accounting at the University of Witwatersrand and served his articles with the FirstRand group... appointed as the Attacq Group, Chief Financial Officer, in June 2018."',
        academic=["Bachelor of Accounting, University of the Witwatersrand"],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="FirstRand group",
        source_urls=[
            "https://attacq.co.za/wp-content/uploads/2026/03/attacq-annual-financial-statements-2025.pdf",
            "https://sareit.co.za/about-2/",
        ],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=PROP_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Debt Funding", "Capital Management"],
        work_history=[dict(employer="Leveraged finance (banking)", title="Leveraged finance transactor", industry="Banking", period="before 2014")],
        career_industry_path="Banking (FirstRand articles, leveraged finance) > Property (Attacq)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Attacq also holds an A2X listing. City shown as Attacq's Waterfall City (Midrand) head office.",
    ),
    dict(
        name="Leon Kok", first="Leon", surname="Kok", des=["CA(SA)"],
        title="Chief Operating Officer", normalized_title="Chief Operating Officer", seniority_band="S8",
        employer="Redefine Properties Limited", employer_group="Redefine Properties", role_family="Executive Finance",
        industry="Property", sub_industry="Real estate investment trust (diversified)",
        grouped_industry="Property & Real Estate", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='SA REIT Association profile: "Leon Kok is a Chartered Accountant (SA) with an excellent blend of operational experience, sound business acumen and technical accounting knowledge. He joined Redefine in 2014 after a 13-year career at Peermont Global Limited. He remained with KPMG until 2000, after which he moved to Brait SA as Group Financial Manager and then to Emperors Palace as Chief Financial Officer until 2006... appointed as financial director and to the board in October 2014 and elected as chief operating officer in February 2021." Also chairs the SA REIT Accounting & JSE Committee.',
        academic=[],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA", articles_employer="KPMG (to 2000)",
        source_urls=["https://sareit.co.za/about-2/"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=PROP_TAGS, finance_environment_tags=["Listed Reporting", "IFRS", "Group Reporting", "Financial Control"],
        work_history=[
            dict(employer="Emperors Palace", title="Chief Financial Officer", industry="Hospitality", period="2000-2013"),
            dict(employer="Brait SA", title="Group Financial Manager", industry="Investments & Capital Markets", period="to 2000"),
            dict(employer="KPMG", title="Audit", industry="Professional Services", period="until 2000"),
            dict(employer="Peermont Global Limited", title="Finance leadership", industry="Hospitality", period="13 years to 2014"),
            dict(employer="Redefine Properties", title="Financial Director", industry="Property", period="2014-2021"),
        ],
        career_industry_path="Professional Services (KPMG) > Investments (Brait) > Hospitality (Emperors Palace/Peermont) > Property (Redefine)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="A clear Hospitality > Property finance talent flow, via a listed-property route.",
    ),
    dict(
        name="Laila Razack", first="Laila", surname="Razack", alternate_names=["Lalia Razack"],
        des=["CA(SA)"], status="HIGH_CONFIDENCE", qualification_confidence="HIGH", designation_status="HIGH_CONFIDENCE",
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Equites Property Fund Limited", employer_group="Equites", role_family="Executive Finance",
        industry="Property", sub_industry="Logistics and industrial real estate",
        grouped_industry="Property & Real Estate", province="Western Cape", city="Cape Town",
        location_confidence="PROBABLE",
        evidence='SA REIT Association profile: "Lalia Razack, Chief Financial Officer at Equites Property Fund. Laila Razack has a BSc (Finance and Accounting) and PGDA, and is a qualified chartered accountant. She joined Equites in 2015... Prior to joining Equites, she worked in PricewaterhouseCoopers Inc.\\u2019s Advisory division with a focus on mergers & acquisitions."',
        academic=["BSc (Finance and Accounting)", "PGDA"],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA", articles_employer="PwC (advisory)",
        source_urls=["https://sareit.co.za/about-2/"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=PROP_TAGS, finance_environment_tags=["Listed Reporting", "IFRS", "M&A", "Debt Funding"],
        work_history=[dict(employer="PricewaterhouseCoopers Inc.", title="Advisory (mergers & acquisitions)", industry="Professional Services", period="before 2015")],
        career_industry_path="Professional Services (PwC advisory) > Property (Equites)",
        employer_confidence="CONFIRMED", profile_confidence="HIGH",
        notes="HIGH_CONFIDENCE: the source says \"qualified chartered accountant\" without the CA(SA) string. Equites is an industrial/logistics-focused REIT — a direct bridge between the Property and Logistics ecosystems.",
    ),
    dict(
        name="Henry Kuhn", first="Henry", surname="Kuhn", des=["CA(SA)"],
        status="HIGH_CONFIDENCE", qualification_confidence="HIGH", designation_status="HIGH_CONFIDENCE",
        title="Group Financial Manager", normalized_title="Group Financial Manager", seniority_band="S4",
        employer="Attacq Limited", employer_group="Attacq", role_family="Group Accounting",
        industry="Property", sub_industry="Real estate investment trust (commercial and mixed-use)",
        grouped_industry="Property & Real Estate", province="Gauteng", city="Midrand",
        location_confidence="PROBABLE",
        evidence='SA REIT Association profile: "Henry Kuhn is a qualified chartered accountant who after being involved in a number of property company audits during his articles pursued his passion for property in joining the Atterbury Property Group. Since then, he joined the Attacq Limited group assisting the company with the listing in 2013 as well as conversion to a REIT in 2018. He is currently performing the role of Group Financial Manager for the Attacq Group."',
        academic=[],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA",
        source_urls=["https://sareit.co.za/about-2/"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=PROP_TAGS, finance_environment_tags=["Listed Reporting", "IFRS", "Group Reporting", "Consolidations", "Audit"],
        work_history=[dict(employer="Atterbury Property Group", title="Finance role", industry="Property", period="before 2013")],
        career_industry_path="Professional Services (property audits) > Property (Attacq)",
        employer_confidence="CONFIRMED", profile_confidence="HIGH",
        notes="HIGH_CONFIDENCE: \"qualified chartered accountant\" without the CA(SA) string. Also evidences a listing and REIT-conversion project track record.",
    ),
    # ------------------------------------------------------------ Hospitality
    dict(
        name="Laurelle McDonald", first="Laurelle", surname="McDonald", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Southern Sun Limited", employer_group="Southern Sun", role_family="Executive Finance",
        industry="Hospitality", sub_industry="Hotels and resorts",
        grouped_industry="Hospitality, Leisure & Tourism", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE",
        evidence='Southern Sun board page: "L MCDONALD CA (SA), Executive Director - Chief Financial Officer, Date appointed: 30 September 2011. Laurelle McDonald served her articles at Grant Thornton and joined Gold Reef Resorts as Assistant Financial Manager at Silverstar Casino in 2007. She was appointed as the Group Financial Manager and the Company Secretary of Gold Reef Resorts. After the acquisition of Gold Reef Resorts by Tsogo Sun, Laurelle was appointed Corporate Finance and Treasury Manager of Tsogo Sun."',
        academic=[],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="Grant Thornton",
        articles_period="pre-2007",
        source_urls=["https://www.southernsun.com/investors/governance/our-board"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=HOSP_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "Treasury", "Corporate Finance", "IFRS"],
        work_history=[
            dict(employer="Gold Reef Resorts", title="Assistant Financial Manager, then Group Financial Manager and Company Secretary", industry="Hospitality", period="2007-"),
            dict(employer="Tsogo Sun", title="Corporate Finance and Treasury Manager", industry="Hospitality", period="to 2011"),
        ],
        career_industry_path="Professional Services (Grant Thornton) > Hospitality and Gaming (Gold Reef/Tsogo Sun) > Hospitality (Southern Sun)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Southern Sun was unbundled from Tsogo Sun in 2019; articles evidence gives a documented audit-to-industry route. City shown as the group's Johannesburg (Sandton/Fourways) base.",
    ),
    dict(
        name="Marcel von Aulock", first="Marcel", surname="von Aulock", des=["CA(SA)"],
        title="Chief Executive Officer and Executive Director", normalized_title="Chief Executive Officer", seniority_band="S8",
        employer="Southern Sun Limited", employer_group="Southern Sun", role_family="Executive Finance",
        industry="Hospitality", sub_industry="Hotels and resorts",
        grouped_industry="Hospitality, Leisure & Tourism", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE",
        evidence='"Marcel Nikolaus von Aulock (46) Chief Executive Officer CA(SA) Appointed: 10 May 2019" (Tsogo Sun Hotels integrated annual report leadership page). Southern Sun board page: "Marcel Nikolaus von Aulock served his articles at PwC and joined Tsogo Sun as Group Financial Manager in 1999. In 2004 he was promoted to Group Strategic Planning Director, in 2009 he was appointed CFO, and in September 2011 he assumed the role of CEO of Tsogo Sun."',
        academic=["BCom", "BAcc"],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="PwC",
        source_urls=[
            "https://hotels-iar.southernsun.com/reports/tsogosun-hotels-iar-2020/our-leadership.php",
            "https://www.southernsun.com/investors/governance/our-board",
        ],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=HOSP_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "Treasury"],
        work_history=[
            dict(employer="Tsogo Sun", title="Group Financial Manager", industry="Hospitality", period="1999-2004"),
            dict(employer="Tsogo Sun", title="Group Strategic Planning Director", industry="Hospitality", period="2004-2009"),
            dict(employer="Tsogo Sun", title="Chief Financial Officer", industry="Hospitality", period="2009-2011"),
            dict(employer="Tsogo Sun", title="Chief Executive Officer", industry="Hospitality", period="2011-2017"),
        ],
        career_industry_path="Professional Services (PwC articles) > Hospitality (Tsogo Sun/Southern Sun)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Classic audit > industry finance > CFO > CEO pathway in a single listed hospitality group.",
    ),
    # ------------------------------------------------------------ Media & Communications
    dict(
        name="Tim Jacobs", first="Tim", surname="Jacobs", des=["CA(SA)"],
        title="Group Chief Financial Officer", normalized_title="Group Chief Financial Officer", seniority_band="S7",
        employer="MultiChoice Group Limited", employer_group="MultiChoice Group", role_family="Executive Finance",
        industry="Media", sub_industry="Pay television and video entertainment",
        grouped_industry="Media & Communications", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='MultiChoice Group executive team page: "Tim Jacobs, Group CFO - BCom, HDipAcc and CA(SA). Tim is the CFO. He was previously the chief executive officer of MultiChoice Africa Limited and chief financial officer of the Naspers Video Entertainment Segment." MultiChoice South Africa Holdings FY2023 financial statements: "prepared under the supervision of the group\\u2019s Chief Financial Officer, Tim Jacobs CA(SA)."',
        academic=["BCom", "HDipAcc"],
        source_urls=[
            "https://www.multichoice.com/about-us/executive-team/",
            "https://www.multichoice.com/media/4417/mcsah-2023-full-group-financial-statements-signed.pdf",
        ],
        primary_evidence_url="https://www.multichoice.com/about-us/executive-team/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=MEDIA_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Investor Relations", "Debt Funding"],
        work_history=[
            dict(employer="Naspers", title="Chief Financial Officer: Video Entertainment segment", industry="Media", period="to 2018"),
            dict(employer="MultiChoice Africa Limited", title="Chief Executive Officer", industry="Media", period="before 2018"),
        ],
        career_industry_path="Media (Naspers video entertainment) > Media (MultiChoice Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="MultiChoice was unbundled from Naspers and listed on the JSE in 2019; the CFO role carried across the listing.",
    ),
    # ------------------------------------------------------------ Banking & Lending
    dict(
        name="Deon Raju", first="Deon", surname="Raju", des=["CA(SA)", "CFA"],
        title="Group Financial Director", normalized_title="Group Financial Director", seniority_band="S6",
        employer="Absa Group Limited", employer_group="Absa Group", role_family="Executive Finance",
        industry="Banking", sub_industry="Diversified banking group",
        grouped_industry="Banking & Lending", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='Absa Group board and management page: "Deon Raju, Group Financial Director. Deon was appointed as Group Financial Director on 26 April 2024 and he joined the Board on the same day. Prior to this role, he was Absa\\u2019s Group Chief Risk Officer from 1 June 2021 and was a member of the Executive Committee and the Group Treasurer 5 years before that... Qualifications: B Com (Hons); CA (SA); CFA."',
        academic=["B Com (Hons)", "CFA"],
        source_urls=["https://www.absa.africa/about-us/board-and-management/"],
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=BANK_TAGS, finance_environment_tags=["Treasury", "Risk", "Capital Management", "Regulated Reporting", "Group Reporting", "Listed Reporting"],
        work_history=[
            dict(employer="Absa", title="Group Treasurer", industry="Banking", period="to 2021"),
            dict(employer="Absa", title="Group Chief Risk Officer", industry="Banking", period="2021-2024"),
            dict(employer="Absa", title="Roles in Enterprise Risk, Finance, Investment Banking, Credit Portfolio Management and Global Markets", industry="Banking", period="over 20 years"),
        ],
        career_industry_path="Banking (Absa; internal progression from risk and treasury to Group Financial Director)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="A treasury/risk-to-CFO succession path inside one major bank — useful for CFO-succession searches.",
    ),
    dict(
        name="Mike Davis", first="Mike", surname="Davis", alternate_names=["Michael Davis"], des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Nedbank Group Limited", employer_group="Nedbank Group", role_family="Executive Finance",
        industry="Banking", sub_industry="Retail and wholesale banking",
        grouped_industry="Banking & Lending", province="Gauteng", city="Johannesburg",
        location_confidence="CONFIRMED",
        evidence='Nedbank Group executive leadership page: "Mike Davis, Chief Financial Officer, Appointed: October 2020. Qualifications: BCom (Hons), DipAcc, CA (SA), AMP (Insead)... Before joining Nedbank through the acquisition of BoE Bank Limited, Mike completed his articles at Deloitte, where he specialised in banking, treasury and risk management." CFO South Africa records his 2024 CFO of the Year award.',
        academic=["BCom (Hons)", "DipAcc", "AMP (INSEAD)"],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="Deloitte",
        source_urls=["https://personal.nedbank.co.za/content/nedbank/za/en/group/home/executive-leadership/mike-davis.html"],
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=BANK_TAGS, finance_environment_tags=["Treasury", "Capital Management", "Risk", "Regulated Reporting", "Group Reporting", "Listed Reporting"],
        work_history=[
            dict(employer="Deloitte", title="Article clerk, manager, senior manager (banking, treasury and risk)", industry="Professional Services", period="to 1998"),
            dict(employer="BoE Bank Limited / Nedbank", title="Group Executive: Balance Sheet Management", industry="Banking", period="1998-2020"),
        ],
        career_industry_path="Professional Services (Deloitte) > Banking (BoE Bank/Nedbank)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Named CFO of the Year at the 2024 CFO Awards. Work location City of Johannesburg.",
    ),
    # ------------------------------------------------------------ Mining & Energy
    dict(
        name="Meroonisha Kerber", first="Meroonisha", surname="Kerber", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Impala Platinum Holdings Limited", employer_group="Impala Platinum", role_family="Executive Finance",
        industry="Mining", sub_industry="Platinum group metals",
        grouped_industry="Mining & Resources", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='Impala Platinum executive profile: "Meroonisha Kerber, Chief Financial Officer and Director, BCom, HDipAcc, CA(SA). Meroonisha was appointed to the board in August 2018 as chief financial officer and executive director. She previously spent 10 years at Deloitte after which she held various senior positions at Anglo American Platinum Ltd and AngloGold Ashanti Ltd."',
        academic=["BCom", "HDipAcc"],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA", articles_employer="Deloitte (10 years)",
        source_urls=[
            "https://people.equilar.com/bio/org/impala-platinum-holdings-limited/510085",
            "https://zimplats.com/about-us/directors/",
        ],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=MINING_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Audit", "Governance"],
        work_history=[
            dict(employer="Deloitte", title="Audit (10 years)", industry="Professional Services", period="to c.2007"),
            dict(employer="Anglo American Platinum", title="Head of Financial Accounting (11 years)", industry="Mining", period="c.2007-2018"),
            dict(employer="AngloGold Ashanti", title="Senior Vice President: Finance", industry="Mining", period="before 2018"),
        ],
        career_industry_path="Professional Services (Deloitte) > Mining (Anglo American Platinum, AngloGold Ashanti) > Mining (Impala Platinum)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Also a director of Impala Canada, Zimplats Holdings and Impala Bafokeng Resources.",
    ),
    dict(
        name="Sayurie Naidoo", first="Sayurie", surname="Naidoo", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Anglo American Platinum Limited", employer_group="Anglo American", role_family="Executive Finance",
        industry="Mining", sub_industry="Platinum group metals",
        grouped_industry="Mining & Resources", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='Company announcement: "Anglo American Platinum appoints Sayurie Naidoo as chief financial officer and executive director, with effect from 1 May 2024... Sayurie, age 39, is a seasoned finance professional and a registered CA(SA) with a distinguished career at Anglo American. Through 15 years within the group she has held various senior roles and has been responsible for leading Anglo American Platinum\\u2019s financial reporting, performance reporting, governance and controls, and systems integration teams."',
        academic=[],
        source_urls=["https://www.valterraplatinum.com/media_centre/press-releases-2024-26-04-2024a/"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=MINING_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "Financial Control", "Governance", "Systems Finance"],
        work_history=[dict(employer="Anglo American / Anglo American Platinum", title="Senior finance roles including financial reporting, performance reporting, governance and controls, and systems integration", industry="Mining", period="15 years to 2024")],
        career_industry_path="Mining (Anglo American group; internal progression to CFO)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Anglo American Platinum was renamed Valterra Platinum in 2025 following the demerger; the CFO role continues.",
    ),
    dict(
        name="Walt Bruns", first="Walt", surname="Bruns", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Sasol Limited", employer_group="Sasol", role_family="Executive Finance",
        industry="Energy", sub_industry="Energy and chemicals (integrated)",
        grouped_industry="Energy & Utilities", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE",
        evidence='Sasol SENS announcement (13 August 2024): "the Board of Sasol Limited... has appointed Mr Walt Bruns as Chief Financial Officer and executive director of Sasol Limited... Mr Bruns is currently the Chief Financial Officer of Sasol Southern Africa including Energy and Chemicals. He has been with Sasol for 15 years and has held a variety of senior management positions, including more than three years as Chief Financial Officer of Sasol\\u2019s global chemicals business... Mr Bruns is a certified chartered accountant in South Africa. He holds a Bachelor of Commerce degree from the University of Stellenbosch and post graduate diplomas from the University of Cape Town."',
        academic=["BCom (University of Stellenbosch)", "Post graduate diplomas (University of Cape Town)"],
        source_urls=["https://www.prnewswire.com/news-releases/sasol-limited-appointment-of-chief-financial-officer-and-executive-director-302220676.html"],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "Multinational", "South African Group", "Asset Intensive", "Regulated", "Manufacturing", "B2B", "Import / Export"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Capital Management", "Manufacturing Finance"],
        work_history=[
            dict(employer="Sasol", title="Chief Financial Officer: Sasol Southern Africa (Energy and Chemicals)", industry="Energy", period="before 2024"),
            dict(employer="Sasol", title="Chief Financial Officer: global chemicals business", industry="Chemicals", period="3+ years"),
        ],
        career_industry_path="Energy and Chemicals (Sasol; internal progression to group CFO)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Sasol spans energy and chemicals; classified under Energy & Utilities with an Industrial & Manufacturing adjacency.",
    ),
    # ------------------------------------------------------------ Agriculture & Agri-processing
    dict(
        name="Debbie Bester", first="Debbie", surname="Bester", des=["CA(SA)"],
        title="Group Chief Executive Officer", normalized_title="Group Chief Executive Officer", seniority_band="S8",
        employer="Senwes Limited", employer_group="Senwes", role_family="Executive Finance",
        industry="Agribusiness", sub_industry="Grain handling, agri inputs, financing and market access",
        grouped_industry="Agriculture & Agri-processing", province="North West", city="Klerksdorp",
        location_confidence="CONFIRMED",
        evidence='Senwes board of directors page: "Debbie Bester, Group Chief Executive Officer, Director since April 2025, B.Com. (Hons), CA (SA)." Agbiz Grain reports Senwes 2025 group results quoting "Group Chief Executive Officer Debbie Bester".',
        academic=["B.Com. (Hons)"],
        source_urls=[
            "https://senwes.com/governance/board-of-directors",
            "https://senwes.com/",
        ],
        ownership="Private Company", scale="Large Private", jse_listed="false", multinational="false",
        business_model_tags=AGRI_TAGS, finance_environment_tags=["Group Reporting", "Working Capital", "Treasury"],
        work_history=[],
        career_industry_path="Agri-processing / Agribusiness (Senwes)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Senwes is headquartered in Klerksdorp, North West — this record opens the North West province on the map.",
    ),
    dict(
        name="Wayne Edwards", first="Wayne", surname="Edwards", des=["CA(SA)", "ACMA", "CGMA"],
        title="Group Chief Financial Officer (acting)", normalized_title="Group Chief Financial Officer", seniority_band="S7",
        employer="Senwes Limited", employer_group="Senwes", role_family="Executive Finance",
        industry="Agribusiness", sub_industry="Grain handling, agri inputs, financing and market access",
        grouped_industry="Agriculture & Agri-processing", province="North West", city="Klerksdorp",
        location_confidence="CONFIRMED",
        evidence='Senwes board of directors page: "Wayne Edwards, Group Chief Financial Officer (Acting), Director since May 2025, BCom (Acc) Hon. CA(SA), ACMA and CGMA." Agbiz Grain: "Senwes\\u2019 acting group chief financial officer, Wayne Edwards, noted that the group is implementing a turnaround plan in Germany."',
        academic=["BCom (Acc) Hon."],
        source_urls=[
            "https://senwes.com/governance/board-of-directors",
            "https://agbizgrain.co.za/content/resources?page=ag-news",
        ],
        ownership="Private Company", scale="Large Private", jse_listed="false", multinational="false",
        business_model_tags=AGRI_TAGS, finance_environment_tags=["Group Reporting", "Working Capital", "Financial Control"],
        work_history=[],
        career_industry_path="Agri-processing / Agribusiness (Senwes)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Multi-designation CA(SA) + ACMA + CGMA. Directional detail on his earlier career appears only on an aggregator profile that abbreviates his surname; not used as evidence here.",
    ),
    # ------------------------------------------------------------ Cold-chain logistics
    dict(
        name="Brendon Lucke", first="Brendon", surname="Lucke", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Commercial Cold Holdings", employer_group="Commercial Cold Holdings", role_family="Executive Finance",
        industry="Cold-Chain Logistics", sub_industry="Temperature-controlled logistics and cold storage",
        grouped_industry="Logistics & Supply Chain", province="Western Cape", city="Cape Town",
        location_confidence="PROBABLE",
        evidence='Commercial Cold Holdings executive team page: "BRENDON LUCKE, Chief Financial Officer. Brendon has over 20 years experience in FMCG, supply chain & logistics. Prior to joining CCH, Brendon was the Group Finance Director at I&J, responsible for Finance, Legal, Supply Chain and Health & Safety. Brendon is a Chartered Accountant, CA(SA)."',
        academic=[],
        source_urls=["https://www.cchcold.com/governance"],
        ownership="Private Equity Backed", scale="Mid-Market", jse_listed="false", multinational="false",
        business_model_tags=COLD_TAGS, finance_environment_tags=["Group Reporting", "Supply Chain Finance", "Working Capital", "Financial Control"],
        work_history=[dict(employer="I&J (Irvin & Johnson)", title="Group Finance Director (Finance, Legal, Supply Chain, Health & Safety)", industry="Food Processing", period="before CCH")],
        career_industry_path="Food Processing (I&J) > Cold-Chain Logistics (Commercial Cold Holdings)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="CCH is an AIIM-led (African Infrastructure Investment Managers) cold-chain platform holding CCS Logistics; the IDEAS Fund has a controlling 59.2% stake. FMCG-to-cold-chain career flow.",
    ),
    dict(
        name="Xoliswa Kula", first="Xoliswa", surname="Kula", des=["CA(SA)"],
        title="Financial Director", normalized_title="Financial Director", seniority_band="S6",
        employer="CCS Logistics", employer_group="Commercial Cold Holdings",
        division="CCS Logistics (an Oceana Group company)", role_family="Executive Finance",
        industry="Cold-Chain Logistics", sub_industry="Cold storage and refrigerated warehousing",
        grouped_industry="Logistics & Supply Chain", province="Western Cape", city="Cape Town",
        location_confidence="PROBABLE",
        evidence='LinkedIn public company page listing: "Xoliswa Kula CA (SA) MCom (Tax) — Financial Director at CCS LOGISTICS"; corroborated by a business-directory row listing "Xoliswa Kula — Director, Financial" at CCS Logistics.',
        academic=["MCom (Tax)"],
        linkedin=None,
        source_urls=["https://www.linkedin.com/company/ccs-logistics-group"],
        ownership="Private Equity Backed", scale="Mid-Market", jse_listed="false", multinational="false",
        business_model_tags=COLD_TAGS, finance_environment_tags=["Tax", "Financial Control", "Group Reporting"],
        work_history=[],
        career_industry_path="Cold-Chain Logistics (CCS Logistics)",
        employer_confidence="PROBABLE", profile_confidence="PROBABLE",
        notes="Employer confidence PROBABLE: CCS Logistics was Oceana's cold-storage division and is now part of the Commercial Cold Holdings platform, so both group attributions circulate. Recorded with the CCH group and the \"an Oceana Group company\" descriptor as stated in the source. No personal LinkedIn URL retrieved.",
    ),
    # ------------------------------------------------------------ Insurance
    dict(
        name="Mhlengi Tenza", first="Mhlengi", surname="Tenza", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Standard Insurance Limited", employer_group="Standard Bank Group", role_family="Executive Finance",
        industry="Insurance", sub_industry="Short-term insurance",
        grouped_industry="Insurance", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Mhlengi Tenza (31), Chief Financial Officer - Standard Insurance Limited". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "Subsidiary", "Regulated", "Multinational", "B2C", "B2B"],
        finance_environment_tags=["Regulated Reporting", "Group Reporting", "IFRS", "Risk"],
        work_history=[],
        career_industry_path="Insurance (Standard Insurance Limited, Standard Bank Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 is restricted to CAs(SA), so appearing on the finalist list is direct designation evidence. City shown as the Standard Bank group head-office metro.",
    ),
    # ------------------------------------------------------------ Industrial & chemicals
    dict(
        name="Riyaad Bhamjee", first="Riyaad", surname="Bhamjee", des=["CA(SA)"],
        title="Vice-President: Strategy and Corporate Development", normalized_title="Vice-President: Strategy and Corporate Development", seniority_band="S5",
        employer="AECI Limited", employer_group="AECI", role_family="Corporate Finance",
        industry="Chemicals", sub_industry="Speciality chemicals and mining explosives",
        grouped_industry="Industrial & Manufacturing", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Riyaad Bhamjee (35), Vice-President Strategy and Corporate Development - AECI Limited". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "Multinational", "South African Group", "Manufacturing", "Multi-site", "B2B", "Import / Export"],
        finance_environment_tags=["Corporate Finance", "M&A", "Strategy"],
        work_history=[],
        career_industry_path="Chemicals and Industrial Manufacturing (AECI)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Corporate-development role in an asset-intensive chemicals group; AECI also serves the mining sector, giving an Industrial > Mining adjacency.",
    ),
    dict(
        name="Arthi Daya", first="Arthi", surname="Daya", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="BBF Safety Group", employer_group="BBF Safety Group", role_family="Executive Finance",
        industry="Industrial Manufacturing", sub_industry="Personal protective equipment and safety footwear",
        grouped_industry="Industrial & Manufacturing", province="Unknown", city=None,
        location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Arthi Daya (35), Chief Financial Officer - BBF Safety Group, Director - Mkhulise Young Minds Development Programme". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Mid-Market", jse_listed="false", multinational="false",
        business_model_tags=["Private Company", "Manufacturing", "Multi-site", "B2B", "High Inventory"],
        finance_environment_tags=["Financial Control", "Manufacturing Finance", "Management Reporting"],
        work_history=[],
        career_industry_path="Industrial Manufacturing (BBF Safety Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. BBF Safety Group manufactures in KwaZulu-Natal, but the source does not state the individual's work location, so location remains Unknown rather than inferred.",
    ),
    # ------------------------------------------------------------ Professional services / engineering
    dict(
        name="Nokuzola Morata", first="Nokuzola", surname="Morata", des=["CA(SA)"],
        title="Group Financial Manager", normalized_title="Group Financial Manager", seniority_band="S4",
        employer="Knight Piésold (Pty) Ltd", employer_group="Knight Piésold", role_family="Group Accounting",
        industry="Engineering", sub_industry="Engineering and environmental consulting",
        grouped_industry="Professional Services", province="Unknown", city=None,
        location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Nokuzola Morata (34), Group Financial Manager - Knight Piésold (Pty) Ltd". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Multinational Private", scale="Multinational", jse_listed="false", multinational="true",
        business_model_tags=["Multinational", "Private Company", "Project Based", "B2B", "Multi-entity"],
        finance_environment_tags=["Group Reporting", "Consolidations", "Project Finance", "Management Reporting"],
        work_history=[],
        career_industry_path="Professional Services / Engineering consulting (Knight Piésold)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Project-based engineering consulting finance — relevant to infrastructure, mining services and construction value chains.",
    ),
    # ------------------------------------------------------------ Public sector
    dict(
        name="Wardah Facoline", first="Wardah", surname="Facoline", des=["CA(SA)"],
        title="Deputy Director: Demand Management", normalized_title="Deputy Director: Demand Management", seniority_band="S4",
        employer="Western Cape Department of Infrastructure", employer_group="Western Cape Provincial Government",
        role_family="Financial Control", industry="Government", sub_industry="Provincial infrastructure delivery",
        grouped_industry="Government & Public Sector", province="Western Cape", city="Cape Town",
        location_confidence="PROBABLE",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Wardah Facoline (33), Deputy Director: Demand Management - Western Cape Department of Infrastructure". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Public Entity", scale="Large Private", jse_listed="false", multinational="false",
        business_model_tags=["State-Owned", "Regulated", "Tender / Contract Driven", "Project Based"],
        finance_environment_tags=["Governance", "Financial Control", "Tender / Procurement", "Management Reporting", "Regulated Reporting"],
        work_history=[],
        career_industry_path="Government & Public Sector (Western Cape Provincial Government)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Procurement/demand-management finance in provincial infrastructure — relevant to construction and infrastructure value chains.",
    ),
    # ------------------------------------------------------------ Technology / VC / other
    dict(
        name="Somah Sachs", first="Somah", surname="Sachs", alternate_names=["Somah Nicholas Beaumont Sachs"],
        des=["CA(SA)"], title="Chief Operating Officer", normalized_title="Chief Operating Officer", seniority_band="S8",
        employer="Tapio", employer_group="Tapio", role_family="Executive Finance",
        industry="Technology", sub_industry="Technology services",
        grouped_industry="Technology & Software", province="Unknown", city=None, location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Somah Nicholas Beaumont Sachs (33), Chief Operating Officer - Tapio". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Small", jse_listed="false", multinational="false",
        business_model_tags=["Private Company", "B2B", "High Growth"],
        finance_environment_tags=["Operational Finance", "Management Reporting"],
        work_history=[],
        career_industry_path="Technology & Software (Tapio)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Location not stated in the source.",
    ),
    dict(
        name="Duval van Zijl", first="Duval", surname="van Zijl", des=["CA(SA)"],
        title="Co-founder and Head of Investments", normalized_title="Head of Investments", seniority_band="S5",
        employer="Holocene", employer_group="Holocene", role_family="Corporate Finance",
        industry="Investment Management", sub_industry="Investment holding",
        grouped_industry="Investments & Capital Markets", province="Unknown", city=None, location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Duval van Zijl (35), Co-founder and Head of Investments - Holocene". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Small", jse_listed="false", multinational="false",
        business_model_tags=["Private Company", "Start-up", "High Growth", "B2B"],
        finance_environment_tags=["Corporate Finance", "M&A", "Investment Appraisal"],
        work_history=[],
        career_industry_path="Investments & Capital Markets (Holocene)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Location not stated in the source.",
    ),
    dict(
        name="Grant Edmond", first="Grant", surname="Edmond", des=["CA(SA)"],
        title="CFO-COO", normalized_title="Chief Financial and Operating Officer", seniority_band="S8",
        employer="DataDrive2030", employer_group="DataDrive2030", role_family="Executive Finance",
        industry="Non-Profit", sub_industry="Data and research for early childhood development",
        grouped_industry="NGO / Non-Profit", province="Western Cape", city="Cape Town",
        location_confidence="CONFIRMED",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Grant Edmond (33), Founder - Just Grace, CFO-COO - DataDrive2030". Peoples Post (Diep River, Cape Town): "Chartered Accountant (CA) Grant Edmond, (33) a resident of Diep River, has been named a finalist in the 2024 SAICA Top 35 Under 35 Awards... As the founder of Just Grace, an award-winning non-profit organisation... the only SAICA-accredited public benefit organisation (PBO) that provides free training to previously disadvantaged youth."',
        academic=[],
        source_urls=[SAICA_2024, "https://peoplespost.co.za/diep-river-chartered-accountant-recognised-in-saica-top-35-under-35-awards-20241126/"],
        ownership="Non-Profit", scale="Small", jse_listed="false", multinational="false",
        business_model_tags=["Non-Profit", "Regulated", "B2B"],
        finance_environment_tags=["Governance", "Statutory Reporting", "Financial Control"],
        work_history=[],
        career_industry_path="NGO / Non-Profit (Just Grace, DataDrive2030)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Media coverage gives a professionally relevant work location (Diep River, Cape Town). Recorded as work location only — no residential inference beyond what the article states.",
    ),
    dict(
        name="Carli Botha", first="Carli", surname="Botha", des=["CA(SA)"],
        title="Director", normalized_title="Director", seniority_band="S6",
        employer="Clinglobal Ltd", employer_group="Clinglobal", role_family="Executive Finance",
        industry="Healthcare", sub_industry="Clinical research services",
        grouped_industry="Healthcare & Life Sciences", province="Unknown", city=None, location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Carli Botha (34), Director - Clinglobal Ltd". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Mid-Market", jse_listed="false", multinational="true",
        business_model_tags=["Private Company", "Multinational", "Multi-site", "B2B", "Regulated", "Project Based"],
        finance_environment_tags=["Group Reporting", "Regulated Reporting", "Financial Control"],
        work_history=[],
        career_industry_path="Healthcare & Life Sciences (Clinglobal)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Clinglobal is a veterinary/clinical research organisation — opens the CRO niche of Healthcare & Life Sciences.",
    ),
    dict(
        name="Frits Reyneke", first="Frits", surname="Reyneke", des=["CA(SA)"],
        title="Chief Executive Officer", normalized_title="Chief Executive Officer", seniority_band="S8",
        employer="Truewood Furniture", employer_group="Truewood Furniture", role_family="Executive Finance",
        industry="Manufacturing", sub_industry="Furniture manufacturing",
        grouped_industry="Industrial & Manufacturing", province="Unknown", city=None, location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Frits Reyneke (34), CEO - Truewood Furniture". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Mid-Market", jse_listed="false", multinational="false",
        business_model_tags=["Private Company", "Manufacturing", "High Inventory", "B2C", "B2B", "Family Owned"],
        finance_environment_tags=["Manufacturing Finance", "Cost Accounting", "Working Capital"],
        work_history=[],
        career_industry_path="Manufacturing (Truewood Furniture)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. CA(SA) in a CEO seat — a finance-to-general-management pathway record.",
    ),
    dict(
        name="Jason Grieve", first="Jason", surname="Grieve", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Crawford Dougall Holdings", employer_group="Crawford Dougall Holdings", role_family="Executive Finance",
        industry="Consumer Services", sub_industry="Facilities and specialist services",
        grouped_industry="Professional Services", province="Unknown", city=None, location_confidence="UNKNOWN",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Jason Grieve (34), Chief Financial Officer - Crawford Dougall Holdings". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="Private Company", scale="Mid-Market", jse_listed="false", multinational="false",
        business_model_tags=["Private Company", "Tender / Contract Driven", "Multi-site", "B2B"],
        finance_environment_tags=["Financial Control", "Management Reporting", "Working Capital"],
        work_history=[],
        career_industry_path="Professional / Consumer Services (Crawford Dougall Holdings)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Location not stated in the source.",
    ),
    dict(
        name="Lindie Scholtz", first="Lindie", surname="Scholtz", des=["CA(SA)"],
        title="Regional Head of Credit", normalized_title="Head of Credit", seniority_band="S5",
        employer="FNB (FirstRand Bank Limited)", employer_group="FirstRand", role_family="Risk",
        industry="Banking", sub_industry="Retail and business banking",
        grouped_industry="Banking & Lending", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Lindie Scholtz (35), Regional Head of Credit - FNB, a Division of FirstRand Bank". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=BANK_TAGS, finance_environment_tags=["Risk", "Credit", "Regulated Reporting", "Management Reporting"],
        work_history=[],
        career_industry_path="Banking (FirstRand/FNB)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Credit-risk leadership is directly relevant to the repo's Credit Risk track as well as Banking & Lending.",
    ),
    dict(
        name="Pamela Mainama", first="Pamela", surname="Mainama", des=["CA(SA)"],
        title="Senior Investment Banker: Financial Solutions Group", normalized_title="Senior Investment Banker", seniority_band="S2",
        employer="Absa Bank Limited", employer_group="Absa Group", role_family="Corporate Finance",
        industry="Banking", sub_industry="Investment banking and structured finance",
        grouped_industry="Banking & Lending", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE",
        evidence='SAICA 2024 Top 35 Under 35 finalists: "Pamela Mainama (32), Senior Investment Banker: Financial Solutions Group - ABSA Bank Limited". The competition recognises young CAs(SA) achievers; every finalist is a CA(SA).',
        academic=[],
        source_urls=[SAICA_2024],
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=BANK_TAGS, finance_environment_tags=["Corporate Finance", "Debt Funding", "Financial Modelling", "Regulated Reporting"],
        work_history=[],
        career_industry_path="Banking (Absa Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation basis: SAICA Top 35 Under 35 finalist. Structured-finance/debt-funding exposure supports the Corporate Finance and Debt Funding tags.",
    ),
]

COMPANIES = []


def company_specs(start_id):
    specs = [
        dict(company_name="Attacq", company_aliases=["Attacq Limited"], website="https://attacq.co.za",
             industry="Property", sub_industry="Real estate investment trust (commercial and mixed-use)",
             headquarters="Waterfall City, Midrand, Gauteng, South Africa",
             south_africa_locations=["Midrand", "Mall of Africa"], company_size_if_public="JSE- and A2X-listed REIT",
             listed_or_private="listed", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO (CONFIRMED from FY2025 AFS) and Group Financial Manager (HIGH_CONFIDENCE) captured; broader finance team not yet swept.",
             source_urls=["https://attacq.co.za/wp-content/uploads/2026/03/attacq-annual-financial-statements-2025.pdf"]),
        dict(company_name="Redefine Properties", company_aliases=["Redefine Properties Limited"], website="https://www.redefine.co.za",
             industry="Property", sub_industry="Real estate investment trust (diversified)",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Cape Town"],
             company_size_if_public="JSE-listed REIT", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="COO/GROUP FD captured (career spans KPMG, Brait, Emperors Palace); finance team sweep outstanding.",
             source_urls=["https://sareit.co.za/about-2/"]),
        dict(company_name="Equites Property Fund", company_aliases=["Equites Property Fund Limited", "Equites"], website="https://www.equites.co.za",
             industry="Property", sub_industry="Logistics and industrial real estate",
             headquarters="Cape Town, Western Cape, South Africa", south_africa_locations=["Cape Town", "Johannesburg", "Durban"],
             company_size_if_public="JSE-listed REIT", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured at HIGH_CONFIDENCE designation tier.",
             source_urls=["https://sareit.co.za/about-2/"]),
        dict(company_name="Southern Sun", company_aliases=["Southern Sun Limited", "Tsogo Sun Hotels Limited"], website="https://www.southernsun.com",
             industry="Hospitality", sub_industry="Hotels and resorts",
             headquarters="Sandton, Gauteng, South Africa", south_africa_locations=["Sandton", "Cape Town", "Durban"],
             company_size_if_public="JSE-listed hotel group; 100+ hotels", listed_or_private="listed", parent_company="HCI (controlling shareholder)",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO (articles at Grant Thornton) and CEO (articles at PwC) both CA(SA) and captured.",
             source_urls=["https://www.southernsun.com/investors/governance/our-board"]),
        dict(company_name="MultiChoice Group", company_aliases=["MultiChoice", "MultiChoice South Africa Holdings"], website="https://www.multichoice.com",
             industry="Media", sub_industry="Pay television and video entertainment",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Cape Town"],
             company_size_if_public="JSE-listed group; approx. 5,000-10,000 employees", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CFO captured with Naspers video-entertainment history.",
             source_urls=["https://www.multichoice.com/about-us/executive-team/"]),
        dict(company_name="Absa Group", company_aliases=["Absa Bank Limited", "Absa"], website="https://www.absa.africa",
             industry="Banking", sub_industry="Diversified banking group",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Cape Town", "Durban"],
             company_size_if_public="JSE-listed major financial institution", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group Financial Director and a Senior Investment Banker captured; group finance team sweep outstanding.",
             source_urls=["https://www.absa.africa/about-us/board-and-management/"]),
        dict(company_name="Nedbank Group", company_aliases=["Nedbank", "Nedbank Limited"], website="https://group.nedbank.co.za",
             industry="Banking", sub_industry="Retail and wholesale banking",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Cape Town"],
             company_size_if_public="JSE-listed major financial institution", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured with Deloitte articles evidence; group finance team sweep outstanding.",
             source_urls=["https://personal.nedbank.co.za/content/nedbank/za/en/group/home/executive-leadership/mike-davis.html"]),
        dict(company_name="Impala Platinum", company_aliases=["Implats", "Impala Platinum Holdings Limited"], website="https://www.implats.co.za",
             industry="Mining", sub_industry="Platinum group metals",
             headquarters="Johannesburg, Gauteng, South Africa",
             south_africa_locations=["Rustenburg", " Johannesburg"], company_size_if_public="JSE-listed group; approx. 63,000 employees",
             listed_or_private="listed", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured with Anglo American Platinum and AngloGold Ashanti history; mine-level finance sweep outstanding.",
             source_urls=["https://people.equilar.com/bio/org/impala-platinum-holdings-limited/510085"]),
        dict(company_name="Anglo American Platinum", company_aliases=["Anglo American Platinum Limited", "Amplats", "Valterra Platinum"],
             website="https://www.valterraplatinum.com", industry="Mining", sub_industry="Platinum group metals",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Rustenburg", "Polokwane"],
             company_size_if_public="JSE-listed group (Anglo American group; renamed Valterra Platinum after the 2025 demerger)",
             listed_or_private="listed", parent_company="Anglo American",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured from the 2024 appointment announcement.",
             source_urls=["https://www.valterraplatinum.com/media_centre/press-releases-2024-26-04-2024a/"]),
        dict(company_name="Sasol", company_aliases=["Sasol Limited", "Sasol South Africa"], website="https://www.sasol.com",
             industry="Energy", sub_industry="Energy and chemicals (integrated)",
             headquarters="Sandton, Gauteng, South Africa", south_africa_locations=["Sandton", "Secunda", "Sasolburg"],
             company_size_if_public="JSE- and NYSE-listed multinational", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CFO captured from the 2024 SENS announcement; Sasol group finance sweep outstanding.",
             source_urls=["https://www.prnewswire.com/news-releases/sasol-limited-appointment-of-chief-financial-officer-and-executive-director-302220676.html"]),
        dict(company_name="Senwes", company_aliases=["Senwes Limited", "Senwes Group"], website="https://senwes.com",
             industry="Agribusiness", sub_industry="Grain handling, agri inputs, financing and market access",
             headquarters="Klerksdorp, North West, South Africa", south_africa_locations=["Klerksdorp", "Bethlehem", "Hinterland"],
             company_size_if_public="Private agribusiness group; approx. 1,000-5,000 employees", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CEO and acting Group CFO both CA(SA) and captured; divisional finance (Agri Credit Solutions) not yet swept.",
             source_urls=["https://senwes.com/governance/board-of-directors"]),
        dict(company_name="Commercial Cold Holdings", company_aliases=["CCH", "CCH Cold"],
             website="https://www.cchcold.com", industry="Cold-Chain Logistics",
             sub_industry="Temperature-controlled logistics and cold storage", headquarters="South Africa",
             south_africa_locations=["Cape Town", "Johannesburg", "Walvis Bay (Namibia)"],
             company_size_if_public="Private platform; approx. 100,000 pallets of storage across six facilities",
             listed_or_private="private", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured (ex-I&J Group Finance Director); platform is AIIM-led with a 59.2% controlling stake and owns CCS Logistics.",
             source_urls=["https://www.cchcold.com/governance"]),
        dict(company_name="CCS Logistics", company_aliases=["CCS Logistics Group", "Oceana Cold Storage"],
             website="https://www.cchcold.com", industry="Cold-Chain Logistics",
             sub_industry="Cold storage and refrigerated warehousing", headquarters="Cape Town, Western Cape, South Africa",
             south_africa_locations=["Cape Town", "Johannesburg", "Walvis Bay (Namibia)"],
             company_size_if_public="Six refrigerated warehouses; part of Commercial Cold Holdings",
             listed_or_private="private", parent_company="Commercial Cold Holdings",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Financial Director captured (employer attribution carried as PROBABLE: Oceana disposal to CCH).",
             source_urls=["https://www.linkedin.com/company/ccs-logistics-group"]),
        dict(company_name="Standard Insurance Limited", company_aliases=["Standard Insurance"], website="https://www.standardbank.co.za",
             industry="Insurance", sub_industry="Short-term insurance", headquarters="Johannesburg, Gauteng, South Africa",
             south_africa_locations=["Johannesburg"], company_size_if_public="Subsidiary of Standard Bank Group",
             listed_or_private="listed", parent_company="Standard Bank Group",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured from SAICA Top 35 Under 35 2024; insurance finance team not yet swept.",
             source_urls=[SAICA_2024]),
        dict(company_name="AECI", company_aliases=["AECI Limited"], website="https://www.aeciworld.com",
             industry="Chemicals", sub_industry="Speciality chemicals and mining explosives",
             headquarters="Sandton, Gauteng, South Africa", south_africa_locations=["Sandton", "Modderfontein"],
             company_size_if_public="JSE-listed multinational", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="VP Strategy and Corporate Development captured; AECI's mining-services exposure makes it a bridge node to Mining.",
             source_urls=[SAICA_2024]),
        dict(company_name="BBF Safety Group", company_aliases=["BBF Safety"], website="https://bbfsafety.co.za",
             industry="Industrial Manufacturing", sub_industry="Personal protective equipment and safety footwear",
             headquarters="KwaZulu-Natal, South Africa", south_africa_locations=["Pietermaritzburg", "Pinetown"],
             company_size_if_public="Private manufacturer", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured from SAICA Top 35 Under 35 2024; location of the individual not evidenced.",
             source_urls=[SAICA_2024]),
        dict(company_name="Knight Piésold", company_aliases=["Knight Piesold (Pty) Ltd"], website="https://www.knightpiesold.com",
             industry="Engineering", sub_industry="Engineering and environmental consulting",
             headquarters="Johannesburg, South Africa", south_africa_locations=["Johannesburg", "Cape Town"],
             company_size_if_public="Multinational consulting engineering group", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group Financial Manager captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="DataDrive2030", company_aliases=["DataDrive 2030"], website=None, industry="Non-Profit",
             sub_industry="Data and research for early childhood development", headquarters="South Africa",
             south_africa_locations=["Cape Town"], company_size_if_public="Non-profit organisation",
             listed_or_private="unknown", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO-COO captured from SAICA Top 35 Under 35 2024 with Cape Town media corroboration.",
             source_urls=[SAICA_2024]),
        dict(company_name="Clinglobal", company_aliases=["Clinglobal Ltd"], website="https://www.clinglobal.com",
             industry="Healthcare", sub_industry="Clinical research services", headquarters="South Africa",
             south_africa_locations=[], company_size_if_public="Multinational contract research group",
             listed_or_private="private", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Director captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="Truewood Furniture", company_aliases=["Truewood"], website=None, industry="Manufacturing",
             sub_industry="Furniture manufacturing", headquarters="South Africa", south_africa_locations=[],
             company_size_if_public="Private manufacturer", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CEO captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="Holocene", company_aliases=["Holocene Investments"], website=None,
             industry="Investment Management", sub_industry="Investment holding", headquarters="South Africa",
             south_africa_locations=[], company_size_if_public="Private investment company",
             listed_or_private="private", parent_company=None, finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Co-founder and Head of Investments captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="Tapio", company_aliases=["Tapio Holdings"], website=None, industry="Technology",
             sub_industry="Technology services", headquarters="South Africa", south_africa_locations=[],
             company_size_if_public="Private company", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="COO captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="Crawford Dougall Holdings", company_aliases=["Crawford Dougall"], website=None,
             industry="Consumer Services", sub_industry="Facilities and specialist services", headquarters="South Africa",
             south_africa_locations=[], company_size_if_public="Private group", listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured from SAICA Top 35 Under 35 2024.",
             source_urls=[SAICA_2024]),
        dict(company_name="Dipula Income Fund", company_aliases=["Dipula"], website="https://www.dipula.co.za",
             industry="Property", sub_industry="Real estate investment trust (diversified)",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg"],
             company_size_if_public="JSE-listed REIT", listed_or_private="listed", parent_company=None,
             finance_team_research_status="NEEDS_RESEARCH",
             finance_team_research_notes="Recorded as the prior employer of Romy Maree (enrichment of acc-0010), not a completed sweep.",
             source_urls=[SAICA_2024]),
    ]
    for offset, spec in enumerate(specs):
        spec["id"] = "cmp-%04d" % (start_id + offset)
        spec.setdefault("date_verified", TODAY)
        spec.setdefault("finance_people_verified_count", 1)
        spec.setdefault("website", None)
        spec.setdefault("company_aliases", [])
        spec.setdefault("headquarters", None)
        spec.setdefault("south_africa_locations", [])
        spec.setdefault("company_size_if_public", None)
        spec.setdefault("listed_or_private", "unknown")
        spec.setdefault("parent_company", None)
        spec.setdefault("source_urls", [])
        spec.setdefault("finance_team_research_status", "NEEDS_RESEARCH")
        spec.setdefault("finance_team_research_notes", "")
        spec.setdefault("industry", None)
        spec.setdefault("sub_industry", None)
        COMPANIES.append(spec)
    return specs


def source_type_for(url):
    lowered = url.lower()
    if "linkedin.com" in lowered:
        return "LinkedIn"
    if ".pdf" in lowered or "jse.co.za" in lowered:
        return "Annual Report"
    if "saica.org.za" in lowered:
        return "Professional Body"
    if any(token in lowered for token in ("cfo.co.za", "moneyweb", "prnewswire", "peoplespost", "agbiz", "miningreview", "businesstech")):
        return "News"
    if any(token in lowered for token in ("equilar", "stockanalysis", "globaldata", "crunchbase", "simplywall")):
        return "Directory"
    return "Employer Website"


def main():
    existing_people = [json.loads(line) for line in open(db_lib.PEOPLE_PATH, encoding="utf-8") if line.strip()]
    known_names = {row["full_name"].strip().lower() for row in existing_people}
    new_specs = [spec for spec in PEOPLE if spec["name"].strip().lower() not in known_names]
    skipped = [spec["name"] for spec in PEOPLE if spec["name"].strip().lower() in known_names]

    companies = company_specs(db_lib.next_id(db_lib.COMPANIES_PATH, "cmp"))
    people = db_lib.append_batch(new_specs, companies, None, label="batch 14 (gap-closing sweeps)")

    existing_sources = db_lib.load_existing_ids(db_lib.SOURCES_PATH)
    next_source = db_lib.next_id(db_lib.SOURCES_PATH, "src")
    current = [json.loads(line) for line in open(db_lib.PEOPLE_PATH, encoding="utf-8") if line.strip()]
    by_name = {row["full_name"].strip().lower(): row for row in current}
    rows = []
    for spec in PEOPLE:
        person = by_name.get(spec["name"].strip().lower())
        if person is None:
            continue
        urls = spec.get("source_urls") or []
        for index, url in enumerate(urls):
            rows.append({
                "id": "src-%04d" % next_source,
                "url": url,
                "source_type": source_type_for(url),
                "person_id": person["id"],
                "company_id": None,
                "evidence_type": "qualification_and_current_employment_evidence" if index == 0 else "secondary_employment_or_career_evidence",
                "evidence_summary": person.get("qualification_evidence") or "",
                "qualification_supported": "true" if "CA(SA)" in (person.get("professional_designations") or []) else "null",
                "skill_supported": None,
                "system_supported": None,
                "employment_supported": "true",
                "accessed_date": TODAY,
                "reliability": "PRIMARY" if index == 0 else "STRONG",
                "status": "USED",
            })
            next_source += 1
    added = db_lib.append_records(db_lib.SOURCES_PATH, rows, existing_sources)
    print(f"sources added: {added} | skipped existing names: {skipped}")


if __name__ == "__main__":
    main()
