#!/usr/bin/env python3
"""Batch 9 — LDP Chartered Accountants & Auditors (Stellenbosch) team page:
12 directors/associate directors with explicit per-person CA(SA)/RA wording.
Includes one CONFLICTING designation case (Alicia Haasbroek). Uses db_lib.append_batch."""
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import db_lib  # noqa: E402

PEOPLE = []
COMPANIES = []
SOURCES = []

TEAM_URL = "https://ldp.co.za/our-team/"

PEOPLE += [
    dict(name="André Du Plessis", first="André", surname="Du Plessis", des=["CA(SA)"],
         title="Senior Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="Executive Finance", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "André Du Plessis — Director | CA(SA)". UFS 1984, CA(SA) 1987; left PwC 1991; co-founded Loubser du Plessis Auditors with Tenk Loubser & Francine-Ann du Plessis.',
         academic=["University of the Free State (1984)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (1987); co-founder Loubser du Plessis (1991) → senior director LDP",
         notes="Co-founder of Loubser du Plessis Auditors (1991); senior director of multi-disciplinary LDP group; specialises in management advice, wealth management, taxation."),
    dict(name="Iaan Marx", first="Iaan", surname="Marx", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Iaan Marx — Director | CA(SA) | RA". Stellenbosch 1996 / UNISA 1998; CA(SA) 1999.',
         academic=["University of Stellenbosch (1996)", "UNISA (1998)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (1999); Registered Auditor",
         notes="Specialises in audit & business advisory: manufacturing, construction, property development, retail, transport, private equity, professional services."),
    dict(name="Francois Joubert", first="Francois", surname="Joubert", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Francois Joubert — Director | CA(SA) | RA". Stellenbosch 1995; CA(SA) 1998.',
         academic=["University of Stellenbosch (1995)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (1998); Registered Auditor",
         notes="Specialises in auditing/accounting/consulting for wine farms, construction and retail companies."),
    dict(name="Johann van Rensburg", first="Johann", surname="van Rensburg", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Johann van Rensburg — Director | CA(SA) | RA". Stellenbosch 2005; CA(SA) 2008.',
         academic=["University of Stellenbosch (2005)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (2008); Registered Auditor",
         notes="Specialises in audit, accounting, valuations and corporate finance for SMMEs."),
    dict(name="Jana Goosen", first="Jana", surname="Goosen", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Jana Goosen — Director | CA(SA) | RA". Stellenbosch 2001; CA(SA) 2008.',
         academic=["University of Stellenbosch (2001)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (2008); Registered Auditor",
         notes="Specialises in audits of large private groups; advanced B-BBEE consulting experience."),
    dict(name="Willene van Zyl", first="Willene", surname="van Zyl", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Willene van Zyl — Director | CA(SA) | RA". Stellenbosch 2007; CA(SA) 2012.',
         academic=["University of Stellenbosch (2007)"],
         source_urls=[TEAM_URL],
         route="CA(SA) (2012); Registered Auditor",
         notes="Specialises in property and agricultural sectors."),
    dict(name="Emile de Villiers", first="Emile", surname="de Villiers", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Emile de Villiers — Director | CA(SA) | RA". Stellenbosch BAcc (Hons) 2011; "completed her articles at a medium-sized audit firm in Cape Town"; CA(SA) 2014; Registered Assessor 2018; RA 2025.',
         academic=["Stellenbosch University — BAcc (Hons), 2011"],
         source_urls=[TEAM_URL],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="Medium-sized audit firm (Cape Town)",
         articles_period="before 2014", articles_location="Cape Town",
         route="BAcc(Hons) → articles (Cape Town) → CA(SA) 2014 → RA 2025",
         career=[{"employer": "Group (EMEA)", "title": "Financial Reporter, Group Financial Controller, CFO", "years": "—"},
                 {"employer": "LDP", "title": "Director", "years": "—"}],
         notes="Prior EMEA financial reporting / group financial controller / CFO experience; IFRS & IFRS for SMEs focus."),
    dict(name="Cornell van Eeden", first="Cornell", surname="van Eeden", des=["CA(SA)"],
         title="Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Cornell van Eeden — Director | CA(SA) | RA". University of Bloemfontein 2015; CA(SA) 2018; RA 2021; Registered Assessor 2023.',
         academic=["University of the Free State (Bloemfontein), 2015"],
         source_urls=[TEAM_URL],
         route="CA(SA) 2018; RA 2021; Registered Assessor 2023",
         career=[{"employer": "LDP", "title": "Manager (3 years)", "years": "—"},
                 {"employer": "Cape Town firm", "title": "Manager / Associate (2 years)", "years": "—"},
                 {"employer": "LDP", "title": "Director", "years": "c.2023–present"}],
         notes="Audit experience across wine & fruit farms, estate agents, sectional title, attorneys, hotels, manufacturing, engineering, wholesale."),
    dict(name="Jana van Zyl", first="Jana", surname="van Zyl", des=["CA(SA)"],
         title="Associate Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Jana van Zyl — Associate Director | CA(SA) | RA". Stellenbosch 2017; LDP audit trainee; UNISA Honours 2019; CA(SA) 2022; RA 2025.',
         academic=["Stellenbosch University (2017)", "UNISA — Honours (2019)"],
         source_urls=[TEAM_URL],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="LDP",
         articles_period="2017–c.2020", articles_location="Stellenbosch",
         route="Audit trainee at LDP → UNISA Honours → CA(SA) 2022 → RA 2025",
         notes="Expertise in construction, property, retail, transport."),
    dict(name="Nadia Van Der Westhuizen", first="Nadia", surname="Van Der Westhuizen", des=["CA(SA)"],
         title="Associate Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Nadia Van Der Westhuizen — Associate Director | CA(SA) | RA". BCom UP; BCom Hons UJ; "She completed her traineeship at LDP (3 years)"; international secondment; Audit Director at another firm 2 years.',
         academic=["University of Pretoria — BCom (Accounting Sciences)", "University of Johannesburg — BCom Hons"],
         source_urls=[TEAM_URL],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="LDP",
         articles_period="3 years", articles_location="Stellenbosch",
         route="Traineeship at LDP → CA(SA) + RA (IRBA)",
         career=[{"employer": "(international secondment)", "title": "Financial management role", "years": "—"},
                 {"employer": "Another firm", "title": "Audit Director (2 years)", "years": "—"},
                 {"employer": "LDP", "title": "Associate Director", "years": "—"}],
         notes="Registered Auditor and qualified CA(SA)."),
    dict(name="Thinus Le Roux", first="Thinus", surname="Le Roux", des=["CA(SA)"],
         title="Associate Director", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page: "Thinus Le Roux — Associate Director | CA(SA) | RA". North-West University 2015/2016; CA(SA) 2019; RA 2023; "began his articles in 2017 ... recognised as the top trainee"; Associate Director 2022.',
         academic=["North-West University — undergraduate (2015), Honours (2016)"],
         source_urls=[TEAM_URL],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="LDP (implied)",
         articles_period="began 2017", articles_location="Stellenbosch (implied)",
         route="Articles from 2017 (top trainee) → CA(SA) 2019 → RA 2023 → Associate Director 2022",
         notes="Exposure across agriculture, financial services, retail, manufacturing, energy, mining; plus tax consulting."),
    dict(name="Alicia Haasbroek", first="Alicia", surname="Haasbroek", des=[],
         status="CONFLICTING", qualified="unknown",
         designation_status="CONFLICTING", qualification_confidence="CONFLICTING",
         title="Associate Director (IT)", employer="LDP Chartered Accountants and Auditors Inc.",
         role_family="Other", function="IT audit / systems", industry="Accounting / Audit", sub_industry="Audit, advisory & tax",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         evidence='LDP team page heading: "Alicia Haasbroek — Associate Director | CA(SA)" BUT bio states "She is eligible to register as a Chartered Accountant (SA) and is currently pursuing her CISA qualification through ISACA". CONFLICTING: heading implies CA(SA); bio says only eligible.',
         academic=[],
         source_urls=[TEAM_URL],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="LDP",
         articles_period="2014–2016", articles_location="Stellenbosch",
         route="Traineeship at LDP 2014–2016 → Audit Senior 2018 → Head of IT 2019 → Associate Director of IT 2026; CA(SA) eligibility (heading)/not yet registered (bio)",
         career=[{"employer": "Equity investment firm", "title": "Trader (investment research & advisory)", "years": "2017"},
                 {"employer": "LDP", "title": "Audit Senior → Head of IT → Associate Director of IT", "years": "2018–present"}],
         notes="CONFLICTING CA(SA): firm heading shows CA(SA) but bio says 'eligible to register'. Pursuing CISA (ISACA). IT audit & systems specialisation."),
]

COMPANIES += [
    dict(id="cmp-0070", company_name="LDP Chartered Accountants and Auditors Inc.", company_aliases=["LDP", "Loubser du Plessis", "LDP Inc."],
         website="https://ldp.co.za/", industry="Accounting / Audit", sub_industry="Audit, advisory & tax (multi-disciplinary)",
         south_africa_locations=["Stellenbosch (HQ)", "Pretoria"],
         source_urls=[TEAM_URL], date_verified=db_lib.TODAY),
]

src_urls = [
    (TEAM_URL, "Employer Website", "LDP team page: André Du Plessis, Iaan Marx, Francois Joubert, Johann van Rensburg, Jana Goosen, Willene van Zyl, Emile de Villiers, Cornell van Eeden, Jana van Zyl, Nadia Van Der Westhuizen, Thinus Le Roux, Alicia Haasbroek (CA(SA)/RA wording per person)."),
]
sid = db_lib.next_id(db_lib.SOURCES_PATH, "src")
for url, typ, summ in src_urls:
    SOURCES.append(dict(id="src-%04d" % sid, url=url, source_type=typ, person_id=None, company_id=None,
                        evidence_type="GENERAL", evidence_summary=summ,
                        qualification_supported=True, skill_supported=None, system_supported=None,
                        employment_supported=True, accessed_date=db_lib.TODAY,
                        reliability="STRONG", status="USED"))
    sid += 1

people = db_lib.append_batch(PEOPLE, company_specs=COMPANIES, source_specs=SOURCES, label="Batch 9 (LDP Stellenbosch)")
