#!/usr/bin/env python3
"""Batch 5 — Western Cape focus: named CA(SA)/AGA(SA)/PA(SA) individuals with
on-page, explicit designation evidence (Streets, McA, Superside, Brenn-O-Kem,
Cape Chamber, Schoemans, Sage directories), plus two Forvis Mazars CAs(SA).
Uses db_lib.append_batch(people_specs, company_specs, source_specs)."""
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import db_lib  # noqa: E402

PEOPLE = []
COMPANIES = []
SOURCES = []

STREETS_URL = "https://www.streets.uk/our-offices/cape-town-south-africa/"
MCA_URL = "https://mca-acc.co.za/"

# ---------------- Western Cape — CONFIRMED designations (on-page wording verified) ----------------
PEOPLE += [
    # Streets — firm website lists designations under each name
    dict(name="Alexis Sacks", first="Alexis", surname="Sacks", des=["CA(SA)"],
         title="Joint Managing Director", employer="Streets Chartered Accountants (Cape Town)",
         role_family="Executive Finance", industry="Accounting / Audit", sub_industry="Chartered accountants & auditors",
         province="Western Cape", city="Cape Town", suburb="Kenilworth", location_confidence="HIGH",
         evidence='Firm website team card: "Alexis Sacks — Joint Managing Director, B. Comm CA (SA)". Office address Kenilworth.',
         academic=["BCom"], source_urls=[STREETS_URL],
         notes="Joint MD of Streets' Cape Town office (formerly MD Accountants & Auditors, rebranded MD Streets Jan 2026)."),
    dict(name="Dave Rich", first="Dave", surname="Rich", des=["CA(SA)"],
         title="Joint Managing Director", employer="Streets Chartered Accountants (Cape Town)",
         role_family="Executive Finance", industry="Accounting / Audit", sub_industry="Chartered accountants & auditors",
         province="Western Cape", city="Cape Town", suburb="Kenilworth", location_confidence="HIGH",
         evidence='Firm website team card: "Dave Rich — Joint Managing Director, B. Comm CA (SA)". Office address Kenilworth.',
         academic=["BCom"], source_urls=[STREETS_URL],
         notes="Joint MD of Streets' Cape Town office."),
    dict(name="Fatima Bapukee", first="Fatima", surname="Bapukee", des=["CA(SA)"],
         title="Director", employer="Streets Chartered Accountants (Cape Town)",
         role_family="Financial Accounting", industry="Accounting / Audit", sub_industry="Chartered accountants & auditors",
         province="Western Cape", city="Cape Town", suburb="Kenilworth", location_confidence="HIGH",
         evidence='Firm website team card: "Fatima Bapukee — Director, Chartered Accountant (SA) PG DIP (Tax)".',
         academic=["PG Dip (Tax)"], source_urls=[STREETS_URL],
         notes="Director; tax specialisation per PG Dip (Tax)."),
    # McA — firm website lists designations under each name
    dict(name="Uwe Birkenstock", first="Uwe", surname="Birkenstock", des=["CA(SA)"],
         title="Director", employer="McA Durbanville Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Auditing & tax practice",
         province="Western Cape", city="Durbanville", location_confidence="HIGH",
         evidence='Firm website: "Uwe Birkenstock — Director McA Durbanville Inc. - Auditing & Tax - CA(SA)". Address Goedemoed Rd, Durbanville.',
         source_urls=[MCA_URL], notes="McA Durbanville Inc. auditing & tax director."),
    dict(name="Juan Spies", first="Juan", surname="Spies", des=["CA(SA)"],
         title="Director", employer="McA Durbanville Inc.",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="Auditing & tax practice",
         province="Western Cape", city="Durbanville", location_confidence="HIGH",
         evidence='Firm website: "Juan Spies — Director McA Durbanville Inc. - Auditing & Tax - CA(SA)". Address Goedemoed Rd, Durbanville.',
         source_urls=[MCA_URL], notes="McA Durbanville Inc. auditing & tax director."),
    dict(name="Lézanne Dirkse van Schalkwyk", first="Lézanne", surname="Dirkse van Schalkwyk",
         des=["AGA(SA)"], title="Accounting Manager", employer="McA Inc.",
         role_family="Financial Accounting", industry="Accounting / Audit", sub_industry="Accounting & tax practice",
         province="Western Cape", city="Durbanville", location_confidence="HIGH",
         evidence='Firm website: "Lézanne Dirkse van Schalkwyk — Accounting Manager AGA(SA)".',
         source_urls=[MCA_URL], notes="McA Inc. (Durbanville) accounting manager."),
    # Justin Stohr / Trevor McLachlan: the site states "SAIPA" (the body), not the literal
    # "PA(SA)" designation string — captured as HIGH_CONFIDENCE, NOT in the CONFIRMED population.
    dict(name="Justin Stohr", first="Justin", surname="Stohr", des=["PA(SA)"], status="HIGH_CONFIDENCE",
         designation_status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
         title="Director", employer="McA Accounting & Tax Services Inc.",
         role_family="Financial Accounting", industry="Accounting / Audit", sub_industry="Accounting & tax practice",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         evidence='Firm website: "Justin Stohr — Director McA Accounting & Tax Services Inc. - SAIPA".',
         source_urls=[MCA_URL],
         notes="SAIPA-designate director; PA(SA) inferred from 'SAIPA' credential (firm team page, not a membership register)."),
    dict(name="Trevor McLachlan", first="Trevor", surname="McLachlan", des=["PA(SA)"], status="HIGH_CONFIDENCE",
         designation_status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
         title="Founder and Executive Consultant", employer="McA Inc.",
         role_family="Financial Accounting", industry="Accounting / Audit", sub_industry="Accounting & tax practice",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         evidence='Firm website: "Trevor McLachlan — Founder and Executive Consultant - SAIPA".',
         source_urls=[MCA_URL],
         notes="Founder of McA Inc. (est. 1994, Cape Town); PA(SA) inferred from 'SAIPA' credential."),
    # LinkedIn — explicit designation + date
    dict(name="Ashley Hanekom", first="Ashley", surname="Hanekom", des=["CA(SA)"],
         title="Finance leader", employer="Superside",
         role_family="Other", industry="Technology", sub_industry="Design subscription / creative services",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Finance leader and Chartered Accountant (CA(SA)) with over 10 years of experience"; licence "Chartered Accountant - South Africa SAICA CA(SA) Issued Dec 2015"; University of Cape Town.',
         academic=["University of Cape Town"],
         linkedin="https://www.linkedin.com/in/ashleyhanekom/",
         source_urls=["https://www.linkedin.com/in/ashleyhanekom/"],
         yoe="10+", yoe_basis="LinkedIn headline: over 10 years of experience.",
         notes="CA(SA) issued Dec 2015. Superside: remote-first design-subscription company with SA (Cape Town) finance base."),
    dict(name="Neil Fourie", first="Neil", surname="Fourie", des=["AGA(SA)"],
         title="Senior Accountant", employer="Brenn-O-Kem",
         role_family="Financial Accounting", industry="Manufacturing", sub_industry="Wine spirits & ethanol producer",
         province="Western Cape", city="Stellenbosch", location_confidence="HIGH",
         linkedin_location="Western Cape, South Africa",
         evidence='LinkedIn headline "Neil Fourie AGA(SA)": PwC (Jan 2016–Jan 2021) Trainee Accountant — "SAICA Articles"; Brenn-O-Kem Senior Accountant Jun 2021–present; LCL Logistics (Stellenbosch) Mar–Jun 2021.',
         academic=["Stellenbosch University (BAcc/BCom; inferred — profile lists SAICA academic route)"],
         linkedin="https://www.linkedin.com/in/neil-fourie-aga-sa-2a125b204/",
         source_urls=["https://www.linkedin.com/in/neil-fourie-aga-sa-2a125b204/"],
         articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="PwC",
         articles_period="Jan 2016 – Jan 2021",
         route="SAICA articles at PwC (2016–2021), then AGA(SA)",
         career=[{"employer": "PwC", "title": "Trainee Accountant (SAICA articles)", "years": "Jan 2016 – Jan 2021"},
                 {"employer": "LCL Logistics", "title": "Senior Accountant", "years": "Mar–Jun 2021"},
                 {"employer": "Brenn-O-Kem", "title": "Senior Accountant (group of companies)", "years": "Jun 2021 – present"}],
         yoe="8+", yoe_basis="PwC from Jan 2016.",
         notes="Brenn-O-Kem: wine-spirits/ethanol producer (Stellenbosch/Worcester region); 'Senior Accountant at group of companies' per profile."),
    dict(name="Lian du Plessis", first="Lian", surname="du Plessis", des=["AGA(SA)"],
         title="Manager: Finance and Group Services", employer="Cape Chamber of Commerce & Industry",
         role_family="Financial Control", industry="Non-Profit", sub_industry="Business chamber",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Lian du Plessis (AGA) SA — Manager: Finance and Group Services at Cape Chamber of Commerce & Industry", City of Cape Town.',
         linkedin="https://www.linkedin.com/in/lian-du-plessis-aga-sa-177375149/",
         source_urls=["https://www.linkedin.com/in/lian-du-plessis-aga-sa-177375149/"],
         notes="Finance & Group Services manager at the Cape Chamber."),
    dict(name="Nastassja Nel", first="Nastassja", surname="Nel", des=["AGA(SA)"],
         title="Accountant", employer="Schoemans Registered Auditors and Chartered Accountants",
         role_family="Financial Accounting", industry="Accounting / Audit", sub_industry="Registered auditors",
         province="Western Cape", city="Cape Town", location_confidence="HIGH",
         linkedin_location="City of Cape Town, Western Cape, South Africa",
         evidence='LinkedIn: "Nastassja Nel - AGA(SA)": "I completed my Articles in 2017... and registered as an AGA(SA) at SAICA"; UNISA BCom Accounting (2014–2015) + Postgraduate Accounting (2016–2018).',
         academic=["BCom Accounting — UNISA (2014–2015)", "Postgraduate Accounting — UNISA (2016–2018)"],
         linkedin="https://www.linkedin.com/in/nastassja-nel-71a15364/",
         source_urls=["https://www.linkedin.com/in/nastassja-nel-71a15364/"],
         articles_status="CONFIRMED_EXPLICIT", articles_body="UNKNOWN (articles employer not named)",
         articles_period="completed 2017",
         route="Articles (2017) + honours + AGA(SA) registration at SAICA",
         career=[{"employer": "One Percent Accounting and Auditing", "title": "Director", "years": "Jul 2021 – May 2023"},
                 {"employer": "Schoemans Registered Auditors and Chartered Accountants", "title": "Accountant", "years": "May 2023 – present"}],
         notes="Explicit articles completion (2017) per profile; articles firm not named. AGA(SA) registered at SAICA."),
    dict(name="Ashley Du Plessis", first="Ashley", surname="Du Plessis", des=["AGA(SA)"],
         title="Accountant", employer=None,
         role_family="Financial Accounting", industry=None,
         province="Western Cape", city="Paarl", location_confidence="HIGH",
         linkedin_location="Paarl, Western Cape, South Africa",
         evidence='LinkedIn: "Ashley Du Plessis - Associate General Accountant AGA(SA)"; honour/award "AGA(SA) SAICA Feb 2023"; BCompt Financial Accounting. Prior employer located Paarl, Western Cape.',
         academic=["BCompt (Financial Accounting)"],
         linkedin="https://www.linkedin.com/in/ashley-du-plessis-ba99a716b/",
         source_urls=["https://www.linkedin.com/in/ashley-du-plessis-ba99a716b/"],
         route="AGA(SA) (SAICA), Feb 2023",
         career=[{"employer": "Not disclosed (masked employer, Paarl)", "title": "Finance role", "years": "—"},
                 {"employer": "Not disclosed (masked employer, Polokwane)", "title": "Finance role", "years": "—"}],
         notes="Current employer masked in public snippet; prior roles in Paarl (Western Cape) and Polokwane (Limpopo)."),
]

# Sage One directory listings: explicit "Professional Accountant (SA)" / "PA(SA)" wording
# and body registration stated — directory third-party listings: HIGH_CONFIDENCE.
PEOPLE += [
    dict(name="Mark Augustine", first="Mark", surname="Augustine", des=["PA(SA)"], status="HIGH_CONFIDENCE",
         designation_status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
         title="Professional Accountant (SA)", employer="Pinnacle Accounting",
         role_family="Financial Accounting", industry="Accounting / Audit",
         province="Western Cape", location_confidence="HIGH",
         evidence='Sage One adviser directory: "Mark Augustine — B.Com (ACC); Professional Accountant (SA); Registered SARS Tax Practitioner" (Western Cape).',
         academic=["BCom (Accounting)"],
         source_urls=["https://mtn.sageone.co.za/find-an-accountant"],
         notes="Sage One 'find an accountant' directory — Western Cape practice; SARS tax practitioner."),
    dict(name="Alana Johns", first="Alana", surname="Johns", des=["PA(SA)"], status="HIGH_CONFIDENCE",
         designation_status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
         title="Professional Accountant and Tax Practitioner", employer=None,
         role_family="Financial Accounting", industry="Accounting / Audit",
         province="Western Cape", location_confidence="HIGH",
         evidence='Sage One adviser directory: "Alana Johns — Professional Accountant and Tax Practitioner Registered with SAIPA and SARS" (Western Cape).',
         source_urls=["https://vox.sageone.co.za/find-an-accountant"],
         notes="Sage One 'find an accountant' directory — Western Cape; SAIPA + SARS registered."),
]

# ---------------- Articles confirmed / designation unverified (secondary population) ----------------
PEOPLE.append(dict(
    name="Alan Robbins", first="Alan", surname="Robbins", des=[],
    status="ARTICLES_CONFIRMED_DESIGNATION_UNVERIFIED", qualified="false",
    qualification_confidence="UNVERIFIED", designation_status="UNVERIFIED",
    title="Accounting Director", employer="Sable International",
    role_family="Financial Accounting", industry="Professional Services", sub_industry="FX, migration & accounting",
    province="Western Cape", city="Cape Town", location_confidence="HIGH",
    evidence='Sable International team page: "went to school, studied and completed his articles in Cape Town, after which he started work as an audit manager".',
    academic=[],
    articles_status="CONFIRMED_EXPLICIT", articles_body="UNKNOWN (body not stated)",
    articles_period="before 2003", articles_location="Cape Town",
    route="Articles completed in Cape Town (firm/body not named); audit manager; UK secondment; returned to Cape Town",
    source_urls=["https://www.sableinternational.com/about-us/meet-the-team/accounting-team"],
    career=[{"employer": "Quotient Financial (UK)", "title": "Client accountant", "years": "2003–2005"},
            {"employer": "Interserve PLC (UK)", "title": "Internal auditor", "years": "2005–2007"},
            {"employer": "Quotient / Sable International (Cape Town)", "title": "Client manager → Accounting Director", "years": "2007–present"}],
    notes="Designation NOT stated in source — retained in articles-confirmed/designation-unverified population, NOT the main qualified count.",
))

# ---------------- National (Forvis Mazars) — CONFIRMED ----------------
PEOPLE += [
    dict(name="Peet van der Merwe", first="Peet", surname="van der Merwe", des=["CA(SA)"],
         title="Partner / Director", employer="Forvis Mazars in South Africa",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="International audit network",
         province="Free State", city="Bloemfontein", location_confidence="HIGH",
         linkedin_location="Bloemfontein, Free State, South Africa",
         evidence='LinkedIn headline: "Peet van der Merwe CA(SA) RA — Forvis Mazars in South Africa"; University of the Free State.',
         academic=["University of the Free State"],
         linkedin="https://www.linkedin.com/in/peet-van-der-merwe-ca-sa-ra-8320b7a6/",
         source_urls=["https://www.linkedin.com/in/peet-van-der-merwe-ca-sa-ra-8320b7a6/"],
         notes="CA(SA) + Registered Auditor (RA)."),
    dict(name="Lynette Roeloffze", first="Lynette", surname="Roeloffze", des=["CA(SA)"],
         title="Senior Manager — Audit", employer="Forvis Mazars Group",
         role_family="External Audit", industry="Accounting / Audit", sub_industry="International audit network",
         province="Gauteng", city="Johannesburg", location_confidence="HIGH",
         linkedin_location="City of Johannesburg, Gauteng, South Africa",
         evidence='LinkedIn headline: "Lynette Roeloffze CA(SA), RA — Forvis Mazars Group"; North-West University; memberOf SAICA + IRBA.',
         academic=["North-West University"],
         linkedin="https://www.linkedin.com/in/lynette-roeloffze-ca-sa-ra-0637aa13/",
         source_urls=["https://www.linkedin.com/in/lynette-roeloffze-ca-sa-ra-0637aa13/"],
         notes="CA(SA) + Registered Auditor (RA); member of SAICA and IRBA."),
]

# ---------------- Companies ----------------
COMPANIES += [
    dict(id="cmp-0042", company_name="Streets Chartered Accountants", company_aliases=["Streets", "MD Streets", "MD Accountants & Auditors"],
         website="https://www.streets.uk/", industry="Accounting / Audit", sub_industry="Chartered accountants & auditors",
         south_africa_locations=["Cape Town (Kenilworth)"],
         source_urls=[STREETS_URL], date_verified=db_lib.TODAY),
    dict(id="cmp-0043", company_name="McA Inc.", company_aliases=["McA Accounting & Tax Services Inc.", "McA Durbanville Inc."],
         website="https://mca-acc.co.za/", industry="Accounting / Audit", sub_industry="Accounting, tax & audit practice",
         south_africa_locations=["Durbanville (Cape Town)"],
         source_urls=[MCA_URL], date_verified=db_lib.TODAY),
    dict(id="cmp-0044", company_name="Superside", company_aliases=[],
         website="https://www.superside.com/", industry="Technology", sub_industry="Design subscription / creative services (remote-first)",
         south_africa_locations=["Cape Town (SA finance base)"],
         source_urls=["https://www.linkedin.com/in/ashleyhanekom/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0045", company_name="Brenn-O-Kem", company_aliases=["Brenn-O-Kem (Pty) Ltd"],
         website="https://brennokem.com/", industry="Manufacturing", sub_industry="Wine spirits & ethanol",
         south_africa_locations=["Stellenbosch / Worcester region (Western Cape)"],
         source_urls=["https://www.linkedin.com/in/neil-fourie-aga-sa-2a125b204/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0046", company_name="Cape Chamber of Commerce & Industry", company_aliases=["Cape Chamber"],
         website="https://www.capechamber.co.za/", industry="Non-Profit", sub_industry="Business chamber",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/lian-du-plessis-aga-sa-177375149/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0047", company_name="Schoemans Registered Auditors and Chartered Accountants", company_aliases=["Schoemans"],
         website=None, industry="Accounting / Audit", sub_industry="Registered auditors & chartered accountants",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.linkedin.com/in/nastassja-nel-71a15364/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0048", company_name="Sable International", company_aliases=["Sable FX", "Sable International Group"],
         website="https://www.sableinternational.com/", industry="Professional Services", sub_industry="FX, migration & accounting",
         south_africa_locations=["Cape Town"],
         source_urls=["https://www.sableinternational.com/about-us/meet-the-team/accounting-team"], date_verified=db_lib.TODAY),
    dict(id="cmp-0049", company_name="Forvis Mazars in South Africa", company_aliases=["Forvis Mazars", "Mazars", "Forvis Mazars Group"],
         website="https://www.forvismazars.com/za/", industry="Accounting / Audit", sub_industry="International audit network",
         south_africa_locations=["Cape Town (Century City)", "Johannesburg", "Bloemfontein", "Pretoria"],
         source_urls=["https://www.linkedin.com/in/peet-van-der-merwe-ca-sa-ra-8320b7a6/",
                      "https://www.linkedin.com/in/lynette-roeloffze-ca-sa-ra-0637aa13/"], date_verified=db_lib.TODAY),
    dict(id="cmp-0050", company_name="Pinnacle Accounting", company_aliases=[],
         website=None, industry="Accounting / Audit", sub_industry="Accounting practice",
         south_africa_locations=["Western Cape"],
         source_urls=["https://mtn.sageone.co.za/find-an-accountant"], date_verified=db_lib.TODAY),
]

# ---------------- Sources ----------------
src_urls = [
    (STREETS_URL, "Employer Website", "Streets Cape Town leadership: Alexis Sacks & Dave Rich (B. Comm CA(SA)); Fatima Bapukee (Chartered Accountant (SA) PG Dip Tax); Juanita Roman (PG Dip Tax, no designation)."),
    (MCA_URL, "Employer Website", "McA Inc. team: Uwe Birkenstock & Juan Spies CA(SA); Lézanne Dirkse van Schalkwyk AGA(SA); Justin Stohr & Trevor McLachlan SAIPA."),
    ("https://www.linkedin.com/in/ashleyhanekom/", "LinkedIn", "Ashley Hanekom CA(SA) (issued Dec 2015, SAICA), Superside, Cape Town."),
    ("https://www.linkedin.com/in/neil-fourie-aga-sa-2a125b204/", "LinkedIn", "Neil Fourie AGA(SA), Brenn-O-Kem; PwC SAICA articles 2016–2021."),
    ("https://www.linkedin.com/in/lian-du-plessis-aga-sa-177375149/", "LinkedIn", "Lian du Plessis AGA(SA), Cape Chamber of Commerce & Industry."),
    ("https://www.linkedin.com/in/nastassja-nel-71a15364/", "LinkedIn", "Nastassja Nel AGA(SA), Schoemans auditors Cape Town; articles completed 2017."),
    ("https://www.linkedin.com/in/ashley-du-plessis-ba99a716b/", "LinkedIn", "Ashley Du Plessis AGA(SA) (SAICA Feb 2023), Paarl."),
    ("https://www.sableinternational.com/about-us/meet-the-team/accounting-team", "Employer Website", "Alan Robbins: completed articles in Cape Town; Accounting Director Sable International."),
    ("https://www.linkedin.com/in/peet-van-der-merwe-ca-sa-ra-8320b7a6/", "LinkedIn", "Peet van der Merwe CA(SA) RA — Forvis Mazars, Bloemfontein."),
    ("https://www.linkedin.com/in/lynette-roeloffze-ca-sa-ra-0637aa13/", "LinkedIn", "Lynette Roeloffze CA(SA), RA — Forvis Mazars Group, Johannesburg."),
    ("https://vox.sageone.co.za/find-an-accountant", "Directory", "Sage One adviser directory (Vox) — Alana Johns PA(SA) & tax practitioner, SAIPA/SARS registered, Western Cape."),
    ("https://mtn.sageone.co.za/find-an-accountant", "Directory", "Sage One adviser directory (MTN) — Mark Augustine Professional Accountant (SA), Western Cape."),
]
sid = db_lib.next_id(db_lib.SOURCES_PATH, "src")
for url, typ, summ in src_urls:
    SOURCES.append(dict(id="src-%04d" % sid, url=url, source_type=typ, person_id=None, company_id=None,
                        evidence_type="GENERAL", evidence_summary=summ,
                        qualification_supported=True, skill_supported=None, system_supported=None,
                        employment_supported=True, accessed_date=db_lib.TODAY,
                        reliability="STRONG", status="USED"))
    sid += 1

people = db_lib.append_batch(PEOPLE, company_specs=COMPANIES, source_specs=SOURCES, label="Batch 5 (Western Cape)")
