#!/usr/bin/env python3
"""Batch 13 - CA(SA) master-mapping layer: senior finance leadership discovered across
South African commerce and industry (FMCG, food manufacturing, agriculture, mining,
logistics, retail, telecoms, insurance, healthcare, construction materials).

Every person in this batch has an explicit CA(SA) / Chartered Accountant (SA) designation
statement in the cited public source, plus an evidenced employer and role. Records carry the
extended mapping fields (seniority band, grouped industry, associated industry groups,
employer normalisation, business-model tags, career path) introduced by the CA(SA) master
research instruction.

Evidence classes follow the repo rule: business-model tags are employer facts from the cited
source; finance-environment tags are only attached where the source itself supports them.
"""
import json
import os
import sys

BASE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, BASE)
import db_lib  # noqa: E402

TODAY = "2026-10-01"

FMCG_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Manufacturing", "Multi-site", "High Inventory", "B2C", "FMCG Route-to-Market"]
RETAIL_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Retail Network", "Multi-site", "High Inventory", "B2C", "Regulated"]
MINING_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Regulated", "B2B", "Import / Export"]
LOGISTICS_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Multi-site", "B2B", "Fleet Intensive"]
AGRI_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Import / Export", "B2B", "Multi-site"]
INSURANCE_TAGS = ["JSE Listed", "Listed Company", "South African Group", "Regulated", "Multi-site", "B2C", "B2B2C"]

PEOPLE = [
    # ---------------------------------------------------------------- Tiger Brands
    dict(
        name="Tjaart Kruger", first="Tjaart", surname="Kruger", des=["CA(SA)"],
        title="Chief Executive Officer", normalized_title="Chief Executive Officer", seniority_band="S8",
        employer="Tiger Brands Limited", employer_group="Tiger Brands", role_family="Executive Finance",
        industry="FMCG", sub_industry="Food, home and personal care manufacturing",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Tiger Brands Integrated Annual Report 2024 - executive committee: "TJAART KRUGER 64, Chief executive officer, appointed November 2023. Qualifications: CA(SA), PMD. Tjaart is a CA(SA) with a PMD from Harvard Business School..."',
        academic=["PMD, Harvard Business School"],
        linkedin=None,
        source_urls=["https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php"],
        primary_evidence_url="https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS, finance_environment_tags=[],
        work_history=[
            dict(employer="Premier Foods", title="Chief Executive Officer", industry="Food Manufacturing", period="2011-2021"),
            dict(employer="Afrox Limited", title="Chief Executive Officer", industry="Industrial Manufacturing", period="2007-2011"),
            dict(employer="Country Bird Proprietary Limited", title="Chief Executive Officer", industry="Food Manufacturing", period=""),
            dict(employer="ICS Foods Limited (now Astral Foods)", title="Divisional Managing Director", industry="Food Manufacturing", period=""),
            dict(employer="Tiger Brands", title="Managing Executive: Pharmaceuticals and Grains", industry="FMCG", period="2001-2007"),
        ],
        career_industry_path="Food Manufacturing (Astral/ICS) > Industrial Manufacturing (Afrox) > Food Manufacturing (Premier) > FMCG (Tiger Brands)",
        employer_confidence="PROBABLE", profile_confidence="CONFIRMED",
        notes="Employer evidence is the FY2024 integrated report (as at 30 September 2024). Location shown as Gauteng/Sandton on the basis of Tiger Brands' Johannesburg head office; individual's city not stated by the source.",
    ),
    dict(
        name="Thushen Govender", first="Thushen", surname="Govender", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Tiger Brands Limited", employer_group="Tiger Brands", role_family="Executive Finance",
        industry="FMCG", sub_industry="Food, home and personal care manufacturing",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Tiger Brands Integrated Annual Report 2024 - executive committee: "THUSHEN GOVENDER 48, Chief financial officer, appointed January 2024. Qualifications: CA(SA), MBA. Thushen re-joined Tiger Brands from Aspen Pharmacare, where he was group commercial officer..."',
        academic=["MBA"],
        linkedin=None,
        source_urls=["https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php"],
        primary_evidence_url="https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS,
        finance_environment_tags=["Listed Reporting", "Commercial Finance", "Investor Relations"],
        work_history=[
            dict(employer="Aspen Pharmacare", title="Group Commercial Officer", industry="Pharmaceuticals", period="before 2024"),
            dict(employer="Pioneer Foods Group", title="Executive (international strategy and global exports)", industry="Food Manufacturing", period=""),
            dict(employer="Tiger Brands", title="Group Strategy, Investor Relations and Business Development Executive", industry="FMCG", period="earlier tenure"),
        ],
        career_industry_path="Pharmaceuticals (Aspen) & Food Manufacturing (Pioneer Foods) > FMCG (Tiger Brands)",
        employer_confidence="PROBABLE", profile_confidence="CONFIRMED",
        notes="Finance-environment tags trace to stated responsibilities (group commercial officer; investor relations and business development executive) rather than title alone. Employer evidence FY2024 integrated report.",
    ),
    dict(
        name="Dumo Mfini", first="Dumo", surname="Mfini", des=["CA(SA)"],
        title="Managing Director: Culinary", normalized_title="Managing Director: Culinary", seniority_band="S8",
        employer="Tiger Brands Limited", employer_group="Tiger Brands", division="Culinary",
        role_family="Executive Finance", industry="FMCG", sub_industry="Food manufacturing",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Tiger Brands Integrated Annual Report 2024 - executive committee: "DUMO MFINI 37, Managing director: Culinary, appointed February 2024. Qualifications: CA(SA), Post-graduate Diploma in Accounting, BAcc... As finance director: Enterprise Food... As finance director: Culinary division..."',
        academic=["Post-graduate Diploma in Accounting", "BAcc"],
        linkedin=None,
        source_urls=["https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php"],
        primary_evidence_url="https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS, finance_environment_tags=["Commercial Finance"],
        work_history=[
            dict(employer="Tiger Brands", title="Finance Director: Culinary", industry="FMCG", period="before 2024"),
            dict(employer="Tiger Brands", title="Finance Director: Enterprise Food", industry="FMCG", period=""),
            dict(employer="Tiger Brands", title="Managing Director: Cereals", industry="FMCG", period=""),
            dict(employer="PepsiCo", title="Finance/commercial role (joined Tiger Brands from PepsiCo in 2016)", industry="FMCG", period="before 2016"),
        ],
        career_industry_path="FMCG (PepsiCo) > FMCG (Tiger Brands)",
        employer_confidence="PROBABLE", profile_confidence="CONFIRMED",
        notes="Finance-to-general-management pathway documented in the integrated report (finance director of two divisions, then MD Cereals, then MD Culinary).",
    ),
    dict(
        name="Grant Pereira", first="Grant", surname="Pereira", des=["CA(SA)"],
        title="Managing Director: Snacks, Treats and Beverages", normalized_title="Managing Director: Snacks, Treats and Beverages",
        seniority_band="S8", employer="Tiger Brands Limited", employer_group="Tiger Brands",
        division="Snacks, Treats and Beverages", role_family="Executive Finance", industry="FMCG",
        sub_industry="Snacks, treats and beverages", grouped_industry="Consumer & FMCG",
        province="Gauteng", city="Sandton", location_confidence="PROBABLE", country="South Africa",
        evidence='Tiger Brands Integrated Annual Report 2024 - executive committee: "GRANT PEREIRA 52, Managing director: Snacks, Treats and Beverages, appointed May 2024. Qualifications: Bachelor of Business Science (Finance), Post-graduate Diploma in Accounting and Auditing, CA(SA). ... Before joining the company, Grant was the director for Adjacencies at AB InBev..."',
        academic=["Bachelor of Business Science (Finance)", "Post-graduate Diploma in Accounting and Auditing"],
        linkedin=None,
        source_urls=["https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php"],
        primary_evidence_url="https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS, finance_environment_tags=["Commercial Finance"],
        work_history=[
            dict(employer="AB InBev", title="Director for Adjacencies (Beyond Beer, South Africa and nine African markets)", industry="Beverage Manufacturing", period="before 2022"),
            dict(employer="Tiger Brands", title="Managing Director: Snacks and Treats", industry="FMCG", period="2022-2024"),
        ],
        career_industry_path="Beverage Manufacturing (AB InBev) > FMCG (Tiger Brands)",
        employer_confidence="PROBABLE", profile_confidence="CONFIRMED",
        notes="Integration-report biography describes a commercial executive combining marketing and finance leadership roles.",
    ),
    # ---------------------------------------------------------------- RCL Foods
    dict(
        name="Robert Field", first="Robert", surname="Field", alternate_names=["Rob Field"], des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="RCL Foods Limited", employer_group="RCL Foods (Remgro)", role_family="Executive Finance",
        industry="Food Manufacturing", sub_industry="Groceries, baking and sugar",
        grouped_industry="Consumer & FMCG", province="KwaZulu-Natal", city="Westville",
        location_confidence="PROBABLE", country="South Africa",
        evidence='RCL Foods Annual Financial Statements FY2025: "The Annual Financial Statements were compiled under the supervision of Robert Field, CA(SA)" and the audit committee assessment of "Robert Field and the Finance function"; CFO South Africa profile: "Rob Field is a Chartered Accountant (SA) who qualified with Deloitte in Durban... appointed CFO of RCL Foods in July 2004".',
        academic=[],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="Deloitte (Durban)",
        articles_period="pre-1997", articles_location="Durban",
        linkedin=None,
        source_urls=[
            "https://rclfoods.com/wp-content/uploads/2025/09/2025-Annual-Financial-Statements.pdf",
            "https://cfo.co.za/profiles/rob-field/",
        ],
        primary_evidence_url="https://rclfoods.com/wp-content/uploads/2025/09/2025-Annual-Financial-Statements.pdf",
        secondary_evidence_url="https://cfo.co.za/profiles/rob-field/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Manufacturing", "Multi-site", "High Inventory", "Distribution", "B2C", "B2B"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Supply Chain Finance"],
        work_history=[
            dict(employer="RCL Foods", title="Chief Financial Officer", industry="Food Manufacturing", period="2004-present"),
            dict(employer="RCL Foods", title="Group Financial Manager", industry="Food Manufacturing", period="2003-2004"),
            dict(employer="Robertsons Homecare (Pty) Ltd", title="Commercial Director", industry="FMCG", period="1999-2003"),
            dict(employer="Deloitte", title="Audit Manager (articles)", industry="Accounting / Audit", period="until 1999"),
        ],
        career_industry_path="Professional Services (Deloitte) > FMCG (Robertsons) > Food Manufacturing (RCL Foods)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Group Financial Manager and Commercial Director history supports commercial/operational finance tags. RCL Foods' remaining business after the 2023 Vector disposal and 2024 Rainbow unbundling comprises Groceries, Baking, Sugar and Group services.",
    ),
    # ---------------------------------------------------------------- Premier Group
    dict(
        name="Kobus Gertenbach", first="Jacobus", surname="Gertenbach", alternate_names=["Kobus Gertenbach"],
        des=["CA(SA)"], title="Chief Executive Officer and Executive Director",
        normalized_title="Chief Executive Officer", seniority_band="S8",
        employer="Premier Group Limited", employer_group="Premier Group", role_family="Executive Finance",
        industry="Food Manufacturing", sub_industry="Millbake, groceries and international",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Waterfall",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Premier Group (JSE: PMR) executive profile: "Mr. Jacobus Johannes Gertenbach, also known as Kobus, BCompt (Honours), MCom, CA (SA), serves as an Executive Director at Premier Group Limited since April 1, 2021 and is its Chief Executive Officer."',
        academic=["BCompt (Honours)", "MCom"],
        linkedin=None,
        source_urls=["https://simplywall.st/stocks/za/food-beverage-tobacco/jse-pmr/premier-group-shares/management"],
        primary_evidence_url="https://simplywall.st/stocks/za/food-beverage-tobacco/jse-pmr/premier-group-shares/management",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS, finance_environment_tags=[],
        work_history=[],
        career_industry_path="Food Manufacturing (Premier Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Premier Group listed on the JSE in March 2023; historically associated with the Brait/ Nespers portfolio. Location shown as the group's Waterfall head office.",
    ),
    dict(
        name="Fritz Grobbelaar", first="Fritz", surname="Grobbelaar", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer",
        seniority_band="S7", employer="Premier Group Limited", employer_group="Premier Group",
        role_family="Executive Finance", industry="Food Manufacturing", sub_industry="Millbake, groceries and international",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Waterfall",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Premier Group executive profile: "Fritz Grobbelaar BCOMPT, C.A. - Chief Financial Officer and Executive Director" (appointed 2021-08-01).',
        academic=["BCompt"],
        linkedin=None,
        source_urls=["https://stockanalysis.com/quote/jse/PMR/company/"],
        primary_evidence_url="https://stockanalysis.com/quote/jse/PMR/company/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=FMCG_TAGS, finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS"],
        work_history=[],
        career_industry_path="Food Manufacturing (Premier Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation appears as \"C.A.\" in the executive listing and the group's CA(SA) qualification is consistent with the CFO role; marked CONFIRMED on the explicit CA annotation plus JSE CFO disclosure.",
    ),
    # ---------------------------------------------------------------- Astral Foods
    dict(
        name="Kenny Schoeman", first="Kenny", surname="Schoeman", des=["CA(SA)", "ACMA", "CGMA"],
        title="Poultry Processing Executive", normalized_title="Poultry Processing Executive", seniority_band="S8",
        employer="Astral Foods Limited", employer_group="Astral Foods", role_family="Executive Finance",
        industry="Food Manufacturing", sub_industry="Poultry and animal feed",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Astral Foods executive management page: "Kenny\\u2019s qualifications are CA(SA), ACMA, GCMA and LLB. He started his career with Astral in 2010 as Financial Manager: Feed Division, Mozambique... 2022 he was promoted to Business Development Manager of the Group. Kenny was appointed as Managing Director of Agriculture on 1 July 2024, and was appointed as Poultry Processing Executive with effect from 1 February 2025."',
        academic=["LLB"],
        linkedin=None,
        source_urls=["https://www.astralfoods.com/executive-management.html"],
        primary_evidence_url="https://www.astralfoods.com/executive-management.html",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Multinational", "Manufacturing", "Vertically Integrated", "Multi-site", "B2B", "B2C"],
        finance_environment_tags=["Manufacturing Finance", "Cost Accounting", "Operational Finance"],
        work_history=[
            dict(employer="Astral Foods", title="Financial Manager: Feed Division, Mozambique", industry="Food Manufacturing", period="2010-2011"),
            dict(employer="Astral Foods", title="Financial Manager: Poultry Division, Mountain Valley / Festive", industry="Food Manufacturing", period="2011-2015"),
            dict(employer="Astral Foods", title="COO: Festive", industry="Food Manufacturing", period="2015-2017"),
            dict(employer="Astral Foods", title="Financial Manager: Poultry Division, Central Region", industry="Food Manufacturing", period="2018-2022"),
            dict(employer="Astral Foods", title="Business Development Manager of the Group", industry="Food Manufacturing", period="2022-2024"),
            dict(employer="Astral Foods", title="Managing Director of Agriculture", industry="Food Manufacturing", period="2024-2025"),
        ],
        career_industry_path="Food Manufacturing (Astral Foods, finance to operations leadership)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Multi-designation CA(SA)+ACMA+CGMA. Career shows a finance-to-operations executive pathway inside one listed poultry group.",
    ),
    dict(
        name="Johan Geel", first="Gideon Johannes", surname="Geel", alternate_names=["Johan Geel"],
        des=["CA(SA)"], title="Chief Financial Officer and Executive Director (from 1 March 2026)",
        normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Astral Foods Limited", employer_group="Astral Foods", role_family="Executive Finance",
        industry="Food Manufacturing", sub_industry="Poultry and animal feed",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Astral Foods SENS announcement reported via company-announcement coverage: "The company named Mr. Gideon Johannes (Johan) Geel as permanent Chief Financial Officer, effective March 1, 2026... Johan Geel, a Chartered Accountant (SA), joins from his role as CFO at AFGRI Limited, bringing experience across FMCG, retail, manufacturing, agro processing, grain management, trading, financing, logistics and agricultural production."',
        academic=[],
        linkedin=None,
        source_urls=["https://simplywall.st/community/narratives/za/food-beverage-tobacco/jse-arl/astral-foods-shares/0brw8lqv-better-south-african-crops-will-fuel-poultry-resurgence/updates/5-analysts-have-kept-their-zar26500-price-target-on-astral-fo"],
        primary_evidence_url="https://simplywall.st/community/narratives/za/food-beverage-tobacco/jse-arl/astral-foods-shares/0brw8lqv-better-south-african-crops-will-fuel-poultry-resurgence/updates/5-analysts-have-kept-their-zar26500-price-target-on-astral-fo",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=FMCG_TAGS + ["Vertically Integrated"],
        finance_environment_tags=["Group Reporting", "Commercial Finance", "Working Capital"],
        work_history=[
            dict(employer="AFGRI Limited", title="Chief Financial Officer", industry="Agriculture", period="until 2026"),
        ],
        career_industry_path="Agriculture (AFGRI) > Food Manufacturing (Astral Foods)",
        employer_confidence="CONFIRMED", profile_confidence="PROBABLE",
        notes="Record reflects the announced appointment effective 1 March 2026. Source is secondary coverage of the SENS announcement; primary SENS document not captured in this pass.",
    ),
    dict(
        name="Henry Enslin", first="Henry", surname="Enslin", des=["CA(SA)"],
        title="Financial Manager: Poultry Commercial Division (acting CFO, February 2026)",
        normalized_title="Financial Manager", seniority_band="S3",
        employer="Astral Foods Limited", employer_group="Astral Foods", division="Poultry Commercial Division",
        role_family="Operational Finance", industry="Food Manufacturing", sub_industry="Poultry and animal feed",
        grouped_industry="Consumer & FMCG", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Astral Foods board announcement: "the Board of Directors of Astral Foods has appointed Mr. Henry Enslin CA(SA) to serve as the acting CFO (not a director) of Astral Foods... Henry currently holds the position of Financial Manager for Astral\\u2019s Poultry Commercial Division. Henry previously held a position as Financial Director of Albany Bakeries a division of Tiger Brands, before joining Astral Foods."',
        academic=[],
        linkedin=None,
        source_urls=["https://www.marketscreener.com/news/astral-foods-limited-announces-appointment-of-henry-enslin-as-acting-cfo-effective-2026-ce7e58ddd080fe24"],
        primary_evidence_url="https://www.marketscreener.com/news/astral-foods-limited-announces-appointment-of-henry-enslin-as-acting-cfo-effective-2026-ce7e58ddd080fe24",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=FMCG_TAGS,
        finance_environment_tags=["Commercial Finance", "Operational Finance", "Manufacturing Finance"],
        work_history=[
            dict(employer="Albany Bakeries (Tiger Brands)", title="Financial Director", industry="Food Manufacturing", period="before Astral"),
        ],
        career_industry_path="Food Manufacturing (Tiger Brands/Albany Bakeries) > Food Manufacturing (Astral Foods)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Substantive role is Financial Manager (S3); the acting-CFO appointment for February 2026 is a temporary elevation and is not used to set the seniority band.",
    ),
    # ---------------------------------------------------------------- Mining
    dict(
        name="Riaan Koppeschaar", first="Riaan", surname="Koppeschaar", des=["CA(SA)"],
        title="Finance Director", normalized_title="Finance Director", seniority_band="S6",
        employer="Exxaro Resources Limited", employer_group="Exxaro Resources", role_family="Executive Finance",
        industry="Mining", sub_industry="Coal and minerals",
        grouped_industry="Mining & Resources", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Exxaro leadership page: "RIAAN KOPPESCHAAR, FINANCE DIRECTOR. BCom (Hons), CA (SA), Advanced Management Programme (INSEAD), Advanced Certificate in Taxation, Advanced Certificate in Treasury Management. Riaan Koppeschaar completed his articles at Coopers & Lybrand in 1995... In July 2016, Koppeschaar was appointed Finance Director."',
        academic=["BCom (Hons)", "Advanced Management Programme (INSEAD)", "Advanced Certificate in Taxation", "Advanced Certificate in Treasury Management"],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="Coopers & Lybrand",
        articles_period="completed 1995", articles_location=None, qualification_year="1995",
        linkedin=None,
        source_urls=["https://www.exxaro.com/our-business/leadership/"],
        primary_evidence_url="https://www.exxaro.com/our-business/leadership/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=MINING_TAGS + ["Multi-site", "Vertically Integrated"],
        finance_environment_tags=["Treasury", "Corporate Finance", "Capital Management", "Debt Funding"],
        work_history=[
            dict(employer="Iscor Limited", title="Managerial roles in treasury and corporate finance", industry="Mining", period="1995-2001"),
            dict(employer="Kumba Resources Limited", title="Managerial roles", industry="Mining", period="2001-2006"),
            dict(employer="Exxaro Resources", title="General Manager: Corporate Finance and Treasury", industry="Mining", period="2006-2016"),
        ],
        career_industry_path="Professional Services (Coopers & Lybrand) > Mining (Iscor/Kumba/Exxaro)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Tenure in corporate finance and treasury before the FD appointment supports the treasury/capital-management tags. Also served as Exxaro acting CEO during the 2025 CEO transition.",
    ),
    dict(
        name="Deon Smith", first="Deon", surname="Smith", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer",
        seniority_band="S7", employer="Thungela Resources Limited", employer_group="Thungela Resources",
        role_family="Executive Finance", industry="Mining", sub_industry="Thermal coal",
        grouped_industry="Mining & Resources", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Thungela "Who we are" leadership page: "Deon Smith, Chief financial officer, executive director. BCom (Hons), CA (SA), CTA. Appointed 1 July 2017... Deon was previously the Chief Financial Officer of Anglo American\\u2019s coal business... responsible for several finance functions across Anglo American and its divisions over 14 years including corporate finance, capital management, shared accounting services and risk and audit."',
        academic=["BCom (Hons)", "CTA"],
        linkedin=None,
        source_urls=["https://www.thungela.com/about-us/who-we-are"],
        primary_evidence_url="https://www.thungela.com/about-us/who-we-are",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=MINING_TAGS + ["Import / Export"],
        finance_environment_tags=["Corporate Finance", "Capital Management", "Shared Services", "Risk", "Internal Audit", "Listed Reporting"],
        work_history=[
            dict(employer="Anglo American", title="Chief Financial Officer, coal business; then strategy and business development", industry="Mining", period="2003-2017"),
        ],
        career_industry_path="Mining (Anglo American) > Mining (Thungela Resources)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Thungela was demerged from Anglo American in 2021; the CFO role carried across the demerger.",
    ),
    dict(
        name="Xolani Mbambo", first="Xolani", surname="Mbambo", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director (from 1 January 2026)",
        normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Kumba Iron Ore Limited", employer_group="Anglo American", role_family="Executive Finance",
        industry="Mining", sub_industry="Iron ore",
        grouped_industry="Mining & Resources", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Mining Review: "Kumba appoints Grindrod CEO Xolani Mbambo as CFO from 2026... Xolani Mbambo, currently CEO of Grindrod Limited, will succeed him as CFO from 1 January 2026... Mbambo is a seasoned executive, holding a Chartered Accountant (CA[SA]) qualification and an Advanced Management Programme (AMP) from Harvard Business School. He brings over 20 years of experience in mining, logistics, and finance, having held senior roles at Grindrod and previously at Anglo American."',
        academic=["Advanced Management Programme (AMP), Harvard Business School"],
        linkedin=None,
        source_urls=["https://www.miningreview.com/news/kumba-appoints-grindrod-ceo-xolani-mbambo-as-cfo-from-2026/"],
        primary_evidence_url="https://www.miningreview.com/news/kumba-appoints-grindrod-ceo-xolani-mbambo-as-cfo-from-2026/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=MINING_TAGS + ["Multinational", "Import / Export", "Asset Intensive"],
        finance_environment_tags=["Corporate Finance", "Business Partnering"],
        work_history=[
            dict(employer="Anglo American", title="Various roles in the mining industry (Johannesburg, London, Mpumalanga, Gaborone)", industry="Mining", period="over a decade to 2013"),
            dict(employer="Grindrod Freight Services", title="Chief Financial Officer", industry="Logistics", period="2013-2018"),
            dict(employer="Grindrod Limited", title="Group Financial Director", industry="Logistics", period="2018-2021"),
            dict(employer="Grindrod Limited", title="Chief Executive Officer", industry="Logistics", period="2021-2025"),
        ],
        career_industry_path="Mining (Anglo American) > Logistics (Grindrod) > Mining (Kumba Iron Ore)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="A documented Mining > Logistics > Mining talent flow; Grindrod CEO until 30 November 2025 (per Grindrod FY2025 AFS).",
    ),
    # ---------------------------------------------------------------- Logistics
    dict(
        name="Fathima Ally", first="Fathima", surname="Ally", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer",
        seniority_band="S7", employer="Grindrod Limited", employer_group="Grindrod", role_family="Executive Finance",
        industry="Logistics", sub_industry="Ports, terminals and freight",
        grouped_industry="Logistics & Supply Chain", province="KwaZulu-Natal", city="Durban",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='Grindrod Limited FY2025 Annual Financial Statements (signed 1 April 2026, Durban): "Fathima Ally CA (SA), Chief Financial Officer (CFO)". Grindrod IAR FY2021: "Fathima Ally, CFO, Grindrod Limited, CA(SA), appointed 1 September 2020. Before joining Grindrod, Fathima was a partner at Deloitte from 2013."',
        academic=[],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA", articles_employer="Deloitte (partner 2013-2020)",
        linkedin=None,
        source_urls=[
            "https://www.grindrod.com/share_holder_documents/document_2586/Grindrod-Limited-2025-Signed-Final-AFS-31-December-2025.pdf",
            "https://www.grindrod.com/iar/2021/about-grindrod",
        ],
        primary_evidence_url="https://www.grindrod.com/share_holder_documents/document_2586/Grindrod-Limited-2025-Signed-Final-AFS-31-December-2025.pdf",
        secondary_evidence_url="https://www.grindrod.com/iar/2021/about-grindrod",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=LOGISTICS_TAGS + ["Import / Export", "Multinational"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "Audit", "Risk", "Governance"],
        work_history=[
            dict(employer="Deloitte", title="Partner (assurance); worked with multinational listed companies", industry="Professional Services", period="2013-2020"),
        ],
        career_industry_path="Professional Services (Deloitte) > Logistics (Grindrod)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Durban signatory in the FY2025 AFS confirms work location at province/city level.",
    ),
    dict(
        name="Peter Mountford", first="Peter", surname="Mountford", des=["CA(SA)"],
        title="Chief Executive Officer", normalized_title="Chief Executive Officer", seniority_band="S8",
        employer="Super Group Limited", employer_group="Super Group", role_family="Executive Finance",
        industry="Logistics", sub_industry="Logistics and mobility solutions",
        grouped_industry="Logistics & Supply Chain", province="Gauteng", city="Sandton",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='Super Group "Our Leadership" page: "Peter Mountford (67) B.Com, B.Acc, HDip Tax, MBA (with distinction, Warwick), CA(SA), Chief Executive Officer... his executive experience includes Managing Director of SAB Diversified Beverages, CEO of the Consumer Logistics Division at Imperial Holdings Limited and Managing Director of Super Group\\u2019s Logistics and Transport Division."',
        academic=["B.Com", "B.Acc", "HDip Tax", "MBA (distinction, Warwick)"],
        linkedin=None,
        source_urls=["https://www.supergroup.co.za/our-leadership/"],
        primary_evidence_url="https://www.supergroup.co.za/our-leadership/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=LOGISTICS_TAGS + ["Multinational", "Import / Export"],
        finance_environment_tags=["Corporate Finance"],
        work_history=[
            dict(employer="SAB Diversified Beverages", title="Managing Director", industry="Beverage Manufacturing", period=""),
            dict(employer="Imperial Holdings", title="CEO: Consumer Logistics Division", industry="Logistics", period=""),
            dict(employer="Super Group", title="Managing Director: Logistics and Transport Division", industry="Logistics", period=""),
        ],
        career_industry_path="Beverage Manufacturing (SAB) > Logistics (Imperial) > Logistics (Super Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Also Deputy Chairman of the Road Freight Association (industry body).",
    ),
    dict(
        name="Colin Brown", first="Colin", surname="Brown", des=["CA(SA)"],
        title="Chief Financial Officer and Debt Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Super Group Limited", employer_group="Super Group", role_family="Executive Finance",
        industry="Logistics", sub_industry="Logistics and mobility solutions",
        grouped_industry="Logistics & Supply Chain", province="Gauteng", city="Sandton",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='Super Group "Our Leadership" page: "Colin Brown (56) B.Compt (Hons), MBL, CA(SA), Chief Financial and Debt Officer. Colin is an experienced financial executive and board director... Since his appointment as CFO in 2010, he has overseen all accounting and finance functions for the Group... His previous roles include CFO and board member of Celcom Group Limited, and Financial Director for EDS Africa Limited and Fujitsu Services South Africa."',
        academic=["B.Compt (Hons)", "MBL (UNISA)"],
        linkedin=None,
        source_urls=["https://www.supergroup.co.za/our-leadership/"],
        primary_evidence_url="https://www.supergroup.co.za/our-leadership/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=LOGISTICS_TAGS + ["Multinational"],
        finance_environment_tags=["Group Reporting", "Listed Reporting", "Debt Funding", "Treasury"],
        work_history=[
            dict(employer="Celcom Group Limited", title="Chief Financial Officer and board member", industry="Telecommunications", period=""),
            dict(employer="EDS Africa Limited", title="Financial Director", industry="Technology", period=""),
            dict(employer="Fujitsu Services South Africa", title="Financial Director", industry="Technology", period=""),
        ],
        career_industry_path="Technology (EDS/Fujitsu) > Telecommunications (Celcom) > Logistics (Super Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Debt Officer designation supports treasury/debt-funding tags.",
    ),
    dict(
        name="Mohammed Akoojee", first="Mohammed", surname="Akoojee", des=["CA(SA)", "CFA"],
        title="CEO and Managing Director: sub-Saharan Africa", normalized_title="Chief Executive Officer",
        seniority_band="S8", employer="DP World", employer_group="DP World", division="Sub-Saharan Africa",
        role_family="Executive Finance", industry="Logistics", sub_industry="Ports, terminals and integrated logistics",
        grouped_industry="Logistics & Supply Chain", province="Gauteng", city="Johannesburg",
        location_confidence="PROBABLE", country="South Africa",
        evidence='DP World/Imperial leadership page: "Mohammed Akoojee, CEO & MD: sub-Saharan Africa at DP World. Qualifications: BCom (Acc) (Hons), CA(SA), CFA. Mohammed Akoojee serves as the CEO & MD of DP World\\u2019s sub-Saharan Africa region... He previously served as the Chief Operating Officer of DP World Global Logistics and as the Chief Executive Officer of Imperial Logistics (Imperial)..."',
        academic=["BCom (Acc) (Hons)", "CFA"],
        linkedin=None,
        source_urls=["https://www.imperiallogistics.com/leadership.php"],
        primary_evidence_url="https://www.imperiallogistics.com/leadership.php",
        ownership="Multinational Private", scale="Multinational", jse_listed="false", multinational="true",
        business_model_tags=["Multinational", "Private Company", "Asset Intensive", "Multi-site", "B2B", "Import / Export", "Retail Network"],
        finance_environment_tags=["Corporate Finance", "M&A", "Investor Relations", "Business Partnering"],
        work_history=[
            dict(employer="Imperial Logistics", title="Chief Executive Officer", industry="Logistics", period="until 2022"),
            dict(employer="DP World Global Logistics", title="Chief Operating Officer", industry="Logistics", period="2022-"),
        ],
        career_industry_path="Logistics (Imperial) > Logistics (DP World)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="DP World acquired Imperial Logistics in 2022; region covers 48 African markets. CFO-level and CEO-level finance background (CFA charterholder).",
    ),
    # ---------------------------------------------------------------- Agriculture
    dict(
        name="Melani De Castro", first="Melani", surname="De Castro", des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director (from 1 April 2026)",
        normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Crookes Brothers Limited", employer_group="Crookes Brothers", role_family="Executive Finance",
        industry="Agriculture", sub_industry="Sugar cane, bananas, macadamias and property",
        grouped_industry="Agriculture & Agri-processing", province="KwaZulu-Natal", city=None,
        location_confidence="PROBABLE", country="South Africa",
        evidence='Crookes Brothers (JSE: CKS) audited AFS FY2026: "prepared under the supervision of Melani De Castro, CA(SA)... Melani De Castro was appointed as Chief Financial Officer and Executive Director of the Company with effect from 1 April 2026." Crookes Brothers AFS 2018 preparer line: "by Nigel Naidoo CA(SA), assisted by Melani De Castro CA(SA) under the supervision of Gregory Veale CA(SA)".',
        academic=[],
        articles_status="QUALIFIED_BUT_ARTICLES_NOT_ESTABLISHED", articles_body="SAICA",
        linkedin=None,
        source_urls=[
            "https://senspdf.jse.co.za/documents/2026/jse/isse/cks/cbl2026.pdf",
            "https://cfo.co.za/people-moves/",
        ],
        primary_evidence_url="https://senspdf.jse.co.za/documents/2026/jse/isse/cks/cbl2026.pdf",
        secondary_evidence_url="https://cfo.co.za/people-moves/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=AGRI_TAGS + ["Multinational", "Project Based"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "IFRS", "Statutory Reporting"],
        work_history=[
            dict(employer="Crookes Brothers", title="Project accountant, rising through the finance function", industry="Agriculture", period="c.2018-2026"),
        ],
        career_industry_path="Agriculture (Crookes Brothers; internal progression)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Province recorded as KwaZulu-Natal (PROBABLE) because Crookes Brothers is a KwaZulu-Natal-based agricultural group; the individual's own city is not stated in the sources. CFO.co.za describes an eight-year climb from project accountant.",
    ),
    # ---------------------------------------------------------------- Food processing / fishing
    dict(
        name="Zaf Mahomed", first="Zaf", surname="Mahomed", alternate_names=["Zafar Mahomed"], des=["CA(SA)"],
        title="Chief Financial Officer and Executive Director", normalized_title="Chief Financial Officer",
        seniority_band="S7", employer="Oceana Group Limited", employer_group="Oceana Group",
        role_family="Executive Finance", industry="Food Processing", sub_industry="Fishing, canned fish and cold storage",
        grouped_industry="Consumer & FMCG", province="Western Cape", city="Cape Town",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='Oceana Group leadership page and Leadership magazine interview: "Zaf is a Chartered Accountant (SA) and holds an MBL from UNISA School of Business Leadership; BCom (Hons) from UNISA and BCom from University of Natal. Zaf took up his role as Oceana\\u2019s CFO and Executive Director of the Oceana Board effective from 1 February 2023... more than 25 years of finance and business experience across multinational and listed companies... telecommunications, food franchise, retail, financial services, real estate and property, food, medical."',
        academic=["MBL (UNISA)", "BCom (Hons) (UNISA)", "BCom (University of Natal)"],
        linkedin=None,
        source_urls=[
            "https://www.oceana.co.za/about-leadership",
            "https://www.leadershiponline.co.za/nothing-lucky-about-these-stars-driving-the-oceana-group/",
        ],
        primary_evidence_url="https://www.oceana.co.za/about-leadership",
        secondary_evidence_url="https://www.leadershiponline.co.za/nothing-lucky-about-these-stars-driving-the-oceana-group/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Multinational", "Manufacturing", "Cold Storage", "Import / Export", "B2B", "B2C", "Asset Intensive"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "Commercial Finance", "Working Capital"],
        work_history=[],
        career_industry_path="Multiple sectors (telecoms, retail, financial services, property, food, medical) > Food Processing (Oceana Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Broad cross-industry finance background documented in the Leadership magazine interview; Oceana owns Lucky Star and cold-chain operations, supporting the cold-storage tag.",
    ),
    # ---------------------------------------------------------------- Healthcare
    dict(
        name="Thato Moloele", first="Thato", surname="Moloele", des=["CA(SA)"],
        title="Executive Director and Group Chief Financial Officer", normalized_title="Group Chief Financial Officer",
        seniority_band="S7", employer="AfroCentric Group", employer_group="AfroCentric Group",
        role_family="Executive Finance", industry="Healthcare", sub_industry="Healthcare administration and medical schemes",
        grouped_industry="Healthcare & Life Sciences", province="Unknown", city=None,
        location_confidence="UNKNOWN", country="South Africa",
        evidence='AfroCentric Group leadership page: "Thato Moloele, Executive Director / Group Chief Financial Officer, appointed 01 February 2025. Qualifications: CA(SA)... Mr. Moloele, a qualified Chartered Accountant (South Africa), is an experienced finance professional and a seasoned corporate financier. He has held several senior positions during his career at Sanlam Limited, the Momentum Group and Deloitte."',
        academic=[],
        linkedin=None,
        source_urls=["https://www.afrocentric.za.com/about-us/our-leadership/"],
        primary_evidence_url="https://www.afrocentric.za.com/about-us/our-leadership/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Regulated", "Multi-entity", "B2B", "B2C"],
        finance_environment_tags=["Corporate Finance", "M&A", "Group Reporting", "Regulated Reporting"],
        work_history=[
            dict(employer="Deloitte", title="Senior position", industry="Professional Services", period=""),
            dict(employer="Momentum Group", title="Senior position", industry="Insurance", period=""),
            dict(employer="Sanlam Limited", title="Senior position (corporate finance)", industry="Insurance", period=""),
        ],
        career_industry_path="Professional Services (Deloitte) > Insurance (Momentum, Sanlam) > Healthcare (AfroCentric)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Location left Unknown: the source does not state the individual's city/province. Financial services to healthcare is a documented talent flow.",
    ),
    # ---------------------------------------------------------------- Retail
    dict(
        name="Praneel Nundkumar", first="Praneel", surname="Nundkumar", des=["CA(SA)"],
        title="Group Chief Financial Officer", normalized_title="Group Chief Financial Officer", seniority_band="S7",
        employer="Mr Price Group Limited", employer_group="Mr Price Group", role_family="Executive Finance",
        industry="Fashion Retail", sub_industry="Omnichannel apparel, homeware and sportswear retail",
        grouped_industry="Retail & Wholesale", province="KwaZulu-Natal", city="Durban",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='CFO South Africa profile and appointment announcement: "Praneel Nundkumar has been the CFO of Mr Price since 1 August 2023... He started his career as an auditor at PwC, where he qualified as a chartered accountant... Before Mr Price, Praneel served as the chief operations and financial officer at the Durban Chamber of Commerce and Industry and as a financial services manager of IT Dynamics." Appointment report: "Praneel holds a BCom and MBA from the University of KwaZulu-Natal and is a qualified CA(SA)."',
        academic=["BCom (UKZN)", "MBA (UKZN)"],
        articles_status="CONFIRMED_EXPLICIT", articles_body="SAICA", articles_employer="PwC",
        articles_period="2006-2009",
        linkedin=None,
        source_urls=[
            "https://cfo.co.za/profiles/praneel-nundkumar/",
            "https://cfo.co.za/articles/praneel-nundkumar-new-mr-price-cfo/",
        ],
        primary_evidence_url="https://cfo.co.za/profiles/praneel-nundkumar/",
        secondary_evidence_url="https://cfo.co.za/articles/praneel-nundkumar-new-mr-price-cfo/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=RETAIL_TAGS + ["Franchise", "B2C", "Multi-entity"],
        finance_environment_tags=["Retail Finance", "Listed Reporting", "Group Reporting", "Commercial Finance", "Revenue Management"],
        work_history=[
            dict(employer="PwC", title="Auditor", industry="Accounting / Audit", period="2006-2009"),
            dict(employer="IT Dynamics", title="Financial Services Manager", industry="Technology", period="2009-2012"),
            dict(employer="Durban Chamber of Commerce and Industry", title="Chief Operations and Financial Officer", industry="Industry Association", period="2012-2016"),
            dict(employer="Mr Price Group", title="Finance Executive", industry="Fashion Retail", period="2016-2019"),
            dict(employer="Mr Price Money", title="Financial Director", industry="Financial Services", period="2019-2020"),
            dict(employer="Mr Price Money", title="Managing Director", industry="Financial Services", period="2020-2023"),
        ],
        career_industry_path="Professional Services (PwC) > Technology (IT Dynamics) > Industry Association > Fashion Retail (Mr Price)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Full career path documented by CFO South Africa, including articles at PwC and the internal route through Mr Price Money.",
    ),
    dict(
        name="Gordon Traill", first="Gordon", surname="Traill", des=["CA(SA)"],
        title="Chief Financial Officer and Chief Support Services Officer", normalized_title="Chief Financial Officer",
        seniority_band="S7", employer="Clicks Group Limited", employer_group="Clicks Group",
        role_family="Executive Finance", industry="Pharmaceutical Retail", sub_industry="Health, beauty and pharmacy retail and wholesale",
        grouped_industry="Retail & Wholesale", province="Western Cape", city="Cape Town",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='Clicks Group audited annual financial statements FY2023: "These are the audited annual financial statements of the group and the company... prepared under the supervision of the chief financial officer, G Traill (CA)" and "Chief financial officer: Gordon Traill" (Clicks Group board page). GlobalData executive profile records his internal progression: joined the company in 2006 as Head of Internal Audit, promoted to Head of Group Finance, Head of finance for the retail business in 2014, Chief Support Services Officer, then CFO from 2023.',
        academic=[],
        linkedin=None,
        source_urls=[
            "https://www.clicksgroup.co.za/iar2023/wp-content/uploads/Clicks-2023-AFS_download.pdf",
            "https://www.globaldata.com/company-profile/clicks-group-limited/executives/",
        ],
        primary_evidence_url="https://www.clicksgroup.co.za/iar2023/wp-content/uploads/Clicks-2023-AFS_download.pdf",
        secondary_evidence_url="https://www.globaldata.com/company-profile/clicks-group-limited/executives/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=RETAIL_TAGS + ["Retail Network"],
        finance_environment_tags=["Listed Reporting", "Group Reporting", "Internal Audit", "Financial Control", "Shared Services"],
        work_history=[
            dict(employer="Clicks Group", title="Head of Internal Audit", industry="Pharmaceutical Retail", period="2006-"),
            dict(employer="Clicks Group", title="Head of Group Finance", industry="Pharmaceutical Retail", period=""),
            dict(employer="Clicks Group", title="Head of Finance: Retail", industry="Pharmaceutical Retail", period="2014-"),
            dict(employer="Clicks Group", title="Chief Support Services Officer", industry="Pharmaceutical Retail", period="before 2023"),
        ],
        career_industry_path="Pharmaceutical Retail (Clicks Group; internal progression)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Cape Town is the Clicks Group head-office location and the AFS signing location.",
    ),
    # ---------------------------------------------------------------- Telecoms / insurance
    dict(
        name="Tsholofelo Molefe", first="Tsholofelo", surname="Molefe", des=["CA(SA)"],
        title="Group Chief Financial Officer", normalized_title="Group Chief Financial Officer", seniority_band="S7",
        employer="MTN Group Limited", employer_group="MTN Group", role_family="Executive Finance",
        industry="Telecommunications", sub_industry="Mobile network operator",
        grouped_industry="Telecommunications", province="Gauteng", city="Johannesburg",
        location_confidence="CONFIRMED", country="South Africa",
        evidence='LinkedIn public profile headline (indexed): "Tsholofelo Molefe CA(SA) - Group CFO... As Group Chief Financial Officer of MTN Group, I lead financial strategy across 16 [markets]"; CFO South Africa: "MTN Group CFO Tsholofelo Molefe is passionate about connecting Africa."',
        academic=[],
        linkedin="https://za.linkedin.com/in/tsholofelo-molefe-ca-sa-765011100",
        source_urls=[
            "https://za.linkedin.com/in/tsholofelo-molefe-ca-sa-765011100",
            "https://cfo.co.za/",
        ],
        primary_evidence_url="https://za.linkedin.com/in/tsholofelo-molefe-ca-sa-765011100",
        secondary_evidence_url="https://cfo.co.za/",
        ownership="JSE Listed", scale="Multinational", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "Multinational", "Regulated", "Multi-site", "B2C", "Subscription"],
        finance_environment_tags=["Group Reporting", "Listed Reporting", "Capital Management", "Investor Relations"],
        work_history=[],
        career_industry_path="Telecommunications (MTN Group)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="LinkedIn headline carries the CA(SA) designation explicitly; profile is public and indexed. Reported work location City of Johannesburg.",
    ),
    dict(
        name="Abigail Mukhuba", first="Abigail", surname="Mukhuba", alternate_names=["Abigail Muelelwa Mukhuba"],
        des=["CA(SA)"], title="Group Finance Director and Executive Director",
        normalized_title="Group Finance Director", seniority_band="S7",
        employer="Sanlam Limited", employer_group="Sanlam", role_family="Executive Finance",
        industry="Insurance", sub_industry="Life and general insurance, investment management",
        grouped_industry="Insurance", province="Western Cape", city="Bellville",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Sanlam executive CV page: "Ms Mukhuba is Sanlam\\u2019s Group Finance Director... Ms Mukhuba is a Chartered Accountant (CA(SA)) and holds a B Compt from UNISA, BCom Hons Accounting from Rand Afrikaans University (RAU), MCom South African and International Taxation (RAU) and an MBA from the University of Cape Town." CFO South Africa: "She joined Sanlam from African Rainbow Minerals where she held the position of Finance Director since 2017... held several senior finance positions at KPMG, BMW SA and Exxaro Resources."',
        academic=["B Compt (UNISA)", "BCom Hons Accounting (RAU)", "MCom South African and International Taxation (RAU)", "MBA (UCT)"],
        linkedin="https://www.linkedin.com/in/abigail-muelelwa-mukhuba-ca-sa-2a683a242/",
        source_urls=[
            "https://www.sanlam.com/cv2-executive",
            "https://cfo.co.za/articles/sanlam-appoints-abigail-mukhuba-as-new-fd/",
        ],
        primary_evidence_url="https://www.sanlam.com/cv2-executive",
        secondary_evidence_url="https://cfo.co.za/articles/sanlam-appoints-abigail-mukhuba-as-new-fd/",
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=INSURANCE_TAGS + ["Multinational", "Regulated"],
        finance_environment_tags=["IFRS", "Listed Reporting", "Group Reporting", "Regulated Reporting", "Tax", "Risk"],
        work_history=[
            dict(employer="KPMG", title="Senior finance position", industry="Professional Services", period=""),
            dict(employer="BMW SA", title="Senior finance position", industry="Automotive Manufacturing", period=""),
            dict(employer="Exxaro Resources", title="Senior finance position", industry="Mining", period=""),
            dict(employer="African Rainbow Minerals", title="Finance Director", industry="Mining", period="2017-2020"),
        ],
        career_industry_path="Professional Services (KPMG) > Automotive Manufacturing (BMW SA) > Mining (Exxaro, ARM) > Insurance (Sanlam)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="An unusually broad cross-sector finance path (audit, automotive, mining, insurance). Bellville is Sanlam's head-office location.",
    ),
    # ---------------------------------------------------------------- Construction materials / cement
    dict(
        name="Nicolaas Crafford-Lazarus", first="Nicolaas", surname="Crafford-Lazarus",
        alternate_names=["NR Crafford-Lazarus"], des=["CA(SA)"],
        title="Financial Director", normalized_title="Financial Director", seniority_band="S6",
        employer="Sephaku Holdings Limited", employer_group="Sephaku Holdings", role_family="Executive Finance",
        industry="Construction Materials", sub_industry="Cement and ready-mix concrete",
        grouped_industry="Construction & Building Materials", province="Gauteng", city="Centurion",
        location_confidence="PROBABLE", country="South Africa",
        evidence='Sephaku Holdings audited AFS FY2025: "The financial statements were internally compiled under the supervision of: NR Crafford-Lazarus CA(SA)" and "The committee has satisfied itself that the financial director of SepHold, Mr. NR Crafford-Lazarus, has appropriate expertise and experience to meet his responsibilities."',
        academic=[],
        linkedin=None,
        source_urls=["https://senspdf.jse.co.za/documents/2025/jse/isse/sep/FY2025.pdf"],
        primary_evidence_url="https://senspdf.jse.co.za/documents/2025/jse/isse/sep/FY2025.pdf",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="false",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Asset Intensive", "Manufacturing", "High Working Capital", "B2B", "Multi-site"],
        finance_environment_tags=["Listed Reporting", "IFRS", "Group Reporting", "Statutory Reporting"],
        work_history=[],
        career_industry_path="Construction Materials (Sephaku Holdings)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="First name recorded as Nicolaas on the basis of the initials \"NR\" used in the AFS; city shown as the group's Centurion base (PROBABLE).",
    ),
    dict(
        name="Brenda Berlin", first="Brenda", surname="Berlin", des=["CA(SA)"],
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="PPC Ltd", employer_group="PPC", role_family="Executive Finance",
        industry="Cement", sub_industry="Cement, aggregates and materials",
        grouped_industry="Construction & Building Materials", province="Gauteng", city="Sandton",
        location_confidence="PROBABLE", country="South Africa",
        evidence='PPC Group leadership page: "Brenda Berlin - Chief Financial Officer (CFO)... Chartered Accountant of South Africa - CA(SA); Program for Management Development, Harvard Business School, 1995; Corporate Finance Elective of the MBA, Wits Business School, 1991; Bachelor of Commerce, University of Witwatersrand, 1986."',
        academic=["Program for Management Development (Harvard Business School)", "Corporate Finance Elective of the MBA (Wits Business School)", "BCom (University of the Witwatersrand)"],
        linkedin=None,
        source_urls=["https://www.ppc.africa/about-us/our-leadership/"],
        primary_evidence_url="https://www.ppc.africa/about-us/our-leadership/",
        ownership="JSE Listed", scale="JSE Listed", jse_listed="true", multinational="true",
        business_model_tags=["JSE Listed", "Listed Company", "South African Group", "Multinational", "Asset Intensive", "Manufacturing", "Multi-site", "B2B"],
        finance_environment_tags=["Corporate Finance", "Listed Reporting", "Group Reporting", "Capital Management"],
        work_history=[],
        career_industry_path="Cement (PPC)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="PPC operates across South Africa, Botswana, Zimbabwe, Zambia and the DRC. City shown as PPC's Johannesburg head office (PROBABLE).",
    ),
    # ---------------------------------------------------------------- Pipeline / Tier 2-3
    dict(
        name="Panashe Moyo", first="Panashe", surname="Moyo", des=["CA(SA)"],
        title="Senior Group Finance Manager", normalized_title="Senior Group Finance Manager", seniority_band="S4",
        employer="Nala Renewables", employer_group="Nala Renewables", role_family="Group Accounting",
        industry="Renewable Energy", sub_industry="Renewable power development",
        grouped_industry="Energy & Utilities", province="Unknown", city=None,
        location_confidence="UNKNOWN", country="South Africa",
        evidence='SAICA 2025 Top 35 Under 35 finalists: "Panashe Moyo CA(SA), 35 - Senior Group Finance Manager \\u2013 Nala Renewables | Transformation Leader | Co-Founder \\u2013 Culcha SA".',
        academic=[],
        linkedin=None,
        source_urls=["https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/"],
        primary_evidence_url="https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/",
        ownership="Private Company", scale="Mid-Market", jse_listed="false", multinational="true",
        business_model_tags=["Private Company", "Multinational", "Project Based", "Asset Intensive", "B2B", "Joint Venture", "High Growth"],
        finance_environment_tags=["Group Reporting", "Project Finance", "Consolidations"],
        work_history=[],
        career_industry_path="Renewable Energy (Nala Renewables)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation and role from SAICA's own 2025 Top 35 Under 35 finalist page. Location not stated by the source; Nala Renewables is an international renewable-energy joint venture, so no South African city is asserted.",
    ),
    dict(
        name="Tracy Lerato Nkosi", first="Tracy", surname="Nkosi", alternate_names=["Tracy Lerato Nkosi"], des=["CA(SA)"],
        title="Southern Africa Finance Controller", normalized_title="Financial Controller", seniority_band="S3",
        employer="Unilever South Africa", employer_group="Unilever", division="Southern Africa",
        role_family="Financial Control", industry="FMCG", sub_industry="Consumer goods manufacturing",
        grouped_industry="Consumer & FMCG", province="KwaZulu-Natal", city="Durban",
        location_confidence="PROBABLE", country="South Africa",
        evidence='SAICA 2025 Top 35 Under 35 finalists: "Tracy Lerato Nkosi CA(SA), 34 - Southern Africa Finance Controller \\u2013 Unilever South Africa | Mentor | Impact Champion".',
        academic=[],
        linkedin=None,
        source_urls=["https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/"],
        primary_evidence_url="https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/",
        ownership="Multinational Listed", scale="Multinational", jse_listed="false", multinational="true",
        business_model_tags=["Multinational", "Manufacturing", "Multi-site", "High Inventory", "B2C", "FMCG Route-to-Market", "Regulated"],
        finance_environment_tags=["Financial Control", "Management Reporting", "Manufacturing Finance"],
        work_history=[],
        career_industry_path="FMCG (Unilever South Africa)",
        employer_confidence="CONFIRMED", profile_confidence="CONFIRMED",
        notes="Designation and role from SAICA's own 2025 Top 35 Under 35 finalist page. Province PROBABLE on the basis of Unilever South Africa's Durban (La Lucia) head office; the individual's location is not stated by the source.",
    ),
    # ---------------------------------------------------------------- High-confidence designation
    dict(
        name="Taskeen Ismail", first="Taskeen", surname="Ismail", des=["CA(SA)"],
        status="HIGH_CONFIDENCE", qualification_confidence="HIGH",
        designation_status="HIGH_CONFIDENCE",
        title="Chief Financial Officer", normalized_title="Chief Financial Officer", seniority_band="S7",
        employer="Sanlam Investments", employer_group="Sanlam", role_family="Executive Finance",
        industry="Asset Management", sub_industry="Institutional investment management",
        grouped_industry="Investments & Capital Markets", province="Western Cape", city="Cape Town",
        location_confidence="PROBABLE", country="South Africa",
        evidence='CFO South Africa appointment report: "Taskeen Ismail, a seasoned chartered accountant with extensive experience in corporate finance and enterprise risk management, has been appointed CFO of Sanlam Investments... began with a Sanlam Group bursary to study business science at the University of Cape Town... joined Santam in 2008, working in enterprise risk management and corporate finance for five years. She then spent 11 years at Old Mutual, leading their corporate finance team."',
        academic=["Business Science (University of Cape Town)"],
        linkedin=None,
        source_urls=["https://cfo.co.za/articles/taskeen-ismail-appointed-chief-financial-officer-of-sanlam-investments/"],
        primary_evidence_url="https://cfo.co.za/articles/taskeen-ismail-appointed-chief-financial-officer-of-sanlam-investments/",
        ownership="JSE Listed", scale="Major Financial Institution", jse_listed="true", multinational="true",
        business_model_tags=INSURANCE_TAGS + ["Regulated"],
        finance_environment_tags=["Corporate Finance", "Risk", "Enterprise Risk Management", "Investor Relations"],
        work_history=[
            dict(employer="Santam", title="Enterprise risk management and corporate finance", industry="Insurance", period="2008-2013"),
            dict(employer="Old Mutual", title="Head of corporate finance", industry="Insurance", period="2013-2024"),
        ],
        career_industry_path="Insurance (Santam) > Insurance (Old Mutual) > Asset Management (Sanlam Investments)",
        employer_confidence="CONFIRMED", profile_confidence="HIGH",
        notes="Designation recorded HIGH_CONFIDENCE, not CONFIRMED: the source describes her as a \"seasoned chartered accountant\" without the explicit CA(SA) designation string. Retained because the role, employer and career history are fully evidenced and the South African chartered-accountant description is a strong indicator; flagged for designation confirmation.",
    ),
]

COMPANIES = []  # populated with sequential ids below


def company_specs(start_id):
    """New employer records discovered in this batch (ids assigned by caller)."""
    specs = [
        dict(company_name="Tiger Brands", company_aliases=["Tiger Brands Limited", "Tiger Brands Ltd"],
             website="https://www.tigerbrands.com", industry="FMCG",
             sub_industry="Food, home and personal care manufacturing", headquarters="Sandton, Gauteng, South Africa",
             south_africa_locations=["Sandton", "Cape Town", "Durban"], company_size_if_public="Approx. 20,000+ employees (JSE-listed group)",
             listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Executive committee captured (CEO, CFO, two divisional MDs with CA(SA)). Deeper finance-team sweep outstanding.",
             source_urls=["https://www.tigerbrands-ir-digital.com/reports/2024/Tiger-Brands-IAR-2024/our-executive-committee.php"]),
        dict(company_name="RCL Foods", company_aliases=["RCL Foods Limited", "RCL FOODS", "Rainbow Farms"],
             website="https://www.rclfoods.com", industry="Food Manufacturing",
             sub_industry="Groceries, baking and sugar", headquarters="Westville, KwaZulu-Natal, South Africa",
             south_africa_locations=["Westville", "Worcester", "Malelane"], company_size_if_public="JSE-listed group (post Rainbow unbundling)",
             listed_or_private="listed", parent_company="Remgro",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured with articles and career history. Deeper finance-team sweep outstanding.",
             source_urls=["https://rclfoods.com/wp-content/uploads/2025/09/2025-Annual-Financial-Statements.pdf"]),
        dict(company_name="Premier Group", company_aliases=["Premier Group Limited", "Premier Foods"],
             website="https://www.premiergroup.co.za", industry="Food Manufacturing",
             sub_industry="Millbake, groceries and international", headquarters="Waterfall, Gauteng, South Africa",
             south_africa_locations=["Waterfall", "Cape Town", "Durban"], company_size_if_public="JSE-listed group; approx. 15,950 employees",
             listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CEO and CFO captured. Divisional finance leadership not yet swept.",
             source_urls=["https://stockanalysis.com/quote/jse/PMR/company/"]),
        dict(company_name="Astral Foods", company_aliases=["Astral Foods Limited", "Astral Operations Ltd"],
             website="https://www.astralfoods.com", industry="Food Manufacturing",
             sub_industry="Integrated poultry and animal feed", headquarters="Centurion, Gauteng, South Africa",
             south_africa_locations=["Centurion", "Mpumalanga", "Western Cape"], company_size_if_public="JSE-listed group; approx. 9,400 employees",
             listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO succession captured (outgoing/incoming/acting) plus a divisional finance-to-operations executive.",
             source_urls=["https://www.astralfoods.com/executive-management.html"]),
        dict(company_name="Exxaro Resources", company_aliases=["Exxaro Resources Limited", "Exxaro"],
             website="https://www.exxaro.com", industry="Mining", sub_industry="Coal and minerals",
             headquarters="Centurion, Gauteng, South Africa", south_africa_locations=["Centurion", "Mpumalanga", "Limpopo"],
             company_size_if_public="JSE-listed group", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Finance Director captured with articles evidence. Group finance team sweep outstanding.",
             source_urls=["https://www.exxaro.com/our-business/leadership/"]),
        dict(company_name="Thungela Resources", company_aliases=["Thungela Resources Limited"],
             website="https://www.thungela.com", industry="Mining", sub_industry="Thermal coal",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Mpumalanga"],
             company_size_if_public="JSE-listed group", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured with full Anglo American career context.",
             source_urls=["https://www.thungela.com/about-us/who-we-are"]),
        dict(company_name="Kumba Iron Ore", company_aliases=["Kumba Iron Ore Limited", "Kumba"],
             website="https://www.angloamericankumba.com", industry="Mining", sub_industry="Iron ore",
             headquarters="Centurion, Gauteng, South Africa", south_africa_locations=["Centurion", "Kathu"],
             company_size_if_public="JSE-listed group (Anglo American group)", listed_or_private="listed",
             parent_company="Anglo American",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Incoming CFO captured from public appointment announcement.",
             source_urls=["https://www.miningreview.com/news/kumba-appoints-grindrod-ceo-xolani-mbambo-as-cfo-from-2026/"]),
        dict(company_name="Grindrod", company_aliases=["Grindrod Limited"],
             website="https://www.grindrod.com", industry="Logistics", sub_industry="Ports, terminals and freight logistics",
             headquarters="Durban, KwaZulu-Natal, South Africa", south_africa_locations=["Durban", "Richards Bay", "Cape Town"],
             company_size_if_public="JSE-listed group; approx. 3,900 employees", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO confirmed from FY2025 signed AFS (Durban). CEO transition 2025 also recorded.",
             source_urls=["https://www.grindrod.com/share_holder_documents/document_2586/Grindrod-Limited-2025-Signed-Final-AFS-31-December-2025.pdf"]),
        dict(company_name="Super Group", company_aliases=["Super Group Limited"],
             website="https://www.supergroup.co.za", industry="Logistics",
             sub_industry="Logistics and mobility solutions", headquarters="Sandton, Gauteng, South Africa",
             south_africa_locations=["Sandton", "Isando", "Cape Town"], company_size_if_public="JSE-listed group; approx. 18,800 employees",
             listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CEO and CFO both CA(SA) and captured with career history.",
             source_urls=["https://www.supergroup.co.za/our-leadership/"]),
        dict(company_name="DP World", company_aliases=["DP World sub-Saharan Africa", "Imperial Logistics"],
             website="https://www.dpworld.com", industry="Logistics",
             sub_industry="Ports, terminals and integrated logistics", headquarters="Dubai, United Arab Emirates",
             south_africa_locations=["Johannesburg", "Cape Town", "Durban"], company_size_if_public="Multinational; approx. 27,000 employees in sub-Saharan Africa",
             listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Regional CEO & MD (CA(SA), CFA) captured; the former Imperial business is now wholly owned.",
             source_urls=["https://www.imperiallogistics.com/leadership.php"]),
        dict(company_name="Crookes Brothers", company_aliases=["Crookes Brothers Limited"],
             website="https://www.cbl.co.za", industry="Agriculture",
             sub_industry="Sugar cane, bananas, macadamias and property",
             headquarters="KwaZulu-Natal, South Africa", south_africa_locations=["Scottburgh", "KwaZulu-Natal Midlands"],
             company_size_if_public="JSE-listed agricultural group", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="New CFO captured from FY2026 AFS and SENS coverage; prior CFO (deceased 2026) not captured.",
             source_urls=["https://senspdf.jse.co.za/documents/2026/jse/isse/cks/cbl2026.pdf"]),
        dict(company_name="AfroCentric Group", company_aliases=["AfroCentric Investment Corporation"],
             website="https://www.afrocentric.za.com", industry="Healthcare",
             sub_industry="Healthcare administration and medical schemes", headquarters="South Africa",
             south_africa_locations=[], company_size_if_public="JSE-listed group", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CFO captured (appointed February 2025); location not yet established.",
             source_urls=["https://www.afrocentric.za.com/about-us/our-leadership/"]),
        dict(company_name="Mr Price Group", company_aliases=["Mr Price Group Limited", "Mr Price"],
             website="https://www.mrpricegroup.com", industry="Fashion Retail",
             sub_industry="Omnichannel apparel, homeware and sportswear retail",
             headquarters="Durban, KwaZulu-Natal, South Africa", south_africa_locations=["Durban"],
             company_size_if_public="JSE-listed group; approx. 32,000 employees", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CFO captured with full PwC-to-retail career path.",
             source_urls=["https://cfo.co.za/profiles/praneel-nundkumar/"]),
        dict(company_name="MTN Group", company_aliases=["MTN Group Limited", "MTN"],
             website="https://www.mtn.com", industry="Telecommunications", sub_industry="Mobile network operator",
             headquarters="Johannesburg, Gauteng, South Africa", south_africa_locations=["Johannesburg", "Roodepoort"],
             company_size_if_public="JSE-listed multinational", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group CFO captured from public LinkedIn headline and CFO South Africa coverage.",
             source_urls=["https://za.linkedin.com/in/tsholofelo-molefe-ca-sa-765011100"]),
        dict(company_name="Sanlam", company_aliases=["Sanlam Limited"],
             website="https://www.sanlam.com", industry="Insurance",
             sub_industry="Life and general insurance, investment management",
             headquarters="Bellville, Western Cape, South Africa", south_africa_locations=["Bellville", "Cape Town", "Sandton"],
             company_size_if_public="JSE-listed major financial institution", listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Group Finance Director captured; Sanlam Investments CFO captured at HIGH_CONFIDENCE designation tier.",
             source_urls=["https://www.sanlam.com/cv2-executive"]),
        dict(company_name="Sanlam Investments", company_aliases=["Sanlam Investment Management"],
             website="https://www.sanlam.com", industry="Asset Management",
             sub_industry="Institutional investment management", headquarters="Cape Town, Western Cape, South Africa",
             south_africa_locations=["Cape Town", "Sandton"], company_size_if_public="Subsidiary of Sanlam Limited",
             listed_or_private="listed", parent_company="Sanlam",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="CFO captured; designation tier flagged HIGH_CONFIDENCE pending explicit CA(SA) wording.",
             source_urls=["https://cfo.co.za/articles/taskeen-ismail-appointed-chief-financial-officer-of-sanlam-investments/"]),
        dict(company_name="Sephaku Holdings", company_aliases=["Sephaku Holdings Limited", "SepHold", "Sephaku Cement"],
             website="https://www.sephaku.co.za", industry="Construction Materials",
             sub_industry="Cement and ready-mix concrete", headquarters="Centurion, Gauteng, South Africa",
             south_africa_locations=["Centurion", "Lichtenburg"], company_size_if_public="JSE-listed; 36% interest in SepCem",
             listed_or_private="listed", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Financial Director captured from FY2025 AFS preparer statement.",
             source_urls=["https://senspdf.jse.co.za/documents/2025/jse/isse/sep/FY2025.pdf"]),
        dict(company_name="Nala Renewables", company_aliases=["Nala Renewables SA"],
             website="https://nalarenewables.com", industry="Renewable Energy",
             sub_industry="Renewable power development", headquarters="United Kingdom / South Africa operations",
             south_africa_locations=[], company_size_if_public="Private joint venture (Vitol / IFM Investors)",
             listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Senior Group Finance Manager captured from SAICA Top 35 Under 35 2025.",
             source_urls=["https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/"]),
        dict(company_name="Unilever South Africa", company_aliases=["Unilever SA"],
             website="https://www.unilever.co.za", industry="FMCG",
             sub_industry="Consumer goods manufacturing", headquarters="Durban (La Lucia), KwaZulu-Natal, South Africa",
             south_africa_locations=["Durban", "Johannesburg"], company_size_if_public="Subsidiary of Unilever plc",
             listed_or_private="listed", parent_company="Unilever",
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Southern Africa Finance Controller captured from SAICA Top 35 Under 35 2025; broader finance team not yet swept.",
             source_urls=["https://www.saica.org.za/initiatives/awards-and-competitions/top-35-under-35-awards/2025-top-35-under-35-finalists/"]),
        dict(company_name="AFGRI", company_aliases=["AFGRI Group Holdings", "AFGRI Operations Limited"],
             website="https://www.afgri.co.za", industry="Agriculture",
             sub_industry="Grain management, agri services and food processing", headquarters="Centurion, Gauteng, South Africa",
             south_africa_locations=["Centurion", "Free State", "Mpumalanga"], company_size_if_public="Approx. 4,500 employees",
             listed_or_private="private", parent_company=None,
             finance_team_research_status="RESEARCHED_WITH_PEOPLE",
             finance_team_research_notes="Recorded as the previous employer of the incoming Astral Foods CFO; AFGRI's own finance team not yet swept.",
             source_urls=["https://simplywall.st/community/narratives/za/food-beverage-tobacco/jse-arl/astral-foods-shares/0brw8lqv-better-south-african-crops-will-fuel-poultry-resurgence/updates/5-analysts-have-kept-their-zar26500-price-target-on-astral-fo"]),
    ]
    for offset, spec in enumerate(specs):
        spec["id"] = "cmp-%04d" % (start_id + offset)
        spec.setdefault("date_verified", TODAY)
        spec.setdefault("finance_people_verified_count", 1)
        spec.setdefault("website", None)
        spec.setdefault("company_aliases", [])
        spec.setdefault("headquarters", None)
        spec.setdefault("south_africa_locations", [])
        spec.setdefault("company_size_if_public", None)
        spec.setdefault("listed_or_private", "unknown")
        spec.setdefault("parent_company", None)
        spec.setdefault("source_urls", [])
        spec.setdefault("finance_team_research_status", "NEEDS_RESEARCH")
        spec.setdefault("finance_team_research_notes", "")
        spec.setdefault("industry", None)
        spec.setdefault("sub_industry", None)
        COMPANIES.append(spec)
    return specs


def source_type_for(url):
    """Map an evidence URL to the sources.jsonl controlled source_type vocabulary."""
    lowered = url.lower()
    if "linkedin.com" in lowered:
        return "LinkedIn"
    if ".pdf" in lowered or "jse.co.za" in lowered:
        return "Annual Report"
    if "saica.org.za" in lowered:
        return "Professional Body"
    if "cfo.co.za" in lowered or "moneyweb" in lowered or "miningreview" in lowered or "marketscreener" in lowered or "seafoodsource" in lowered:
        return "News"
    if "simplywall.st" in lowered or "stockanalysis" in lowered or "globaldata" in lowered:
        return "Directory"
    return "Employer Website"


def main():
    existing_people = [json.loads(line) for line in open(db_lib.PEOPLE_PATH, encoding="utf-8") if line.strip()]
    known_names = {row["full_name"].strip().lower() for row in existing_people}
    new_specs = [spec for spec in PEOPLE if spec["name"].strip().lower() not in known_names]

    companies = company_specs(db_lib.next_id(db_lib.COMPANIES_PATH, "cmp"))
    people = db_lib.append_batch(new_specs, companies, None, label="batch 13 (CA(SA) master-mapping layer)")

    # Evidence-source records for every batch-13 person now in the DB, linked to their id.
    existing_sources = db_lib.load_existing_ids(db_lib.SOURCES_PATH)
    next_source = db_lib.next_id(db_lib.SOURCES_PATH, "src")
    current = [json.loads(line) for line in open(db_lib.PEOPLE_PATH, encoding="utf-8") if line.strip()]
    by_name = {row["full_name"].strip().lower(): row for row in current}
    rows = []
    for spec in PEOPLE:
        person = by_name.get(spec["name"].strip().lower())
        if person is None:
            continue
        urls = spec.get("source_urls") or []
        for index, url in enumerate(urls):
            rows.append({
                "id": "src-%04d" % next_source,
                "url": url,
                "source_type": source_type_for(url),
                "person_id": person["id"],
                "company_id": None,
                "evidence_type": "qualification_and_current_employment_evidence" if index == 0 else "secondary_employment_or_career_evidence",
                "evidence_summary": person.get("qualification_evidence") or "",
                "qualification_supported": "true" if "CA(SA)" in (person.get("professional_designations") or []) else "null",
                "skill_supported": None,
                "system_supported": None,
                "employment_supported": "true",
                "accessed_date": TODAY,
                "reliability": "PRIMARY" if index == 0 else "STRONG",
                "status": "USED",
            })
            next_source += 1
    if rows and rows[0]["id"] in existing_sources:
        print("source records already present; skipping")
    else:
        added = db_lib.append_records(db_lib.SOURCES_PATH, rows, existing_sources)
        print(f"sources added: {added}")


if __name__ == "__main__":
    main()
