# -*- coding: utf-8 -*-
"""SA Hackathon Census — participation records (Phase 1), captured 2026-08-26.
Tuple: (event_id, full_published, first, middle, surname, placement, team, project, extra)
extra: pipe-separated k=v pairs — uni, org, award, src (extra source ids), cid, cpl, note, alias
Placement codes: 1..10, Top3, Top10, Finalist, Participant, Winner(special), Qualified
"""

P = [
# ---- E009 Hack.Jozi 2015 ----
("E009","Desmond Mongwe","Desmond","","Mongwe","1","MoWallet","PopApp Deals / moWallet","org=moWallet (founder/CTO)|award=R1,000,000 first prize|src=S02,S03,S06|note=Winner of inaugural #Hack.Jozi Challenge"),
("E009","Niel Pieters","Niel","","Pieters","2nd/3rd (conflicting)","Lazy Lizzard","Teachinator educational software","org=Lazy Lizzard (founder/CEO)|award=R350,000|src=S02,S03,S06|cpl=Medium|note=joburg.org.za places Lazy Lizzard 3rd; Tshimologong blog says 1st runner-up — unresolved (see contradiction log)"),
("E009","Percy Lawrence","Percy","","Lawrence","2nd/3rd (conflicting)","MoveThisStuff","MoveThisStuff logistics app","award=R350,000|src=S02,S03|cpl=Medium|note=Conflicting runner-up order (see contradiction log)"),
# ---- E010 Hack.Jozi 2016 ----
("E010","Neo Hutiri","Neo","","Hutiri","1","Technovera","Technovera chronic-medication smart lockers","org=Technovera (founder)|award=R1,000,000 first prize|src=S04,S05"),
("E010","Abed Tau","Abed","","Tau","2","Tuta-Me","Tuta-Me tutor-student marketplace","org=Tuta-Me (co-founder)|award=R350,000|src=S05"),
("E010","Dylan Hyslop","Dylan","","Hyslop","2","Tuta-Me","Tuta-Me tutor-student marketplace","org=Tuta-Me (co-founder)|award=R350,000|src=S05"),
("E010","Lomile Mokoka","Lomile","","Mokoka","3","eSubmit","eSubmit building-plan submission solution","org=eSubmit; qualified architect (per ITWeb)|award=R350,000|src=S05"),
# ---- E015 GirlCodeHack 2017 ----
("E015","Kungela Mzuku","Kungela","","Mzuku","1","The Rubies","Amava (NPO-skills linking platform)","uni=University of Cape Town|src=S07,S08"),
("E015","Fadzai Mupfunya","Fadzai","","Mupfunya","1","The Rubies","Amava (NPO-skills linking platform)","uni=University of Cape Town|src=S07,S08|alias=Call_Me_Fadzi (public X handle cited in coverage)"),
("E015","Lorna Nqodi","Lorna","","Nqodi","1","The Rubies","Amava (NPO-skills linking platform)","uni=University of Cape Town|src=S07,S08"),
("E015","Valerie Tshiani","Valerie","","Tshiani","1","The Rubies","Amava (NPO-skills linking platform)","uni=University of Cape Town|src=S07,S08"),
# ---- E018 Entelect Challenge 2017 ----
("E018","Ryan Louw","Ryan","","Louw","1","","Colonel Panic (Battleships bot)","org=Software developer (profession per organiser)|award=R70,000|src=S12"),
("E018","Dion van Huyssteen","Dion","","van Huyssteen","2","","","award=R35,000|src=S12"),
("E018","Anesu Jairosi","Anesu","","Jairosi","3","","","award=R25,000|src=S12|note=Same distinctive name places 3rd (2017), 3rd (2023), 8th (2024) in same competition series — treated as one individual (medium-high confidence); 2024 source spells 'Aneso' (see alias record)"),
("E018","Jaco Mostert","Jaco","","Mostert","4","","","award=R25,000|src=S12"),
("E018","Willie Theron","Willie","","Theron","5","","","award=R10,000|src=S12|note=Same distinctive name: 5th (2017), 2nd (2022), 1st (2024) in same series — treated as one individual"),
("E018","Wynand Wolmarans","Wynand","","Wolmarans","6","","","award=R10,000|src=S12"),
# ---- E019 Entelect Challenge 2019 ----
("E019","japeyjapes (pseudonym)","Unknown","","Unknown","3","","MrLavaLava (worms bot)","cid=Low|note=Participant blog under pseudonym; real name not publicly linked on the page — recorded as unresolved identity per pseudonym rule",),
# ---- E020 Entelect Challenge 2022 ----
("E020","Kobus van Schoor","Kobus","","van Schoor","1","","","src=S13|note=Treated as same individual across 2022/2023/2024 editions (identical name, same series, consistent placements)"),
("E020","Willie Theron","Willie","","Theron","2","","","src=S13"),
("E020","Tian Cilliers","Tian","","Cilliers","3","","","src=S13"),
# ---- E021 Entelect Challenge 2023 ----
("E021","Purpose Katakwa","Purpose","","Katakwa","1","","mari.ai (Dotnet bot)","award=R70,000|src=S14|note=Nationality not stated in source — not inferred"),
("E021","Kobus van Schoor","Kobus","","van Schoor","2","","","src=S14"),
("E021","Anesu Jairosi","Anesu","","Jairosi","3","","","src=S14"),
# ---- E022 Entelect Challenge 2024 ----
("E022","Willie Theron","Willie","","Theron","1","","","award=R70,000|src=S15"),
("E022","Riaan Nel","Riaan","","Nel","2","","","award=R35,000|src=S15"),
("E022","Marvin Thobejane","Marvin","","Thobejane","3","","","award=R25,000|src=S15"),
("E022","Jesse Bristow","Jesse","","Bristow","4","","","award=prize share (R200k pool)|src=S15"),
("E022","Kobus van Schoor","Kobus","","van Schoor","5","","","src=S15"),
("E022","Scott Schultz","Scott","","Schultz","6","","","src=S15"),
("E022","Jean-Paul De Conceicao","Jean-Paul","","De Conceicao","7","","","src=S15"),
("E022","Aneso Jairosi","Aneso","","Jairosi","8","","","cid=Medium|cpl=High|src=S15|alias=Anesu Jairosi|note=Probable same individual as 'Anesu Jairosi' (2017/2023) — spelling variant kept as separate canonical record pending corroboration per name-variation rule"),
# ---- E012 Hack4Water hackathon weekend 2016 (names from organiser page snapshot) ----
("E012","Yolanda (single name published)","Yolanda","","Unknown","Participant","(Cape Town 'cost of water' team)","What is the cost of water?","cid=Low|src=S17|note=Single-name participant listing on organiser page; surname not published"),
("E012","Chelsea Lewis","Chelsea","","Lewis","Participant","(Cape Town 'cost of water' team)","What is the cost of water?","src=S17"),
("E012","Adi Eyal","Adi","","Eyal","Participant","(Cape Town 'cost of water' team)","What is the cost of water?","src=S17"),
("E012","Raymond Joseph","Raymond","","Joseph","Participant","(Cape Town 'cost of water' team)","What is the cost of water?","src=S17"),
("E012","Heiko Heilgendorff","Heiko","","Heilgendorff","Participant","(Durban water-sources team)","Where does your water come from?","src=S17"),
("E012","Bruce Page","Bruce","","Page","Participant","(Durban water-sources team)","Where does your water come from?","src=S17"),
("E012","Thuthukani Nxumalo","Thuthukani","","Nxumalo","Participant","(Durban water-sources team)","Where does your water come from?","src=S17"),
("E012","Johanna Singh","Johanna","","Singh","Participant","(Durban water-sources team)","Where does your water come from?","src=S17"),
("E012","James Smith","James","","Smith","Participant","(Durban water-sources team)","Where does your water come from?","src=S17|note=Listed in both Durban teams on organiser page — two participation rows, one canonical person (same event page)"),
("E012","Justus Caspers","Justus","","Caspers","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","Sandile Nkomonde","Sandile","","Nkomonde","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","Max Grau","Max","","Grau","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","Wiseman Mkhwanazi","Wiseman","","Mkhwanazi","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","Avanti Maharaj","Avanti","","Maharaj","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","James Smith","James","","Smith","Participant","Team Fix It","Community app to notify municipality of water leakages","src=S17"),
("E012","Suvritha Ramphal","Suvritha","","Ramphal","Participant","","","src=S17"),
("E012","James Lees","James","","Lees","Participant","","","src=S17"),
("E012","Mikhail Peppas","Mikhail","","Peppas","Participant","","","src=S17"),
("E012","Sanabelle Ebrahim","Sanabelle","","Ebrahim","Participant","","","src=S17"),
("E012","Roxanne Mingard","Roxanne","","Mingard","Participant","","","src=S17"),
("E012","Peterson Ndlovu","Peterson","","Ndlovu","Participant","","","src=S17"),
("E012","Aditi Lachman","Aditi","","Lachman","Participant","","","src=S17"),
("E012","Katherine Townsend","Katherine","","Townsend","Participant","","","src=S17"),
("E012","Tumelo Motaung","Tumelo","","Motaung","Participant","","","src=S17"),
("E012","Claudio Duarte","Claudio","","Duarte","Participant","","","src=S17"),
("E012","Nora Hanke","Nora","","Hanke","Participant","","","src=S17"),
("E012","Tshepo Mamabolo Mahudu","Tshepo","","Mamabolo Mahudu","Participant","","","src=S17"),
("E012","Sipho Mbulawa","Sipho","","Mbulawa","Participant","","","src=S17"),
("E012","Simon Chambert","Simon","","Chambert","Participant","","","src=S17"),
("E012","Tanisha Lalla","Tanisha","","Lalla","Participant","","","src=S17"),
("E012","Tiyani Nghonyama","Tiyani","","Nghonyama","Participant","","","src=S17|note=Geekulcha COO/CTO listed as participant on organiser page (pre-dates his later organiser roles in other events)"),
("E012","Pertunia Molope","Pertunia","","Molope","Participant","","","src=S17"),
("E012","Tsiepe Zemene","Tsiepe","","Zemene","Participant","","","src=S17"),
("E012","Thembisile Sizwe Mngadi","Thembisile","Sizwe","Mngadi","Participant","","","src=S17"),
("E012","John Harris","John","","Harris","Participant","","","src=S17"),
("E012","Jeanette Normand","Jeanette","","Normand","Participant","","","src=S17"),
("E012","Siyabonga Africa","Siyabonga","","Africa","Participant","","","src=S17"),
("E012","Lucas Kekana","Lucas","","Kekana","Participant","","","src=S17"),
("E012","Isaac Hlengani","Isaac","","Hlengani","Participant","","","src=S17"),
("E012","Solly Cossa","Solly","","Cossa","Participant","","","src=S17"),
("E012","Jonathan Mayunga Wishes","Jonathan","Mayunga","Wishes","Participant","","","src=S17"),
("E012","Godfrey Madzivire","Godfrey","","Madzivire","Participant","","","src=S17"),
# ---- E008 RHoK Pretoria 2014 ----
("E008","Kutlwano Kemisho","Kutlwano","","Kemisho","Winner(special)","","","award=Best female hacker|src=S19"),
("E008","Josiah Masango","Josiah","","Masango","Winner(special)","","","award=Best hacking spirit|src=S19"),
("E008","Lehlogonolo Sathekge","Lehlogonolo","","Sathekge","Winner(special)","","","award=Best social media person (Nokia Lumia 625)|src=S19"),
("E008","Desiree Mampane","Desiree","","Mampane","Winner(special)","","","award=Best tweet (Nokia Lumia 520)|src=S19"),
("E008","Diamond Mubaraack","Diamond","","Mubaraack","Winner(special)","","","award=Nokia X (used in implementing solution)|src=S19"),
("E008","Joao Nzango","Joao","","Nzango","Winner(special)","","","award=GeekStar / Hackathon RHoKStar (Twitter vote, 39%)|src=S19"),
# ---- E004 Hacking Health Cape Town 2014 ----
("E004","Farah Jawitz","Farah","","Jawitz","1","ECTracker","ECTracker ER patient-flow app","uni=UCT (medical student, per coverage)|note='Team led by' — other member names not published|src=S23"),
# ---- E005 #GovHackSA 2014 ----
("E005","Alek Gallo","Alek","","Gallo","1","Pulse","Mobile micro-polling platform","src=S24"),
("E005","Bruce Bassett","Bruce","","Bassett","1","Pulse","Mobile micro-polling platform","src=S24"),
("E005","Riccardo Iovino","Riccardo","","Iovino","1","Pulse","Mobile micro-polling platform","src=S24"),
("E005","Michael Graaf","Michael","","Graaf","1","Pulse","Mobile micro-polling platform","src=S24"),
("E005","Coenraad Loubser","Coenraad","","Loubser","1","Pulse","Mobile micro-polling platform","src=S24"),
# ---- E006 Discovery GradHack 2014 ----
("E006","Michael Wright","Michael","","Wright","1","Health Ninjas","Vitality-focused Android health app (Arduino heart-rate sensor)","uni=University of Johannesburg (ACSSE)|src=S25"),
("E006","Egbert van der Westhuizen","Egbert","","van der Westhuizen","1","Health Ninjas","Vitality-focused Android health app","uni=University of Johannesburg (ACSSE)|src=S25"),
("E006","Lourens Badenhorst","Lourens","","Badenhorst","1","Health Ninjas","Vitality-focused Android health app","uni=University of Johannesburg (ACSSE)|src=S25"),
("E006","Martin Trollip","Martin","","Trollip","1","Health Ninjas","Vitality-focused Android health app","uni=University of Johannesburg (ACSSE)|src=S25"),
# ---- E023 Discovery GradHack 2016 ----
("E023","Kyle Alexander","Kyle","","Alexander","1","Team Bithealth","Health & fitness tracking system","uni=University of Johannesburg (ACSSE)|src=S27"),
("E023","Jihyun Byun","Jihyun","","Byun","1","Team Bithealth","Health & fitness tracking system","uni=University of Johannesburg (ACSSE)|src=S27"),
("E023","Jacques Oosthuizen","Jacques","","Oosthuizen","1","Team Bithealth","Health & fitness tracking system","uni=University of Johannesburg (ACSSE)|src=S27"),
("E023","Mario da Silva","Mario","","da Silva","1","Team Bithealth","Health & fitness tracking system","uni=University of Johannesburg (ACSSE)|src=S27"),
("E023","Shaun Van Wyk","Shaun","","Van Wyk","1","Team Bithealth","Health & fitness tracking system","uni=University of Johannesburg (ACSSE)|src=S27"),
# ---- E025 Discovery GradHack 2018 ----
("E025","Natasha Oates","Natasha","","Oates","1","","PayDay (informal-worker employment matching)","uni=University of Cape Town (IS honours; business science)|src=S28"),
("E025","Nasiha Ally","Nasiha","","Ally","1","","PayDay","uni=University of Cape Town (IS honours)|src=S28"),
("E025","Ryan Tripod","Ryan","","Tripod","1","","PayDay","uni=University of Cape Town (IS honours)|src=S28"),
("E025","Zack Zornitta","Zack","","Zornitta","1","","PayDay","uni=University of Cape Town (IS honours)|src=S28"),
# ---- E026 Discovery GradHack 2021 ----
("E026","Rudi Dreyer","Rudi","","Dreyer","1","Team NeuroTech","(winning solution)","uni=North-West University|award=R10,000 prize value|src=S29"),
("E026","Chris Neuhoff","Chris","","Neuhoff","1","Team NeuroTech","","uni=North-West University|award=R10,000 prize value|src=S29"),
("E026","Franco Bester","Franco","","Bester","1","Team NeuroTech","","uni=North-West University|award=R10,000 prize value|src=S29"),
("E026","Ivan Pretorius","Ivan","","Pretorius","1","Team NeuroTech","","uni=North-West University|award=R10,000 prize value|src=S29"),
# ---- E027 Discovery GradHack 2024 ----
("E027","Jordy Kafwe","Jordy","","Kafwe","1","Team Cookout","SafeRoute (crime-data navigation app)","uni=University of Cape Town (CS Hons)|src=S30"),
("E027","Ben Cleveland","Ben","","Cleveland","1","Team Cookout","SafeRoute","uni=University of Cape Town (CS Hons)|src=S30"),
("E027","Yohannes Gebremeskel Libelo","Yohannes","Gebremeskel","Libelo","1","Team Cookout","SafeRoute","uni=University of Cape Town (IS Hons)|src=S30"),
("E027","Maesela Katlego Sekoele","Maesela","Katlego","Sekoele","1","Team Cookout","SafeRoute","uni=University of Cape Town (IS Hons)|src=S30"),
("E027","Michael Gamsu","Michael","","Gamsu","Top3","Team Silicon Slippers","AI-powered personalised financial navigator","uni=University of Cape Town (CS Hons)|src=S30"),
("E027","Boitumelo Mokoka","Boitumelo","","Mokoka","Top3","Team Silicon Slippers","AI-powered personalised financial navigator","uni=University of Cape Town (CS Hons)|src=S30"),
("E027","Ryan Murphy","Ryan","","Murphy","Top3","Team Silicon Slippers","AI-powered personalised financial navigator","uni=University of Cape Town (CS Hons)|src=S30"),
("E027","Tasmiyah Nakooda","Tasmiyah","","Nakooda","Top3","","AI-powered lung-disease detection + EHR","uni=North-West University (IT)|src=S31|note=Top-3 finalist; exact rank not stated; offered permanent Discovery employment"),
("E027","Ulysses Makubika","Ulysses","","Makubika","Top3","","AI-powered lung-disease detection + EHR","uni=North-West University (IT)|src=S31"),
("E027","Zaid Asvat","Zaid","","Asvat","Top3","","AI-powered lung-disease detection + EHR","uni=North-West University (IT)|src=S31"),
# ---- E028 Discovery GradHack 2025 ----
("E028","Mia Olivier","Mia","","Olivier","1","VitaliTeam","","uni=Stellenbosch University (BDatSci)|award=R15,000 each + R50,000 to SU|src=S32"),
("E028","Kayleigh Koekemoer","Kayleigh","","Koekemoer","1","VitaliTeam","","uni=Stellenbosch University (BDatSci)|award=R15,000 each + R50,000 to SU|src=S32"),
("E028","Jaime Kruger","Jaime","","Kruger","1","VitaliTeam","","uni=Stellenbosch University (BDatSci)|award=R15,000 each + R50,000 to SU|src=S32"),
("E028","David Nicolay","David","","Nicolay","1","VitaliTeam","","uni=Stellenbosch University (BDatSci)|award=R15,000 each + R50,000 to SU|src=S32"),
# ---- E030 SU Hackathon 2021 ----
("E030","Simeon Boshoff","Simeon","","Boshoff","1","LaTeX on the Beach","Inventory-taking prototype (phone + marker)","uni=Stellenbosch University|award=R8,000 (FinTech challenge)|src=S33"),
("E030","Nadia van Niekerk","Nadia","","van Niekerk","1","LaTeX on the Beach","Inventory-taking prototype","uni=Stellenbosch University|award=R8,000 (FinTech challenge)|src=S33"),
("E030","Lauren Abrahall","Lauren","","Abrahall","1","LaTeX on the Beach","Inventory-taking prototype","uni=Stellenbosch University|award=R8,000 (FinTech challenge)|src=S33"),
("E030","Daniel Olivier","Daniel","","Olivier","1","LaTeX on the Beach","Inventory-taking prototype","uni=Stellenbosch University|award=R8,000 (FinTech challenge)|src=S33"),
("E030","Simon Steven","Simon","","Steven","1","LaTeX on the Beach","Inventory-taking prototype","uni=Stellenbosch University|award=R8,000 (FinTech challenge)|src=S33"),
("E030","Lance Davids","Lance","","Davids","1","Designated Derivers","(data challenge winner)","uni=Stellenbosch University|award=R8,000 (data challenge)|src=S33"),
("E030","Musa Maboea","Musa","","Maboea","1","Designated Derivers","(data challenge winner)","uni=Stellenbosch University|award=R8,000 (data challenge)|src=S33"),
("E030","Thamu Mnyulwa","Thamu","","Mnyulwa","1","Designated Derivers","(data challenge winner)","uni=Stellenbosch University|award=R8,000 (data challenge)|src=S33"),
# ---- E031 SU LaunchLab Hackathon 2024 ----
("E031","Emma Sharratt","Emma","","Sharratt","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (electrical engineering masters)|award=R7,500|src=S34"),
("E031","Divan van der Bank","Divan","","van der Bank","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (engineering)|award=R7,500|src=S34"),
("E031","Retief Louw","Retief","","Louw","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (engineering)|award=R7,500|src=S34"),
("E031","Dgibrilly Mutabazi","Dgibrilly","","Mutabazi","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (engineering)|award=R7,500|src=S34"),
("E031","Kharendwe Makhani","Kharendwe","","Makhani","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (engineering)|award=R7,500|src=S34"),
("E031","Kabelo Maphutha","Kabelo","","Maphutha","1","Team Apollo","Cloud-platform cost-management solution","uni=Stellenbosch University (engineering)|award=R7,500|src=S34"),
# ---- E032 MiWay Actuarial Hackathon 2019 ----
("E032","Matt Lourens","Matt","","Lourens","1","","Predictive customer-retention model","uni=North-West University (Masters Business Analytics)|award=R20,000|src=S35,S36"),
("E032","Dehan Opperman","Dehan","","Opperman","1","","Predictive customer-retention model","uni=North-West University (Masters Data Mining)|award=R20,000|src=S35,S36"),
("E032","Christian Hitchcock","Christian","","Hitchcock","2","","","uni=University of Pretoria (Actuarial Science Hons)|award=R5,000|src=S35"),
("E032","Lebogang Moremi","Lebogang","","Moremi","3","","","uni=University of Pretoria (Actuarial Science Hons)|award=R3,000|src=S35"),
# ---- E036 Standard Bank UniHack 2024 ----
("E036","Andile Masela","Andile","","Masela","1","Edu Elevators","AI-powered SA-SAMS-integrated tutoring chatbot","src=S38"),
("E036","Michael Maseko","Michael","","Maseko","1","Edu Elevators","AI-powered tutoring chatbot","src=S38"),
("E036","Olerato Motaung","Olerato","","Motaung","1","Edu Elevators","AI-powered tutoring chatbot","src=S38"),
("E036","Nkuleko Nhlapo","Nkuleko","","Nhlapo","1","Edu Elevators","AI-powered tutoring chatbot","src=S38"),
# ---- E037 Standard Bank UniHack 2025 ----
("E037","Justin Dietrich","Justin","","Dietrich","1","High Five","Handy (real-time sign-language-to-text app)","uni=Stellenbosch University|src=S39,S40"),
("E037","Vutivi Makubela","Vutivi","","Makubela","1","High Five","Handy","uni=Stellenbosch University|src=S39,S40"),
("E037","Bailey McJarrow","Bailey","","McJarrow","1","High Five","Handy","uni=Stellenbosch University|src=S39,S40|alias=Bailey Mc Jarrow (source spelling variant)"),
("E037","Oluphi Vukaphi","Oluphi","","Vukaphi","1","High Five","Handy","uni=University of the Western Cape|src=S39,S40"),
("E037","Nabeelah Khan","Nabeelah","","Khan","1","High Five","Handy","uni=University of the Western Cape|src=S39,S40"),
# ---- E044 #SS19Hack 2019 ----
("E044","Tumelo Baloyi","Tumelo","","Baloyi","1","","Crowd-sourcing volunteer platform for disaster relief","award=#SS19Hack Champion's Trophy (innovation score)|src=S45"),
("E044","Siyammukela Kasapo","Siyammukela","","Kasapo","1","Khululeka (probable member)","Khululeka blockchain-based content filtering tool","cid=Medium|src=S45|note=Named in winning-team photo caption; photo may include sponsor/judge representatives — individual membership not fully confirmed"),
("E044","James Miwahili","James","","Miwahili","1","Khululeka (probable member)","Khululeka blockchain-based content filtering tool","cid=Medium|src=S45|note=As above — photo-caption ambiguity"),
# ---- E045 Absa Design Hackathon 2021 ----
("E045","Tsholofelo Radebe","Tsholofelo","","Radebe","1","ELEV8A","","award=R50,000|src=S47"),
("E045","Keletso Moagi","Keletso","","Moagi","1","ELEV8A","","award=R50,000|src=S47"),
("E045","Sihle Dube","Sihle","","Dube","1","ELEV8A","","award=R50,000|src=S47"),
("E045","Mila Daly","Mila","","Daly","2","Omnicorn","","award=R15,000|src=S47"),
("E045","Tawanda Mutambwe","Tawanda","","Mutambwe","2","Omnicorn","","award=R15,000|src=S47"),
("E045","Refilwe Lesego Masekela","Refilwe","Lesego","Masekela","2","Omnicorn","","award=R15,000|src=S47"),
# ---- E050 Wits Minecraft challenge 2018 ----
("E050","Yadir Purmasir","Yadir","","Purmasir","1","","The Order of the Stone Academy (Minecraft school world)","uni=Wits University (education student)|award=First prize, Individual Challenge|src=S52"),
("E050","Nqobile Mhlanga","Nqobile","","Mhlanga","Winner(special)","","Mathematical maze (Minecraft)","uni=Wits University (mathematics & computer science student)|award=Audience Vote|src=S52"),
("E050","Previn Ramiah","Previn","","Ramiah","Winner(special)","","Chemistry lab adaptation (Minecraft)","uni=Wits University (Pharmacy; Wits Advanced Drug Delivery Platform)|award=Social Media Challenge|src=S52"),
# ---- E051 Wits supercomputing awards 2018 ----
("E051","Hassaan Hameed","Hassaan","","Hameed","Winner(special)","(most innovative team)","","uni=Wits University (2nd-year biomedical engineering)|src=S52"),
("E051","Basheq Tarifi","Basheq","","Tarifi","Winner(special)","(most innovative team)","","uni=Wits University (2nd-year biomedical engineering)|src=S52"),
("E051","Nathan Jones","Nathan","","Jones","Winner(special)","(most innovative team)","","uni=Wits University (2nd-year biomedical engineering)|src=S52"),
("E051","Sansha Gupta","Sansha","","Gupta","Winner(special)","(most innovative team)","","uni=Wits University (2nd-year electrical engineering)|src=S52"),
("E051","Anita de Mello Koch","Anita","","de Mello Koch","Winner(special)","(best teamwork)","","uni=Wits University (3rd-year information engineering)|src=S52"),
("E051","Kaamilah Desai","Kaamilah","","Desai","Winner(special)","(best teamwork)","","uni=Wits University (3rd-year information engineering)|src=S52"),
("E051","Brendon Swanepoel","Brendon","","Swanepoel","Winner(special)","(best teamwork)","","uni=Wits University (3rd-year information engineering)|src=S52"),
("E051","Nicholas Kastanos","Nicholas","","Kastanos","Winner(special)","(best teamwork)","","uni=Wits University (3rd-year information engineering)|src=S52"),
# ---- E052 MICT SETA KZN Regionals 2026 ----
("E052","Lindokuhle Mnguni","Lindokuhle","","Mnguni","1","DUT Informatics","","uni=Durban University of Technology|award=R100,000|src=S53"),
("E052","Queen Hadebe","Queen","","Hadebe","1","DUT Informatics","","uni=Durban University of Technology|award=R100,000|src=S53"),
("E052","Sanelisekile Nqabeni","Sanelisekile","","Nqabeni","1","DUT Informatics","","uni=Durban University of Technology|award=R100,000|src=S53"),
("E052","Siqiniseko Ntombela","Siqiniseko","","Ntombela","2","Team Demo","Tourism safety app (dangerous-area alerts, safer routes)","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Andile Ntshangase","Andile","","Ntshangase","2","Team Demo","Tourism safety app","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Bukeka Nxumalo","Bukeka","","Nxumalo","2","Team Demo","Tourism safety app","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Mesuli Gama","Mesuli","","Gama","2","Team Demo","Tourism safety app","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Mbuso Khoza","Mbuso","","Khoza","2","Team Demo","Tourism safety app","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Gomotso Mohapi","Gomotso","","Mohapi","3","Clever Programming","","uni=Durban University of Technology|award=R50,000|src=S53|note=Members from Mercury syndicated variant page"),
("E052","Ntokozo Ngcobo","Ntokozo","","Ngcobo","3","Clever Programming","","uni=Durban University of Technology|award=R50,000|src=S53"),
("E052","Lwazi Ncongwana","Lwazi","","Ncongwana","3","Clever Programming","","uni=Durban University of Technology|award=R50,000|src=S53"),
# ---- E053 MICT SETA Eastern Cape leg 2026 ----
("E053","Kamva Twala","Kamva","","Twala","1","","","uni=Nelson Mandela University|org=Digital Ubuntu (Cybersecurity/AI initiative, Google.org) alumnus|award=R100,000|src=S54"),
("E053","Kateko Tivane","Kateko","","Tivane","1","","","uni=Nelson Mandela University|award=R100,000|src=S54"),
("E053","Daniel Basiwe","Daniel","","Basiwe","1","","","uni=Nelson Mandela University|award=R100,000|src=S54"),
("E053","Namhla Lingela","Namhla","","Lingela","1","","","uni=Nelson Mandela University|award=R100,000|src=S54"),
("E053","Katlego Molotsi","Katlego","","Molotsi","1","","","uni=Nelson Mandela University|award=R100,000|src=S54"),
# ---- E055 UFS Beat the Banker 2026 ----
("E055","Takalani Mukhevho","Takalani","","Mukhevho","1","","KasiCred (township SME credit platform)","uni=University of the Free State|src=S55"),
("E055","Oliver Mpofu","Oliver","","Mpofu","1","","KasiCred","uni=University of the Free State|src=S55"),
("E055","Lukhulo Vongo","Lukhulo","","Vongo","2","","Money Matters (financial-management platform)","uni=University of the Free State|src=S55"),
("E055","Noziphiwo Mpikeleli","Noziphiwo","","Mpikeleli","2","","Money Matters","uni=University of the Free State|src=S55"),
("E055","Francis Ndlovu","Francis","","Ndlovu","2","","Money Matters","uni=University of the Free State|src=S55"),
("E055","Mnqobi Madlala","Mnqobi","","Madlala","2","","Money Matters","uni=University of the Free State|src=S55"),
("E055","Oamogetswe Phiri","Oamogetswe","","Phiri","2","","Money Matters","uni=University of the Free State|src=S55"),
("E055","Luyanda Shezi","Luyanda","","Shezi","3","","","uni=University of the Free State|src=S55"),
("E055","Ismael Dlamini","Ismael","","Dlamini","3","","","uni=University of the Free State|src=S55"),
("E055","Edwin van Zyl","Edwin","","van Zyl","3","","","uni=University of the Free State|src=S55"),
("E055","Ofentse Ngcongca","Ofentse","","Ngcongca","3","","","uni=University of the Free State|src=S55"),
("E055","Ultimate Ngobeni","Ultimate","","Ngobeni","Winner(special)","","","uni=University of the Free State|award=BBD Prize for Most Professional GitHub Repository|src=S55"),
("E055","Phemelo Mokwena","Phemelo","","Mokwena","Winner(special)","","","uni=University of the Free State|award=BBD Prize for Most Professional GitHub Repository|src=S55"),
("E055","Ivy Mutodi","Ivy","","Mutodi","Winner(special)","","","uni=University of the Free State|award=BBD Prize for Most Professional GitHub Repository|src=S55"),
("E055","Darrell Nkosi","Darrell","","Nkosi","Winner(special)","","","uni=University of the Free State|award=BBD Prize for Most Professional GitHub Repository|src=S55"),
("E055","Sindiswa Baloyi","Sindiswa","","Baloyi","Winner(special)","","","uni=University of the Free State|award=BBD Prize for Most Professional GitHub Repository|src=S55"),
("E055","Sizwe Nkuna","Sizwe","","Nkuna","Winner(special)","","","uni=University of the Free State|award=Special additional prize from judging panel (completed project solo after teammates withdrew)|src=S55"),
# ---- E056 Telkom 10X Free State 2025 ----
("E056","Delight Chetter","Delight","","Chetter","1","DeTech","Fire-Link Lite (fire alert system for vulnerable communities)","uni=Central University of Technology|award=R15,000|src=S56"),
("E056","Kabelo Makhetha","Kabelo","","Makhetha","1","DeTech","Fire-Link Lite","uni=Central University of Technology|award=R15,000|src=S56"),
# ---- E061 CyberSecureTech 2025 ----
("E061","Sandra Mukhumo","Sandra","","Mukhumo","1","Mzansi Shield","(cybersecurity solution)","uni=University of Venda|award=R20,000 (ceremony article; R25,000 per other UNIVEN article — conflict)|cpl=Medium|src=S59,S60"),
("E061","Phooko Mokgomme","Phooko","","Mokgomme","1","Mzansi Shield","(cybersecurity solution)","uni=University of Venda|award=R20,000 (ceremony article; R25,000 per other UNIVEN article — conflict)|cpl=Medium|src=S59,S60"),
("E061","Titelo Maleka","Titelo","","Maleka","1","Mzansi Shield (probable member)","(cybersecurity solution)","uni=Tshwane University of Technology|cid=Low|src=S59|note=Listed in 'Adapt IT Mentors and First Place Winners' caption — role ambiguous (mentor vs team member); not sufficiently verified"),
("E061","Sigidane Khumbudzo","Sigidane","","Khumbudzo","1","Mzansi Shield (probable member)","(cybersecurity solution)","uni=University of Venda|cid=Low|src=S59|note=As above — caption ambiguity"),
("E061","Amokelane Bele","Amokelane","","Bele","2","Cyber Blockers","","uni=University of Venda (inferred from UNIVEN event)|cid=Medium|award=R10,000 (ceremony article; R15,000 per other article — conflict)|src=S59,S60"),
("E061","Rabelani Mufamadi","Rabelani","","Mufamadi","2","Cyber Blockers","","uni=University of Venda (inferred from UNIVEN event)|cid=Medium|award=R10,000 (ceremony article; R15,000 per other article — conflict)|src=S59,S60"),
# ---- E034 Geekulcha Hackathon 2023 ----
("E034","Gerrard Lewu","Gerrard","","Lewu","Top10","Code Blooded","HarvestHub Technologies (rural/agri economies)","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Morena Ramateletse","Morena","","Ramateletse","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Sinovuyo Sondara","Sinovuyo","","Sondara","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Kamogelo Seale","Kamogelo","","Seale","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Gratitude Phoku","Gratitude","","Phoku","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Nhlanhla Nwariwe","Nhlanhla","","Nwariwe","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Jenifer Brown","Jenifer","","Brown","Top10","Code Blooded","HarvestHub Technologies","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Dean Dube","Dean","","Dube","Top10","Who's Next","Emerge Connect (emergency-services turnaround)","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Boiketlo Ramoabi","Boiketlo","","Ramoabi","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Fortunate Sadiki","Fortunate","","Sadiki","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Lesego Lubisi","Lesego","","Lubisi","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Siphokazi Malesa","Siphokazi","","Malesa","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Boitumelo Moile","Boitumelo","","Moile","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
("E034","Themba Mabuza","Themba","","Mabuza","Top10","Who's Next","Emerge Connect","uni=North-West University (Vanderbijlpark)|src=S61"),
# ---- E035 Geekulcha Annual Hackathon 2025 ----
("E035","Delight Chetter","Delight","","Chetter","3","DeTech","(Geekulcha 2025 entry)","uni=Central University of Technology|src=S56"),
("E035","Kabelo Makhetha","Kabelo","","Makhetha","3","DeTech","(Geekulcha 2025 entry)","uni=Central University of Technology|src=S56"),
# ---- E062 UCT FIH x Interledger 2025 ----
("E062","Sakeena Majiet","Sakeena","","Majiet","2","Team Fin Illuminaries","USSD-based Interledger access via spaza shops","uni=UCT (student, per event context)|cid=Medium|src=S62|note=Named in photo caption for 2nd-place team; full roster not stated"),
("E062","Moegamat Rashaad Samsodien","Moegamat","Rashaad","Samsodien","2","Team Fin Illuminaries","USSD-based Interledger access via spaza shops","cid=Medium|src=S62|note=As above"),
("E062","Amukelani Rikhotso","Amukelani","","Rikhotso","2","Team Fin Illuminaries","USSD-based Interledger access via spaza shops","cid=Medium|src=S62|note=As above"),
("E062","Raibim Alam","Raibim","","Alam","2","Team Fin Illuminaries","USSD-based Interledger access via spaza shops","cid=Medium|src=S62|note=As above; one further name in caption not legible in snapshot"),
# ---- E063 UCT FIH x Interledger 2026 ----
("E063","Kerry-Lynne White","Kerry-Lynne","","White","1","(UCT MPhil FinTech team)","Fireline (community micro-insurance with rapid fire payouts)","uni=University of Cape Town (MPhil FinTech)|award=R35,000|src=S63|note=One of three team members; other two not named in coverage"),
# ---- E064 UCT Surgical hackathon 2025 ----
("E064","Ludolph Pedro","Ludolph","","Pedro","1","Authentic Intelligence","Street Smarts (child body-autonomy/consent safety game app)","src=S64"),
("E064","Bunono Frans","Bunono","","Frans","1","Authentic Intelligence","Street Smarts","src=S64"),
("E064","Wanda Madasa","Wanda","","Madasa","1","Authentic Intelligence","Street Smarts","src=S64"),
("E064","Rahul Rama-Panchia","Rahul","","Rama-Panchia","1","Authentic Intelligence","Street Smarts","src=S64"),
("E064","Simphiwe Malinga","Simphiwe","","Malinga","1","Authentic Intelligence","Street Smarts","src=S64"),
# ---- E065 Innovate Africa Fund 2025 ----
("E065","Lucy Kgware","Lucy","","Kgware","1","(SA team three)","Address Me (verifiable digital addressing for informal settlements)","award=share of $100k prize pool (top prize)|src=S65"),
("E065","Thina Mathebula","Thina","","Mathebula","1","(SA team three)","Address Me","src=S65"),
("E065","Phumla Makhoba","Phumla","","Makhoba","1","(SA team three)","Address Me","src=S65"),
("E065","Sicelo Shange","Sicelo","","Shange","1","(SA team three)","Address Me","src=S65"),
("E065","Lerato Masango","Lerato","","Masango","1","(SA team three)","Address Me","src=S65"),
# ---- E069 EC Youth Digital Agrisec Hackathon 2022 ----
("E069","Lifa Gomomo","Lifa","","Gomomo","1","","Android app for real-time farmer information dissemination","uni=Walter Sisulu University (Komani, ITS)|award=1st place; R20,000 towards AI module|src=S69"),
("E069","Aphiwe Mazwi","Aphiwe","","Mazwi","1","","Android agri-information app","uni=Walter Sisulu University (Komani, ITS)|award=1st place|src=S69"),
("E069","Francine Tembo","Francine","","Tembo","1","","Android agri-information app","uni=Walter Sisulu University (Komani, ITS)|award=1st place|src=S69"),
("E069","Asekhona Xanywa","Asekhona","","Xanywa","1","","Android agri-information app","uni=Walter Sisulu University (Komani, ITS)|award=1st place|src=S69"),
# ---- E070 PAICTA International Hackathon 2022 ----
("E070","Lifa Gomomo","Lifa","","Gomomo","Qualified","","","uni=Walter Sisulu University|src=S69|note=Qualified through Agrisec win; placement at international event Unknown"),
("E070","Aphiwe Mazwi","Aphiwe","","Mazwi","Qualified","","","uni=Walter Sisulu University|src=S69"),
("E070","Francine Tembo","Francine","","Tembo","Qualified","","","uni=Walter Sisulu University|src=S69"),
("E070","Asekhona Xanywa","Asekhona","","Xanywa","Qualified","","","uni=Walter Sisulu University|src=S69"),
# ---- E071 DIRISA Datathon 2022 ----
("E071","Fikile Motha","Fikile","","Motha","Winner(special)","Alpha Logic","","uni=Tshwane University of Technology|award=Consistent Student award|src=S70"),
("E071","Husnaa Molvi","Husnaa","","Molvi","Winner(special)","Recursive Redemption","","uni=University of Johannesburg|award=Best Research Poster|src=S70"),
("E071","Kyle Botes","Kyle","","Botes","Winner(special)","Recursive Redemption","","uni=University of Johannesburg|award=Best Research Poster|src=S70"),
("E071","Ditshego Ntoagae","Ditshego","","Ntoagae","Winner(special)","Mighty Ridge","","uni=Saulridge Secondary School|award=Female empowerment bursary|src=S70"),
("E071","Khanyisa Mokgoloboth","Khanyisa","","Mokgoloboth","Winner(special)","Cyber Eclipse","","uni=Sefako Makgatho Health Sciences University|award=Female empowerment bursary|src=S70"),
# ---- E072 DIRISA Datathon 2023 ----
("E072","Daniel Kenan Slinda","Daniel","Kenan","Slinda","Winner(special)","Fix8t","","uni=University of Mpumalanga|award=Best male student bursary (R100,000)|src=S72"),
("E072","Tshepiso Mogola","Tshepiso","","Mogola","Winner(special)","","","uni=Phateng Secondary School|award=Best female student bursary (R100,000)|src=S72"),
# ---- E075 SA Space Design Competition 2026 ----
("E075","Benjamin Honigwachs","Benjamin","","Honigwachs","1","Team ZA","(winning national finals team -> Team ZA)","uni=Bishops Diocesan College (per Daily Maverick)|src=S74|note=Team ZA then won international ISSDC finals (Florida, Jul-Aug 2026) in Rockdonnell"),
("E075","Joseph Allderman","Joseph","","Allderman","1","Team ZA","(winning national finals team -> Team ZA)","src=S74|note=Won Anita Gale Creative Genius Prize at international finals"),
("E075","Ethan Schoombee","Ethan","","Schoombee","1","Team ZA","(winning national finals team -> Team ZA)","src=S74,S83"),
("E075","Alaya Kaplen","Alaya","","Kaplen","1","Team ZA","(winning national finals team -> Team ZA)","src=S74,S83"),
("E075","Dean Weich","Dean","","Weich","1","Team ZA","(winning national finals team -> Team ZA)","src=S74,S83"),
("E075","Zayaan Abdurahman","Zayaan","","Abdurahman","1","Team ZA","(winning national finals team -> Team ZA)","src=S74,S83"),
("E075","Qayalah Omar","Qayalah","","Omar","1","Team ZA","(winning national finals team -> Team ZA)","src=S74"),
# ---- E076 HackAtom SA 2026 ----
("E076","Philani Gabriel Marapira","Philani","Gabriel","Marapira","1","ZuluTechCollective","(energy-challenge winning solution)","uni=University of Zululand|note=Team leader; other members not named in coverage|src=S75"),
# ---- E078 Girls Game Jam 2025 ----
("E078","Danica Adlam","Danica","","Adlam","1","","Berets and Baguettes (winning game)","award=Trip to Playtopia Festival, Cape Town|src=S77"),
("E078","Trich Semakula","Trich","","Semakula","1","","Berets and Baguettes (winning game)","award=Trip to Playtopia Festival, Cape Town|src=S77"),
# ---- E080 Cloud DevJam (Zaio) ----
("E080","Sinaye Sotatshe","Sinaye","","Sotatshe","Top10","","","uni=University of Zululand (3rd-year CS)|src=S79"),
("E080","Ronica Singh","Ronica","","Singh","Top10","","","org=Software developer (Durban-based, per UNIZULU)|src=S79"),
# ---- E082 IATF Healthcare Hackathon 2025 (SA-connected winner) ----
("E082","Jamie Thurston Wyngaard","Jamie","Thurston","Wyngaard","1","Loop / Dillets","Loop healthcare payments/access via WhatsApp","org=Loop (co-founder, South African)|award=share of $20,000|src=S81|note=Event physically outside SA (IATF 2025); included under SA-connection rule"),
("E082","Dimakatso Kanyane","Dimakatso","","Kanyane","1","Loop / Dillets","Dillets menstrual healthcare products","award=share of $20,000|src=S81|note=SA connection probable (per coverage framing) — verify nationality/SA-base before upgrading confidence"),
# ---- E067 Township Tech 2021 ----
("E067","Zandile Tlhapi","Zandile","","Tlhapi","1","Tech Khaltsha","(township safety & security solution)","award=R5,000 + 10-month entrepreneurial programme + pitch-of-the-day R5,000|src=S67"),
# ---- E068 AB4IR Hackathon 2021 ----
("E068","Katlego Matshwi","Katlego","","Matshwi","1","Captured","Social + business networking app for creatives","award=R15,000|src=S68"),
]
