# -*- coding: utf-8 -*-
"""SA Hackathon Census — source register + hackathon master data (Phase 1).
Every record was captured from a live web source on 2026-08-26. U = Unknown / Not publicly verified.
"""

U = "Unknown"

# Evidence register seeds: id -> (title, publisher, url, pub_date, source_type, primary_or_secondary, strength, excerpt)
SOURCES = {
 "S01": ("moWallet, Lazy Lizzard and MoveThisStuff win #Hack.Jozi Challenge", "Innovation Village",
         "https://innovation-village.com/mowallet-lazy-lizzard-and-movethisstuff-win-hack-jozi-challenge/",
         "2015-07", "News article", "Secondary", "Strong",
         "Desmond Mongwe of MoWallet awarded R1m; Niel Pieters (Lazy Lizzard) and Percy Lawrence (MoveThisStuff) R350k each; 140 applications, 10 finalists; 100 delegates in Seed Academy accelerator + technical hackathons"),
 "S02": ("Hack Jozi Challenge is the real deal", "City of Johannesburg (joburg.org.za)",
         "https://www.joburg.org.za/media_/Newsroom/Pages/2016%20&%202015%20Articles/hack-jozi-challenge-is-the-real-deal-ID9917.aspx",
         "2015-08-11", "Government news", "Primary", "Strong",
         "Top 10 finalists named: Diepkloof Kasi Hive, MoveThisStuff, i-Tea, MoWallet, Atinov, Ghost, Tirisan Tech Solutions, South African Trade Solutions, Lazy Lizzard, How2Get2; MoWallet R1m 1st; MoveThisStuff 2nd; Lazy Lizzard 3rd (per this source)"),
 "S03": ("#HackJozi Challenge winner announced", "Tshimologong Precinct (blog)",
         "https://tshimologong.wordpress.com/2015/07/10/hackjozi-challenge-winner-announced/",
         "2015-07-10", "Organiser blog", "Primary", "Strong",
         "Winner Desmond Mongwe; 1st Runner Up Niel Pieters (Lazy Lizzard); 2nd Runner Up Percy Lawrence (Move This Stuff) — conflicts with joburg.org.za ordering"),
 "S04": ("E-health startup wins $64k at #Hack.Jozi Challenge", "Disrupt Africa",
         "https://disrupt-africa.com/2016/05/23/e-health-startup-wins-64k-at-hack-jozi-challenge/",
         "2016-05-23", "News article", "Secondary", "Strong",
         "2016 winner Technovera (Neo Hutiri) R1m; runners-up Tuta-Me and eSubmit R350k each; 400+ applications; top 10; CoJ + JCSE Wits"),
 "S05": ("Hack.Jozi winners impress", "ITWeb",
         "https://www.itweb.co.za/article/hackjozi-winners-impress/XGxwQDq1rNZvlPVo",
         "2016", "News article", "Secondary", "Strong",
         "Neo Hutiri R1m; Abed Tau and Dylan Hyslop (Tuta-Me) 2nd; Lomile Mokoka (eSubmit, architect) 3rd"),
 "S06": ("Spaza shop discount App wins inaugural Hack.Jozi challenge", "Engineering News",
         "https://www.engineeringnews.co.za/print-version/digital-marketing-solution-wins-r1-million-in-hackjozi-challenge-2015-07-24",
         "2015-07-24", "News article", "Secondary", "Strong",
         "Desmond Mongwe (moWallet founder/CTO) PopApp Deals R1m; Niel Pieters (Lazy Lizzard founder/CEO) Teachinator R350k; 140 participants"),
 "S07": ("The Largest All-Female Hackathon In South Africa Concluded With A Trip To Silicon Valley For The Winners", "iAfrikan",
         "https://www.iafrikan.com/2017/08/12/girlcode-the-largest-all-female-hackathon-in-south-africa/",
         "2017-08-12", "News article", "Secondary", "Strong",
         "GirlCodeHack 2017 (JHB, 70+ women): winners The Rubies (UCT), project Amava; 2nd Grapes; 3rd Techtress (Kgosigadi app)"),
 "S08": ("UCT students win women-only hackathon", "Brand South Africa",
         "https://www.brandsouthafrica.com/investments-immigration/uct-students-win-women-only-hackathon",
         "2017-08-10", "News article", "Secondary", "Strong",
         "Rubies team members: Kungela Mzuku, Fadzai Mupfunya, Lorna Nqodi, Valerie Tshiani (UCT); 4th annual #GirlCodeHack, 6 Aug 2017, Johannesburg"),
 "S09": ("Winners of GirlCode's women-only hackathon named", "ITWeb",
         "https://www.itweb.co.za/article/winners-of-girlcodes-women-only-hackathon-named/Gb3BwMW8GOrq2k6V",
         "2022-03-11", "News article", "Secondary", "Strong",
         "8th edition (Takealot partnership, theme 'Break the bias'): 1st NTV; 2nd Hack-Gen; 3rd Hack Invasion Girls; member names not published"),
 "S10": ("SA teams recognised at GirlCodeHack 2025", "ITWeb",
         "https://www.itweb.co.za/article/sa-teams-recognised-at-girlcodehack-2025/RgeVDvPR9WXMKJN3",
         "2025-10-21", "News article", "Secondary", "Strong",
         "11th edition, 30-hour, 8 African cities: city winners incl. TechGurlies (JHB, FinLit GPT), Ndlela (CPT, AI Career Coach), CyberShield Africa (DBN, Rural Cyber App); overall winner Tokiva Sisters (Tanzania) R100k"),
 "S11": ("Makerere University's Code Forces Triumph at the 2025 Absa GirlCode Hackathon", "PC Tech Magazine",
         "https://pctechmag.com/2025/10/makerere-university-triumph-at-the-2025-absa-girlcode-hackathon/",
         "2025-10-21", "News article", "Secondary", "Moderate",
         "Continental standings: 1st Tokiva Sisters (TZ), 2nd Tech Gullies (SA), 3rd Code Forces (UG); 'Tech Gullies' vs ITWeb 'TechGurlies' spelling variant"),
 "S12": ("Ryan Louw wins 2017 Entelect Challenge", "Entelect",
         "https://entelect.co.za/ryan-louw-wins-2017-entelect-challenge/",
         "2017-10-06", "Organiser announcement", "Primary", "Strong",
         "Finals at rAge Expo 7 Oct: 1 Ryan Louw (Colonel Panic, C#, R70k); 2 Dion van Huyssteen R35k; 3 Anesu Jairosi R25k; 4 Jaco Mostert R25k; 5 Willie Theron R10k; 6 Wynand Wolmarans R10k; Battleships-based game, six months of play"),
 "S13": ("Entelect LinkedIn post: 2022 Entelect Challenge finals", "Entelect (LinkedIn)",
         "https://za.linkedin.com/posts/entelect_entelectchallenge-coding-competition-activity-6980752619631726592-YSb8",
         "2022-09-28", "Organiser social post", "Primary", "Moderate",
         "Finals at Comic Con Africa: champion Kobus van Schoor; Willie Theron 2nd; Tian Cilliers 3rd; top 8"),
 "S14": ("Entelect Challenge 2023: Finals at Comic-Con Africa", "Entelect (culture.entelect.co.za)",
         "https://culture.entelect.co.za/stories/entelect-challenge-2023-finals-at-comic-con-africa/",
         "2023-12-05", "Organiser announcement", "Primary", "Strong",
         "2023 game Cy-Fi; 1st Purpose Katakwa (bot mari.ai, R70k); 2nd Kobus van Schoor; 3rd Anesu Jairosi; 8 finalists; 'now in its 11th year'"),
 "S15": ("2024 Entelect challenge finals: South Africa's top coders battle it out at Comic Con Africa", "MyBroadband",
         "https://mybroadband.co.za/news/industrynews/564860-2024-entelect-challenge-finals-south-africas-top-coders-battle-it-out-at-comic-con-africa.html",
         "2024-10-11", "News article", "Secondary", "Strong",
         "1 Willie Theron R70k; 2 Riaan Nel R35k; 3 Marvin Thobejane R25k; 4 Jesse Bristow; 5 Kobus Van Schoor; 6 Scott Schultz; 7 Jean-Paul De Conceicao; 8 Aneso Jairosi; game Sproutopia; '13th year'"),
 "S16": ("Entelect challenge 2019 (personal blog)", "japeyjapes (WordPress)",
         "https://japeyjapes.wordpress.com/2019/09/24/entelect-challenge-2019/",
         "2019-09-24", "Participant blog", "Participant-generated", "Moderate",
         "Author's bot MrLavaLava placed 3rd in 2019 Entelect Challenge (finals Comic Con Africa, top 8 share R200k); author's real name not stated on page"),
 "S17": ("{code}bridge — Hack4Water hackathons (participant lists)", "{code}bridge / Code for South Africa",
         "https://www.codebridge.co.za/allevents/hack4water-hack4water-hackathons.html",
         "2016", "Organiser page", "Primary", "Moderate",
         "Named participants for Cape Town (Codebridge), Durban (The Green Door) and Pretoria (Innovation Hub) Hack4Water hackathons; teams incl. Fix It. NOTE: page captured via search snapshot 2026-08-26 (direct fetch failed; URL as indexed may differ — re-verify)"),
 "S18": ("Hack4Water Hackathon", "Code for South Africa (code4sa.org)",
         "https://code4sa.org/2016/04/04/hack4water-hackathon.html",
         "2016-04-04", "Organiser blog", "Primary", "Moderate",
         "Cape Town hackathon weekend part of nationwide Hack4Water challenge with Dept of Water & Sanitation + Open Government Partnership"),
 "S19": ("RHoK Pretoria 2014 — Hacking for Humanity", "mLab",
         "https://mlab.co.za/news/rhok-pretoria-2014-hacking-for-humanity/",
         "2014", "Organiser blog", "Primary", "Strong",
         "Top 3: 1 Geekulcha electronics app; 2 UNISA MyCampus Buildings; 3 P-STEM portal. Awards: Kutlwano Kemisho (best female hacker), Josiah Masango (best hacking spirit), Lehlogonolo Sathekge (best social media), Desiree Mampane (best tweet), Diamond Mubaraack, Joao Nzango (GeekStar)"),
 "S20": ("Random Hacks of Kindness — Johannesburg / Pretoria (Google Group thread)", "lambda-luminaries (Google Groups)",
         "https://groups.google.com/g/lambda-luminaries/c/t6sthhWGUzg",
         "2013", "Community announcement", "Primary", "Moderate",
         "RHoK Johannesburg 30 Nov–1 Dec 2013 at ThoughtWorks, 17 Melle St, Braamfontein; organiser thread mentions Andreas Pauley; RHoK Pretoria same weekend"),
 "S21": ("Random Hacks of Kindness — Wikipedia", "Wikipedia",
         "https://en.wikipedia.org/wiki/Random_Hacks_of_Kindness",
         "2026", "Encyclopedia", "Secondary", "Moderate",
         "RHoK 3.0 events held twice in 2012 (June & December) 'saw multiple cities... including Cape Town'"),
 "S22": ("International Space Apps Challenge 2013 — Johannesburg/Pretoria location page", "NASA Space Apps (2013 archive)",
         "https://2013.spaceappschallenge.org/location/johannesburg",
         "2013", "Competition platform", "Primary", "Strong",
         "SA leg 20-21 Apr 2013: main event mLab Pretoria; virtual sites Stellenbosch & Cape Town. Local awards: The Blue Marble (Space Decode); Database of Near Earth Objects (Solar system simulator); Reach for the Stars (Augmented Solar System); Smart Cities & Smart Climate (SmartT Resources)"),
 "S23": ("Hacking healthcare in South Africa", "MaRS Discovery District",
         "https://marsdd.com/news-and-insights/hacking-healthcare-south-africa",
         "2014-02-19", "Sector publication", "Secondary", "Strong",
         "Hacking Health Cape Town, 24-25 Jan 2014, Groote Schuur Hospital; 100+ participants, 30 challenges, 10 teams; winner ECTracker led by medical student Farah Jawitz; organised by UCT Inclusive Healthcare Innovation Initiative + Hacking Health + Medic Mobile"),
 "S24": ("#GovHackSA hackathon report", "mLab",
         "https://mlab.co.za/news/govhacksa/",
         "2014-05-26", "Organiser blog", "Primary", "Strong",
         "Cape Town at 22seven offices, 40+ participants; winning group 'Pulse' (Active Citizen challenge): Alek Gallo, Bruce Bassett, Riccardo Iovino, Michael Graaf, Coenraad Loubser (mobile micro-polling platform); judges incl. Brett St Clair (Google), Cllr Garreth Bloor"),
 "S25": ("UJ students won Discovery IT Graduate Hackathon", "University of Johannesburg",
         "https://news.uj.ac.za/news/uj-students-won-discovery-it-graduate-hackathon-2/",
         "2014-08-04", "University news", "Primary", "Strong",
         "First-ever Discovery GradHack 2014 won by UJ ACSSE team Health Ninjas: Michael Wright, Egbert van der Westhuizen, Lourens Badenhorst, Martin Trollip (Vitality-focused Android app)"),
 "S26": ("South African Engineers expose Discovery Vitality cheaters", "The Techieguy",
         "https://thetechieguy.com/south-african-engineers-expose-discovery-vitality-cheaters/",
         "2015-08-26", "Tech blog", "Secondary", "Moderate",
         "UJ ACSSE students won Discovery GradHack national finals in 2014 and 2015; also won Microsoft Imagine Cup SA national finals four times in six years"),
 "S27": ("Discovery Hackathon hat trick for UJ ACSSE students", "University of Johannesburg",
         "https://news.uj.ac.za/news/discovery-hackathon-hat-trick-for-uj-acsse-students-2/",
         "2016-12-14", "University news", "Primary", "Strong",
         "2016 GradHack winner Team Bithealth (UJ ACSSE): Kyle Alexander, Jihyun Byun, Jacques Oosthuizen, Mario da Silva, Shaun Van Wyk; third consecutive UJ win"),
 "S28": ("UCT team wins national hackathon", "University of Cape Town",
         "https://www.news.uct.ac.za/article/-2018-07-13-uct-team-wins-national-hackathon",
         "2018-07-13", "University news", "Primary", "Strong",
         "2018 Discovery GradHack (JHB, 48h) winner: UCT IS honours team PayDay — Natasha Oates, Nasiha Ally, Ryan Tripod, Zack Zornitta; beat 10 other pitches; UCT IS also won 2017 edition; prize = guaranteed Discovery employment"),
 "S29": ("NWU students win Discovery GradHack (EISH magazine)", "North-West University",
         "https://www.nwu.ac.za/sites/www.nwu.ac.za/files/files/i-media/I-eish-202110/students.html",
         "2021-10", "University news", "Primary", "Strong",
         "2021 GradHack winner NWU Team NeuroTech: Rudi Dreyer, Chris Neuhoff, Franco Bester, Ivan Pretorius (R10k each + R50k to NWU)"),
 "S30": ("UCT wins Discovery GradHack", "University of Cape Town (School of IT)",
         "https://sit.uct.ac.za/articles/2024-07-24-uct-wins-discovery-gradhack",
         "2024-07-24", "University news", "Primary", "Strong",
         "2024 winner Team Cookout (UCT): Jordy Kafwe, Ben Cleveland, Yohannes Gebremeskel Libelo, Maesela Katlego Sekoele (SafeRoute app); top-3 Team Silicon Slippers: Michael Gamsu, Boitumelo Mokoka, Ryan Murphy"),
 "S31": ("Students' IT prowess lands them jobs at Discovery", "North-West University",
         "https://news.nwu.ac.za/students-it-prowess-lands-them-jobs-discovery",
         "2024-08-19", "University news", "Primary", "Strong",
         "NWU team Tasmiyah Nakooda, Ulysses Makubika, Zaid Asvat among top-3 finalists of 72-hour virtual GradHack 2024 (50 students, 16 teams); AI lung-disease detection project; permanent Discovery jobs"),
 "S32": ("BDatSci Final-Years Win the 2025 Discovery GradHack", "Stellenbosch University",
         "https://www.su.ac.za/en/faculties/economy/news/bdatsci-final-years-win-2025-discovery-gradhack",
         "2025-11-11", "University news", "Primary", "Strong",
         "2025 winner VitaliTeam (SU): Mia Olivier, Kayleigh Koekemoer, Jaime Kruger, David Nicolay; R15k each + R50k; finals at Discovery HQ Sandton"),
 "S33": ("SU hackathon goes in a new direction", "Die Matie (MatieMedia)",
         "https://www.matiemedia.org/su-hackathon-goes-in-a-new-direction/",
         "2021-10-19", "Student newspaper", "Secondary", "Strong",
         "2021 SU hackathon (mentors from Entersekt & Capitec): FinTech challenge winner LaTeX on the Beach (Simeon Boshoff, Nadia van Niekerk, Lauren Abrahall, Daniel Olivier, Simon Steven); data challenge winner Designated Derivers (Lance Davids, Musa Maboea, Thamu Mnyulwa); R8k each"),
 "S34": ("SU students tackle data challenge in 40 hours", "Stellenbosch University (SMF News)",
         "https://www.smfnews.org/su-students-tackle-data-challenge-in-40-hours/",
         "2024-08-29", "University news", "Secondary", "Strong",
         "2024 SU LaunchLab/InnovUS hackathon (40 hours, cloud cost management, 9 teams/49 participants): winner Team Apollo — Emma Sharratt, Divan van der Bank, Retief Louw, Dgibrilly Mutabazi, Kharendwe Makhani, Kabelo Maphutha (R7,500)"),
 "S35": ("Two North-West University students win Miway 24-hour hackathon", "MiWay",
         "https://www.miway.co.za/blog/in-the-news/two-north-west-university-students-win-miway-24-hour-hackathon",
         "2019-04-16", "Corporate news", "Primary", "Strong",
         "2nd annual MiWay 24-hours Actuarial Hackathon (25 students, 5 universities): 1st Matt Lourens & Dehan Opperman (NWU masters) R20k; 2nd Christian Hitchcock (UP) R5k; 3rd Lebogang Moremi (UP) R3k; predictive customer retention modelling"),
 "S36": ("NWU duo wins 24-hour hackathon competition", "North-West University",
         "https://news.nwu.ac.za/nwu-duo-wins-24-hour-hackathon-competition",
         "2019", "University news", "Primary", "Strong",
         "Confirms Matt Lourens and Dehan Opperman won 2nd MiWay 24-hours Actuarial Hackathon"),
 "S37": ("NWU IT News 2016 (PDF)", "North-West University IT Services",
         "https://services.nwu.ac.za/sites/services.nwu.ac.za/files/files/information-technology/news/IT-News2016.pdf",
         "2016", "Institutional PDF", "Primary", "Moderate",
         "NWU hackday 2016: 'greenhouse project' and 'virtual museum' teams won (prize: Raspberry Pi 3 model B per team member)"),
 "S38": ("Standard Bank UniHack inspires young developers", "ITWeb",
         "https://www.itweb.co.za/article/standard-bank-unihack-inspires-young-developers/Kjlyr7wBmLXvk6am",
         "2024-07-10", "News article", "Secondary", "Strong",
         "UniHack 2024 (early July, students from four Western Cape universities): 1st Edu Elevators — Andile Masela, Michael Maseko, Olerato Motaung, Nkuleko Nhlapo (AI WhatsApp tutor chatbot); 2nd Health Guardians; 3rd EduDev"),
 "S39": ("Standard Bank Concludes Third Annual UniHack Competition", "Standard Bank",
         "https://www.standardbank.co.za/southafrica/news-and-media/newsroom/standard-bank-concludes-third-annual-unihack-competition",
         "2025-04-07", "Corporate news", "Primary", "Strong",
         "UniHack 2025 (Cape Town, 13 teams): 1st High Five team ('Handy' sign-language app) — Justin Dietrich, Vutivi Makubela, Bailey Mc Jarrow (Stellenbosch), Oluphi Vukaphi, Nabeelah Khan (UWC); 2nd My EduVault; 3rd AI Mental Health Solution"),
 "S40": ("Standard Bank announces UniHack competition winners", "ITWeb",
         "https://www.itweb.co.za/article/standard-bank-announces-unihack-competition-winners/KPNG878NPjDq4mwD",
         "2025-04-08", "News article", "Secondary", "Strong",
         "Corroborates UniHack 2025 winners and Cape Town venue; two-day competition"),
 "S41": ("Standard Bank Ghana's CIB team wins employee hackathon", "ITWeb Africa",
         "https://itweb.africa/content/6GxRKMYQlmBMb3Wj",
         "2024-09-16", "News article", "Secondary", "Moderate",
         "10th annual Kuunda Disrupt Hackathon (Standard Bank employee event): overall winner DigiTrade (Ghana CIB); 395 proposals from 20 markets; top 45 teams/230+ hackers"),
 "S42": ("The winning AI solutions at this year's Standard Bank hackathon", "htxt.africa",
         "https://htxt.co.za/2025/09/the-winning-ai-solutions-at-this-years-standard-bank-hackathon/",
         "2025-09-26", "Tech media", "Secondary", "Moderate",
         "11th Kuunda Disrupt Hackathon, Johannesburg, 244 participants from 20 African countries, 3 days; SA winners unnamed (AI lead-ranking solution; agentic AI tool)"),
 "S43": ("Effingham Heights Primary School wins prestigious Standard Bank Kuunda Disrupt Competition", "IOL / Daily News",
         "https://www.iol.co.za/dailynews/news/effingham-heights-primary-school-wins-prestigious-standard-bank-kuunda-disrupt-competition-d361b66e-fdf8-41e6-a574-af1a9137a840",
         "2024-12-04", "News article", "Secondary", "Moderate",
         "Durban schools STEAM competition at Gordon Road Girls' School (19 schools): 1st 'The Recycling Rangers' — 12 Effingham Heights Primary pupils, 'Smart Eco Bin' (Raspberry Pi-based)"),
 "S44": ("Discover the future: MTN MoMo API Hackathon unveils trailblazing innovations", "IOL",
         "https://www.iol.co.za/technology/techsperts/discover-the-future-mtn-momo-api-hackathon-unveils-trailblazing-innovations-695051ba-a05d-44d5-b2e0-41627d1cacd6",
         "2024-04-23", "News article", "Secondary", "Moderate",
         "MTN MoMo API Hackathon 2023 SA (31 Jul–9 Oct 2023): winners Zaka (cashflow financing), Tata Imali (2nd, micro-lending), MoLo (3rd, P2P lending); $10k prize pool; developer names not published in these sources"),
 "S45": ("Winners of #SS19Hack announced", "ITWeb",
         "https://www.itweb.co.za/content/Pero37ZgwLBMQb6m",
         "2019-05-31", "News article", "Secondary", "Strong",
         "#SS19Hack (JHB, ~50 developers, ~30h, IoT security): 1st Khululeka (blockchain content filtering); 2nd Dumela (Kimberley team); 3rd Watchr (team True Author); overall champion Tumelo Baloyi (disaster-relief volunteering platform); CTF winners Red team / Blue team (JHB); photo caption lists Siyammukela Kasapo, James Miwahili, Ivan Regasek with prize"),
 "S46": ("Absa hosts hackathon to ignite innovation and engagement in the Absa Technology community", "Absa",
         "https://www.absa.africa/media-statements/2024/absa-hosts-hackathon-to-ignite-innovation-and-engagement-in-the-absa-technology-community/",
         "2024-09-13", "Corporate news", "Primary", "Moderate",
         "2nd annual Absa Technology Hackathon (internal, multi-country): 1st Hackernauts (SA+Prague); 2nd Dragons Unleashed (Botswana); 3rd Teamo Supremo (SA)"),
 "S47": ("2021 Absa Design Hackathon", "Absa",
         "https://www.absa.co.za/offers/2021-absa-design-hackathon/",
         "2021", "Corporate page", "Primary", "Strong",
         "Winner ELEV8A: Tsholofelo Radebe, Keletso Moagi, Sihle Dube (R50k); runner-up Omnicorn: Mila Daly, Tawanda Mutambwe, Refilwe Lesego Masekela (R15k)"),
 "S48": ("Absa Teams Build Real-World Banking Solutions in 24 Hours at 2025 Technology Hackathon", "Africa Business (africabusiness.com)",
         "https://africabusiness.com/2025/10/30/absa-teams-build-real-world-banking-solutions-in-24-hours-at-2025-technology-hackathon/",
         "2025-10-30", "News article", "Secondary", "Moderate",
         "2025 Absa Technology Hackathon (24h, internal): AI for Impact winner Mighty Pythons (SA); Blue Sky co-winner Hustle Hub (SA) and Digital Islanders (Mauritius); Commercialisation winner The Solvers (Zambia); R25k per member"),
 "S49": ("Vodacom Group CEO encourages innovation at annual hack-alympics", "Tech Review Africa",
         "https://techreviewafrica.com/news/1281/vodacom-group-ceo-encourages-innovation-at-annual-hack-alympics",
         "2024-03-29", "Tech media", "Secondary", "Moderate",
         "Vodacom Group Annual Hack-alympics 2024: 3-day internal hackathon across SA, Kenya, DRC, Lesotho, Mozambique, Tanzania, Ethiopia, Egypt; winners advance to All-Africa finals; individual winners not published"),
 "S50": ("Wits Uni Student App Challenge winners named", "Disrupt Africa",
         "https://disruptafrica.com/2015/09/02/wits-uni-student-app-challenge-winners-named/",
         "2015-09-02", "News article", "Secondary", "Moderate",
         "Top 3: Gig Guide, I'm Interested, Wits Locate (member names not published); category awards: Wits Meal App (Most Innovative), IQMates (Ready for Market), Bus Control (Most Required); best presentations: Need A Book, Wits Happening, 24"),
 "S51": ("PODCAST: Wits Hackathon winners plan to revolutionise mining industry", "The Citizen",
         "https://www.citizen.co.za/lifestyle/technology/podcast-wits-hackathon-winners-mining/",
         "2023-05-10", "News article", "Secondary", "Strong",
         "First-ever Wits Hackathon (2022, <24h, 'Digitalisation in Mining'): winning team Creative Mines — Taryn Michael, Eli Nimy, Mfundo Monchwe, Clarence Mantiya, Kurhula Manganyi (OCR + text analytics; R15k + NEMISA courses)"),
 "S52": ("Wits stories — Minecraft challenge & supercomputing awards", "Wits University",
         "https://www.wits.ac.za/future/stories/",
         "2018-09", "University news", "Primary", "Moderate",
         "Minecraft Education Edition challenge: 1st individual Yadir Purmasir ('The Order of the Stone Academy'); Audience Vote Nqobile Mhlanga; Social Media Challenge Previn Ramiah. Supercomputing: most innovative team Hassaan Hameed, Basheq Tarifi, Nathan Jones, Sansha Gupta; best teamwork Anita de Mello Koch, Kaamilah Desai, Brendon Swanepoel, Nicholas Kastanos"),
 "S53": ("DUT students excel at MICT SETA Hackathon", "The Mercury",
         "https://themercury.co.za/ios/news/2026-04-09-dut-students-excel-at-mict-seta-hackathon-showcasing-innovation-prowess/",
         "2026-04-09", "News article", "Secondary", "Strong",
         "MICT SETA National Skills Challenge Hackathon KZN Regionals (22-23 Mar 2026, MKRI offices Durban): 1st DUT Informatics — Lindokuhle Mnguni, Queen Hadebe, Sanelisekile Nqabeni (R100k); 2nd Team Demo — Siqiniseko Ntombela, Andile Ntshangase, Bukeka Nxumalo, Mesuli Gama, Mbuso Khoza (R50k); 3rd Clever Programming (R50k)"),
 "S54": ("Mandela University students win Eastern Cape leg of National Skills Challenge", "Nelson Mandela University",
         "https://news.mandela.ac.za/News/Mandela-University-students-win-Eastern-Cape-leg-o",
         "2026-03-23", "University news", "Primary", "Strong",
         "EC leg (Gqeberha, 2-day innovation sprint): winner NMU team Kamva Twala, Kateko Tivane, Daniel Basiwe, Namhla Lingela, Katlego Molotsi (R100k; Digital Ubuntu/Google.org alumni); national finals in Gauteng 30-31 Mar 2026"),
 "S55": ("UFS students tackle real-world banking challenges at Beat the Banker Hackathon", "University of the Free State",
         "https://www.ufs.ac.za/templates/news-archive-item/campus-news/2026/june/ufs-students-tackle-real-world-banking-challenges-at-beat-the-banker-hackathon",
         "2026-06-24", "University news", "Primary", "Strong",
         "1st Takalani Mukhevho & Oliver Mpofu (KasiCred); 2nd Lukhulo Vongo, Noziphiwo Mpikeleli, Francis Ndlovu, Mnqobi Madlala, Oamogetswe Phiri (Money Matters); 3rd Luyanda Shezi, Ismael Dlamini, Edwin van Zyl, Ofentse Ngcongca; BBD GitHub prize: Ultimate Ngobeni, Phemelo Mokwena, Ivy Mutodi, Darrell Nkosi, Sindiswa Baloyi; solo participant Sizwe Nkuna; Standard Bank + BBD involved"),
 "S56": ("CUT students take first place at Hackathon", "Bloemfontein Courant",
         "https://www.bloemfonteincourant.co.za/cut-students-take-first-place-at-hackathon/",
         "2025-10-21", "News article", "Secondary", "Strong",
         "Telkom 10X Hackathon Free State leg at Botshabelo Digital Hub: 1st Delight Chetter & Kabelo Makhetha (CUT, DeTech co-founders, Fire-Link Lite, R15k); duo placed 3rd at Geekulcha Annual Hackathon"),
 "S57": ("Innovation takes centre stage at 4th Annual Limpopo Varsity Hackathon", "Tshwane University of Technology",
         "https://www.tut.ac.za/newsroom/all-news/2025/innovation-takes-centre-stage-at-4th-annual-limpopo-varsity-hackathon.php",
         "2025-10-27", "University news", "Primary", "Moderate",
         "LVH 2025 (10-12 Oct 2025, University of Limpopo VL Hall, theme Hack4Mzansi): 1st Master Hackers (borehole dashboard); 2nd Ctrl, Alt & Defeat (pesticide detection); 3rd Byte Bandits (smart traffic light) — member names not published"),
 "S58": ("ICT students drive Tshwane's digital revolution (7th Annual Tshwane Varsity Hackathon)", "Tshwane University of Technology",
         "https://www.tut.ac.za/newsroom/all-news/2025/ict-students-drive-tshwanes-digital-revolution.php",
         "2025-11-03", "University news", "Primary", "Moderate",
         "TVH 2025 (Sept 2025, with City of Tshwane, MTN SA, IQ Business, AWS, Nelekat; TUT/UP/UNISA/SMU): 1st Ubuntu Hackers (Notiza App); 2nd Cybergeeks (Aqua Balance); 3rd Bit by Bit (Kasi Connect) — member names not published"),
 "S59": ("CyberSecureTech Hackathon 2025 Empowers the Youth", "University of Venda",
         "https://www.univen.ac.za/news/cybersecure-tech-hackathon-2025-empowers-the-youth-to-safeguard-south-africas-digital-future/",
         "2026-01-23", "University news", "Primary", "Moderate",
         "18 teams -> 11 finalists: 1st Mzansi Shield (R25k per this article); 2nd Cyber Blockers (R15k); joint 3rd Data Defence Solutions & Zero Trust (R5k each). Caption lists Titelo Maleka (TUT), Sigidane Khumbudzo/Mukhumo Sandra/Phooko Mokgomme (UNIVEN) as 'Adapt IT Mentors and First Place Winners'"),
 "S60": ("UNIVEN Honours Top Innovators at CyberSecureTech Hackathon 2025 Prize Ceremony", "University of Venda",
         "https://www.univen.ac.za/news/univen-honours-top-innovators-at-cybersecuretech-hackathon-2025-prize-ceremony/",
         "2026-04-23", "University news", "Primary", "Moderate",
         "Mzanzi Shield represented by Phooko Mokgomme and Sandra Mukhumo — 1st, R20k (conflicts with S59's R25k); 2nd Cyberblockers: Amokelane Bele & Rabelani Mufamadi, R10k (conflicts with S59's R15k); R40k total awarded"),
 "S61": ("Students excel at annual Geekulcha Hackathon", "North-West University",
         "https://news.nwu.ac.za/students-excel-annual-geekulcha-hackathon",
         "2023-10-16", "University news", "Primary", "Strong",
         "Geekulcha Hackathon 2023 at UNISA Pretoria campus: NWU Vanderbijlpark teams in top 10 — Code Blooded (Gerrard Lewu, Morena Ramateletse, Sinovuyo Sondara, Kamogelo Seale, Gratitude Phoku, Nhlanhla Nwariwe, Jenifer Brown; HarvestHub Technologies) and Who's Next (Dean Dube, Boiketlo Ramoabi, Fortunate Sadiki, Lesego Lubisi, Siphokazi Malesa, Boitumelo Moile, Themba Mabuza; Emerge Connect)"),
 "S62": ("The UCT Financial Innovation Hub and Interledger Foundation Hackathon", "Interledger Foundation",
         "https://interledger.org/news/uct-financial-innovation-hub-and-interledger-foundation-hackathon",
         "2025-07-10", "Funder news", "Primary", "Strong",
         "28 Jun 2025, Cape Town; 12 teams from 4 SA universities after week of training: 1st Team Direla (QR-code ILP transactions); 2nd Team Fin Illuminaries (USSD ILP via spaza shops; members incl. Sakeena Majiet, Moegamat Rashaad Samsodien, Amukelani Rikhotso, Raibim Alam per photo caption); 3rd Team FlowFi (student crowdfunding)"),
 "S63": ("UCT Master's students win financial innovation hub hackathon", "Eyewitness News (EWN)",
         "https://www.ewn.co.za/2026/06/28/uct-master-s-students-win-financial-innovation-hub-hackathon",
         "2026-06-28", "News article", "Secondary", "Moderate",
         "2026 Interledger bootcamp+hackathon (8 students from UCT, Eduvos, Sol Plaatje, UFS): winning 3-member UCT MPhil FinTech team incl. Kerry-Lynne White (Fireline micro-insurance; R35k)"),
 "S64": ("Surgical hackathon team devises 'street smart' solution", "University of Cape Town",
         "https://www.news.uct.ac.za/article/-2025-04-24-surgical-hackathon-team-devises-street-smart-solution",
         "2025-04-24", "University news", "Primary", "Strong",
         "UCT Surgical Society x Harvard HSIL 2-day surgical hackathon concluded 12 Apr 2025: winner Authentic Intelligence — Ludolph Pedro, Bunono Frans, Wanda Madasa, Rahul Rama-Panchia, Simphiwe Malinga ('Street Smarts' child-safety app)"),
 "S65": ("South African team building digital addressing solution wins Innovate Africa Fund hackathon", "Techpoint Africa",
         "https://techpoint.africa/feature/innovate-africa-fund-hackathon/",
         "2025-09-22", "Tech media", "Secondary", "Moderate",
         "Inaugural Innovate Africa Fund hackathon ($100k prize pool; 10 teams from across Africa): winning SA team of five — Lucy Kgware, Thina Mathebula, Phumla Makhoba, Sicelo Shange, Lerato Masango ('Address Me' digital addressing platform)"),
 "S66": ("Hackathons for SA #GBV: Digital Solutions for Real-World Challenges (event page)", "Quicket",
         "https://www.quicket.co.za/events/94401-hackathons-for-sa-gbv-digital-solutions-for-real-world-challenges/",
         "2020", "Event listing", "Primary", "Moderate",
         "Cape Town edition: winning concept by team SmartWare (GBV-prevention education + panic button app); R25k winner prize; Silicon Cape implementation partner; Johannesburg edition also planned"),
 "S67": ("Township Tech hackathon stars revealed", "ITWeb",
         "https://www.itweb.co.za/article/township-tech-hackathon-stars-revealed/lwrKxv3KkVxvmg1o",
         "2021-03-15", "News article", "Secondary", "Strong",
         "CiTi Township Tech hackathon (hybrid final at Woodstock Bandwidth Barn; 40 participants -> 6 finalists): theme winners Tech Khaltsha (safety & security; + 'pitch of the day'; member Zandile Tlhapi), Basket (reach of services), Cyberspace (connectivity)"),
 "S68": ("Township tech innovations provide real-world solutions", "ITWeb",
         "https://www.itweb.co.za/article/township-tech-innovations-provide-real-world-solutions/lwrKxq3KaE1qmg1o",
         "2021-05-04", "News article", "Secondary", "Strong",
         "AB4IR (Africa Beyond 4IR) + Liquid Intelligent Technologies 3-day hackathon (April 2021, Tshwane South TVET College; 250 registrations -> 20 participants): 1st Captured (R15k; member Katlego Matshwi quoted); 2nd Ubunifu (R10k); 3rd My Universe (R5k)"),
 "S69": ("WSU students headed to international hackathon 2022", "Walter Sisulu University",
         "https://www.wsu.ac.za/index.php/media-center/latest-news/286-wsu-newsletter/406-wsu-its-students-headed-to-international-hackathon-2022",
         "2022", "University news", "Primary", "Strong",
         "Eastern Cape Youth Digital Agrisec Hackathon: 1st Lifa Gomomo, Aphiwe Mazwi, Francine Tembo, Asekhona Xanywa (WSU Komani ITS; android agri-info app; R20k + AI module); qualify for PAICTA International Hackathon 2022"),
 "S70": ("2022 DIRISA Student Datathon", "DIRISA",
         "https://sdc.dirisa.ac.za/2022-datathon/",
         "2022", "Organiser page", "Primary", "Strong",
         "26 Nov–2 Dec 2022, CSIR ICC Pretoria; 10 teams. 1st UJ Recursive Redemption; 2nd NWU Eagles; 3rd SPU DataTude; Best team Mighty Ridge (Saulridge Secondary); Consistent Student Fikile Motha (TUT, Alpha Logic); Best Research Poster Husnaa Molvi & Kyle Botes (UJ); bursaries Ditshego Ntoagae (Saulridge) & Khanyisa Mokgoloboth (SMU)"),
 "S71": ("2023 DIRISA Student Datathon winners", "DIRISA",
         "https://www.dirisa.ac.za/2023-dirisa-student-datathon/",
         "2023", "Organiser page", "Primary", "Strong",
         "Theme Youth Unemployment. Technical challenge top 3 (R100k Momentum pool): 1 SPU, 2 Wits, 3 UNIZULU. Research posters: 1 SPU, 2 TUT, 3 UNIZULU. Best team: University of Mpumalanga"),
 "S72": ("DIRISA hosts annual Student Datathon Challenge", "CSIR",
         "https://www.csir.co.za/dirisa-hosts-annual-student-datathon-challenge",
         "2024-01-29", "Organiser news", "Primary", "Strong",
         "2023 datathon awards 7 Dec 2023 Skukuza: Research Poster + Technical winner SPU 'The Domain'ators'; Best team UMpumalanga 'Fix8t'; bursaries Daniel Kenan Slinda (UM) & Tshepiso Mogola (Phateng Secondary); annual since 2019"),
 "S73": ("AI joins the judging panel for 2026 IEB TechWays AI Hackathon — winners announced", "iafrica.com",
         "https://iafrica.com/ai-joins-the-judging-panel-for-2026-ieb-techways-ai-hackathon-2026-winners-announced/",
         "2026-06-18", "News article", "Secondary", "Moderate",
         "National schools AI hackathon: Grade 9+ 1st TrustTrade AI (Hatfield Christian School), RU AquaGuard (Midstream College), RU PlateSmart SA (Kearsney College); 1st Scam Scanner (St Mary's DSG), RU Green Flow (Bridge House School), RU Nomvula (King David Linksfield); Foundations Cup 1st FoodBridge (Ribane Lake School of Specialisation)"),
 "S74": ("Seven SA high schoolers crowned Nasa space champions", "Daily Maverick",
         "https://www.dailymaverick.co.za/article/2026-08-21-sa-high-schoolers-rocket-to-the-top-as-nasa-space-champions/",
         "2026-08-21", "News article", "Secondary", "Strong",
         "Team ZA (7 Western Cape learners) selected at inaugural SA Space Design Competition national finals at UCT (March 2026, 109 learners, 9 schools) then won International Space Settlement Design Competition (Kennedy Space Center, 30 Jul–2 Aug 2026) in team Rockdonnell; Joseph Allderman won Anita Gale Creative Genius Prize"),
 "S75": ("HackAtom Final: University of Zululand team to represent SA in Russia", "TechFinancials",
         "https://techfinancials.co.za/2026/05/12/hackatom-final-university-of-zululand-team-to-represent-sa-in-russia/",
         "2026-05-12", "News article", "Secondary", "Moderate",
         "First SA national round of HackAtom (energy/engineering competition), Durban: winner UNIZULU team ZuluTechCollective, team leader Philani Gabriel Marapira; advances to Moscow final"),
 "S76": ("Fourth place for West Rand in Gauteng's biggest youth tech challenge", "Krugersdorp News (Citizen)",
         "https://www.citizen.co.za/krugersdorp-news/news-headlines/local-news/2026/07/14/fourth-place-for-west-rand-in-gautengs-biggest-youth-tech-challenge/",
         "2026-07-14", "News article", "Secondary", "Moderate",
         "Gauteng Dept of e-Government youth tech challenge 2026: 1st Gridwise 10X (JHB CBD, 84.2%); 2nd Chromomark (Tshwane, 81.6%); 3rd Civic Eye (Sedibeng, 70.2%); 4th SIRRS (West Rand, 63.0%); 5th Aqua Guard AI (Ekurhuleni, 59.0%); teams of 10 learners"),
 "S77": ("Girls Game Jam: Inspiring the next generation of game developers", "French Institute of South Africa",
         "https://frenchinstitute.org.za/arts-and-creative-industries/creative-industries/gaming/girls-game-jam-inspiring-the-next-generation-of-game-developers/",
         "2025-09-03", "Organiser news", "Primary", "Strong",
         "Winning team Danica Adlam and Trich Semakula (game 'Berets and Baguettes'); prize: trip to Playtopia Festival, Cape Town"),
 "S78": ("Global Game Jam 2020 — Make Games South Africa forum thread", "MakeGamesSA",
         "https://makegamessa.com/discussion/5846/global-game-jam-2020-31-jan-2-feb-2020",
         "2019-12-20", "Community forum", "Participant-generated", "Moderate",
         "GGJ 2020 SA sites: Vega School Cape Town and Vega Johannesburg (31 Jan–2 Feb 2020); participant lists live on globalgamejam.org per site"),
 "S79": ("UNIZULU CS news (datathon 3rd place; Cloud DevJam top-10)", "University of Zululand",
         "https://www.science.unizulu.ac.za/cs/category/news/page/2/",
         U, "University news", "Primary", "Moderate",
         "UNIZULU 3rd in CSIR Datathon Challenge (DIRISA student datathon); Sinaye Sotatshe top-10 in international Cloud DevJam Hackathon (organised by Zaio, Cape Town; MERN coding gameshow), paired with Durban developer Ronica Singh"),
 "S80": ("VUT Hackathon 2026 turns student ideas into real world innovation", "Vaal University of Technology",
         "https://vut.ac.za/vut-hackathon-2026-turns-student-ideas-into-real-world-innovation/",
         "2026-05-12", "University news", "Primary", "Weak (partial)",
         "VUT campus hackathon 2026; winning teams progress to regional competition at UFS QwaQwa campus vs SPU, NWU, UFS; winning team names not captured in accessed excerpt"),
 "S81": ("Winners of IATF 2025 Healthcare Hackathon", "Towards Healthcare",
         "https://www.towardshealthcare.com/news/iatf-2025-healthcare-hackathon-winners",
         "2025-09-22", "Sector publication", "Secondary", "Weak (partial)",
         "IATF 2025 Healthcare Hackathon (Afrilabs + Afreximbank, $20k pool): winners Jamie Thurston Wyngaard (SA, Loop co-founder) and Dimakatso Kanyane (Dillets); venue outside SA (IATF); SA connection via Wyngaard"),
 "S82": ("#HackJozi Challenge — ESDSA programme description", "ESDSA",
         "http://www.esdsa.com/hack-jozi.html",
         U, "Programme page", "Secondary", "Weak (partial)",
         "Hack.Jozi described as entrepreneurship competition with 4 categories; confirms winners list for 2015"),
 "S83": ("Business Tech Africa — SA learners win NASA space design competition", "Business Tech Africa",
         "https://www.businesstechafrica.co.za/technology/2026/08/08/seven-south-african-high-school-learners-won-the-international-space-settlement-design-competition/",
         "2026-08-08", "News article", "Secondary", "Moderate",
         "Team ZA members incl. Ethan Schoombee, Alaya Kaplen, Dean Weich, Zayaan Abdurahman (+ Honigwachs, Allderman, Omar per other sources); SA national finals at UCT March 2026 from 109 learners / 9 schools"),
}

# Hackathon master rows. Keys: id,name,alt,edition,year,start,end,city,province,venue,mode,host,org,sponsors,
# theme,est,ver,fin,winners,web,results,partlist,archive,other,compl,notes,src
E = []
def ev(**kw):
    kw.setdefault("alt", U); kw.setdefault("edition", U); kw.setdefault("start", U); kw.setdefault("end", U)
    kw.setdefault("city", U); kw.setdefault("province", U); kw.setdefault("venue", U); kw.setdefault("mode", "Physical")
    kw.setdefault("host", U); kw.setdefault("org", U); kw.setdefault("sponsors", U); kw.setdefault("theme", U)
    kw.setdefault("est", U); kw.setdefault("ver", U); kw.setdefault("fin", U); kw.setdefault("winners", U)
    kw.setdefault("web", U); kw.setdefault("results", U); kw.setdefault("partlist", U); kw.setdefault("archive", U)
    kw.setdefault("other", U); kw.setdefault("compl", "E"); kw.setdefault("notes", "")
    E.append(kw)

ev(id="E001", name="Random Hacks of Kindness (RHoK) — Cape Town", edition="RHoK 3.0", year="2012",
   theme="Civic tech / humanitarian", host="RHoK global community", compl="E",
   notes="Existence per Wikipedia RHoK 3.0 city list (2012 events incl. Cape Town). No local results/participants located this pass.", src=["S21"])
ev(id="E002", name="NASA International Space Apps Challenge — South Africa", edition="2013", year="2013", start="2013-04-20", end="2013-04-21",
   city="Pretoria (main); virtual sites Stellenbosch & Cape Town", province="Gauteng; Western Cape", venue="mLab Southern Africa, Pretoria + virtual", mode="Hybrid",
   host="NASA (global); mLab Southern Africa (local)", theme="Space / open data", fin="4 local award projects", winners="4", results="https://2013.spaceappschallenge.org/location/johannesburg", compl="C",
   notes="Earliest verified Space Apps SA edition. Winning project team members not published on archived page.", src=["S22"])
ev(id="E003", name="Random Hacks of Kindness (RHoK) — Johannesburg", edition="2013", year="2013", start="2013-11-30", end="2013-12-01",
   city="Johannesburg", province="Gauteng", venue="ThoughtWorks, 17 Melle Street, Braamfontein", host="RHoK community (incl. Andreas Pauley et al.)",
   theme="Social / humanitarian", compl="D", notes="Earliest SA hackathon event verified with date+venue this pass. Participant names not located.", src=["S20"])
ev(id="E004", name="Hacking Health Cape Town", edition="2014", year="2014", start="2014-01-24", end="2014-01-25",
   city="Cape Town", province="Western Cape", venue="Groote Schuur Hospital", host="UCT Inclusive Healthcare Innovation Initiative (Bertha Centre + Faculty of Health Sciences) with Hacking Health & Medic Mobile",
   theme="Health", est="100+", fin="10 teams", winners="1", compl="B",
   notes="First health hackathon of its kind on the African continent (per source).", src=["S23"])
ev(id="E005", name="#GovHackSA", edition="2014", year="2014", start="2014-05 (day event)", city="Cape Town", province="Western Cape",
   venue="22seven offices", theme="Govtech / open data", est="40+", winners="1", compl="C",
   notes="Follow-on from SA open data policy work; partnership mentions with Silicon Cape.", src=["S24"])
ev(id="E006", name="Discovery GradHack", edition="2014 (first ever)", year="2014", start="2014-08 (approx)", city=U, province=U,
   host="Discovery", sponsors="Discovery Health", theme="Health / Vitality", winners="1", compl="B",
   notes="National IT graduate hackathon; 2014 winner named; venue not stated in sources used.", src=["S25","S26"])
ev(id="E007", name="Discovery GradHack", edition="2015", year="2015", host="Discovery", theme="Health / Vitality", compl="C",
   notes="Winner: UJ ACSSE students (per The Techieguy); member names not published.", src=["S26"])
ev(id="E008", name="Random Hacks of Kindness (RHoK) — Pretoria", edition="2014", year="2014", city="Pretoria", province="Gauteng",
   venue=U, host="RHoK community / mLab", sponsors="Nokia, IT Varsity (prizes)", theme="Humanitarian", fin="3", winners="3 named solutions", compl="B",
   notes="24-hour event; full special-award winner list captured.", src=["S19"])
ev(id="E009", name="Hack.Jozi Challenge", edition="2015 (inaugural)", year="2015", start="2015 (five-month programme)", end="2015-07-08",
   city="Johannesburg", province="Gauteng", venue="Awards: Wits Origins Centre; accelerator+hackathon sessions", mode="Hybrid",
   host="City of Johannesburg", org="Joburg Centre for Software Engineering (JCSE), Wits University; Seed Academy", sponsors="City of Johannesburg (R5m); IBM Bluemix",
   theme="Smart city / civic innovation", est="140 participants/applications", fin="10", winners="3", compl="B",
   notes="Bootcamp + accelerator + technical hackathons culminating in demo day. Runner-up order conflicting between sources (see contradiction log).", src=["S01","S02","S03","S06","S82"])
ev(id="E010", name="Hack.Jozi Challenge", edition="2016", year="2016", start="2016 (programme)", end="2016-05",
   city="Johannesburg", province="Gauteng", host="City of Johannesburg", org="JCSE Wits", theme="Smart city / civic innovation",
   est="400+ applications", fin="10", winners="3", compl="B", notes="Mirrored by City of Cape Town per Disrupt Africa (separate edition not yet located).", src=["S04","S05"])
ev(id="E011", name="Wits Student App Challenge", edition="2015", year="2015", city="Johannesburg", province="Gauteng",
   venue="Wits Digital Innovation Zone (DIZ)", host="Wits University", theme="Student apps", fin="3+", winners="3 + 3 category + 3 presentation prizes", compl="C",
   notes="Team member names not published.", src=["S50"])
ev(id="E012", name="Hack4Water — hackathon weekend (Codebridge CT / Green Door DBN / Innovation Hub PTA)", edition="2016", year="2016",
   start="2016-04-04 (blog)", city="Cape Town; Durban; Pretoria", province="Western Cape; KwaZulu-Natal; Gauteng",
   venue="{code}bridge CT; The Green Door DBN; Innovation Hub PTA", host="Code for South Africa / {code}bridge",
   org="Department of Water and Sanitation; Open Government Partnership SA", theme="Water / climate / open data", ver="45+ named participants", compl="B",
   notes="Participant lists captured from organiser page via search snapshot (page fetch failed — re-verify URL).", src=["S17","S18"])
ev(id="E013", name="Hack4Water — national challenge", edition="2015/2016", year="2016", host="Department of Water and Sanitation",
   org="Open Government Partnership SA", theme="Water / climate", compl="E",
   notes="Nationwide challenge incl. video/idea competition with multiple categories; winners not located this pass.", src=["S18"])
ev(id="E014", name="NWU Hackday", edition="2016", year="2016", city="Potchefstroom", province="North West", venue="NWU (campus not explicitly stated)",
   host="NWU IT Services", theme="Internal innovation", winners="2 teams", compl="D",
   notes="Winners: 'greenhouse project' and 'virtual museum' teams; member names not captured.", src=["S37"])
ev(id="E015", name="GirlCodeHack (#GirlCodeHack)", edition="2017 (4th annual)", year="2017", start="2017-08-06", city="Johannesburg", province="Gauteng",
   host="GirlCode (GirlCodeZA)", theme="Women in tech", est="70+", fin="3", winners="3", compl="B",
   notes="Prize: trip to US women-in-tech conference.", src=["S07","S08"])
ev(id="E016", name="GirlCodeHack", edition="2022 (8th annual)", year="2022", start="2022-03 (two days)", city="Johannesburg", province="Gauteng",
   host="GirlCode", sponsors="Takealot, AWS, Mint Group, Lenovo", theme="Break the bias (IWD 2022)", fin="3", winners="3", compl="C",
   notes="Winning team member names not published in located sources.", src=["S09"])
ev(id="E017", name="GirlCodeHack (Absa GirlCode Hackathon)", edition="2025 (11th annual)", year="2025", start="2025-10-12", end="2025-10 (30-hour)",
   city="Johannesburg; Cape Town; Durban (+ 5 other African cities)", province="Gauteng; Western Cape; KwaZulu-Natal", mode="Hybrid",
   host="GirlCode", sponsors="Absa", theme="Fintech, cybersecurity and AI", fin="8 city winners", winners="1 continental + 8 city winners", compl="B",
   notes="Continental field; SA city winners named as teams (members not published).", src=["S10","S11"])
ev(id="E018", name="Entelect Challenge", edition="2017", year="2017", start="2017 (six-month series)", end="2017-10-07",
   city="Johannesburg", province="Gauteng", venue="rAge Expo (finals)", host="Entelect", theme="AI bot coding competition",
   est=U, fin="8", winners="6 named", compl="B",
   notes="Long-form national coding competition (not a single-weekend hackathon) — included under 'coding challenge' scope. Full 2017 rankings captured.", src=["S12"])
ev(id="E019", name="Entelect Challenge", edition="2019", year="2019", end="2019-09 (finals)", city="Johannesburg", province="Gauteng",
   venue="Comic Con Africa (finals)", host="Entelect", theme="AI bot coding competition", fin="8", compl="D",
   notes="3rd place documented via participant blog (pseudonymous); full rankings not located this pass.", src=["S16"])
ev(id="E020", name="Entelect Challenge", edition="2022", year="2022", end="2022-09 (finals)", city="Johannesburg", province="Gauteng",
   venue="Comic Con Africa (finals)", host="Entelect", theme="AI bot coding competition", fin="8", compl="C", src=["S13"])
ev(id="E021", name="Entelect Challenge", edition="2023", year="2023", end="2023-09-23", city="Johannesburg", province="Gauteng",
   venue="Comic Con Africa (finals)", host="Entelect", theme="AI bot coding competition (Cy-Fi)", fin="8", compl="B",
   notes="'Now in its 11th year' per organiser (vs '13th year' claimed for 2024 by MyBroadband — see contradiction log).", src=["S14"])
ev(id="E022", name="Entelect Challenge", edition="2024", year="2024", end="2024-10 (finals)", city="Johannesburg", province="Gauteng",
   venue="Comic Con Africa (finals)", host="Entelect", theme="AI bot coding competition (Sproutopia)", fin="8", winners="8 named", compl="B",
   notes="Full top-8 with names and prizes captured.", src=["S15"])
ev(id="E023", name="Discovery GradHack", edition="2016", year="2016", host="Discovery", theme="Health", compl="B", src=["S27"])
ev(id="E024", name="Discovery GradHack", edition="2017", year="2017", city="Johannesburg", province="Gauteng", host="Discovery", theme="Health", compl="C",
   notes="Winner: UCT Information Systems team (per UCT 2018 article); member names not published.", src=["S28"])
ev(id="E025", name="Discovery GradHack", edition="2018", year="2018", start="2018-07 (48 hours)", city="Johannesburg", province="Gauteng",
   host="Discovery", theme="Health", fin="11 pitches", winners="1", compl="B", src=["S28"])
ev(id="E026", name="Discovery GradHack", edition="2021", year="2021", mode="Online", host="Discovery", theme="Health", compl="B",
   notes="72-hour virtual competition (COVID era).", src=["S29"])
ev(id="E027", name="Discovery GradHack", edition="2024", year="2024", mode="Online (72h) + finals in Sandton", city="Sandton", province="Gauteng",
   host="Discovery", theme="Health / Vitality", est="50 students", fin="16 teams", winners="3 named teams", compl="A", src=["S30","S31"])
ev(id="E028", name="Discovery GradHack", edition="2025", year="2025", mode="Finals at Discovery HQ", city="Sandton", province="Gauteng",
   host="Discovery", theme="Health / data", compl="B", src=["S32"])
ev(id="E029", name="Discovery GradHack — unverified interim editions", edition="2019/2020/2022/2023 (probable)", year="2019-2023", host="Discovery",
   compl="E", notes="Series continuity suggests editions in these years (annual event since 2014); no per-year results located this pass. Existence probable, not individually verified.", src=["S26","S31"])
ev(id="E030", name="Stellenbosch University Hackathon (InnovUS / LaunchLab)", edition="2021", year="2021", start="2021-10 (weekend)", city="Stellenbosch",
   province="Western Cape", host="Stellenbosch University (InnovUS, LaunchLab)", sponsors="Entersekt, Capitec (mentorship)", theme="FinTech + data", fin="2 challenge winners", compl="B", src=["S33"])
ev(id="E031", name="SU LaunchLab Annual Hackathon", edition="2024", year="2024", start="2024-08 (40 hours)", city="Stellenbosch", province="Western Cape",
   host="Stellenbosch University (InnovUS, LaunchLab)", theme="Cloud cost management (data)", est="49 participants", fin="9 teams", winners="1", compl="B", src=["S34"])
ev(id="E032", name="MiWay 24-hours Actuarial Hackathon", edition="2019 (2nd annual)", year="2019", city=U, province=U,
   host="MiWay Insurance", theme="Insurtech / data science", est="25 students from 5 universities", winners="3 named", compl="B",
   notes="Venue not stated in located sources; MiWay is Gauteng-based (not verified for this event — not inferred).", src=["S35","S36"])
ev(id="E033", name="MiWay 24-hours Actuarial Hackathon", edition="2018 (1st annual — inferred)", year="2018", host="MiWay Insurance",
   compl="E", notes="Existence inferred from 'second annual' phrasing in 2019 coverage; no independent 2018 coverage located.", src=["S35"])
ev(id="E034", name="NWU Geekulcha Hackathon", edition="2023 (annual Geekulcha Hackathon)", year="2023", city="Pretoria", province="Gauteng",
   venue="UNISA Pretoria campus", host="Geekulcha", theme="Student innovation", fin="top 10 incl. 2 NWU teams", compl="C",
   notes="Overall winners not located this pass; NWU top-10 teams fully named.", src=["S61"])
ev(id="E035", name="Geekulcha Annual Hackathon", edition="2025", year="2025", city=U, province=U, host="Geekulcha", compl="D",
   notes="3rd place: Delight Chetter & Kabelo Makhetha (CUT). 1st/2nd and full results not located.", src=["S56"])
ev(id="E036", name="Standard Bank UniHack", edition="2024", year="2024", start="2024-07 (two days)", city=U, province=U,
   host="Standard Bank", theme="AI / education / health solutions", fin="3", compl="B",
   notes="Participants from four Western Cape universities; event city not explicitly stated in located coverage.", src=["S38"])
ev(id="E037", name="Standard Bank UniHack", edition="2025 (3rd annual)", year="2025", start="2025-04 (two days)", city="Cape Town", province="Western Cape",
   host="Standard Bank", est="13 teams", fin="3", compl="B", src=["S39","S40"])
ev(id="E038", name="Standard Bank UniHack", edition="2023 (1st annual — inferred)", year="2023", host="Standard Bank", compl="E",
   notes="Existence inferred from 'third annual' phrasing (2025); no 2023 coverage located.", src=["S39"])
ev(id="E039", name="Kuunda Disrupt Hackathon (Standard Bank employee hackathon)", edition="2024 (10th annual)", year="2024", mode=U,
   host="Standard Bank Group", theme="Banking innovation", est="230+ hackers in top 45", compl="D",
   notes="Internal employee hackathon across 20 African markets; overall winner Ghana-based team; SA individual winners not named publicly.", src=["S41"])
ev(id="E040", name="Kuunda Disrupt Hackathon", edition="2025 (11th annual)", year="2025", city="Johannesburg", province="Gauteng", mode="Hybrid",
   host="Standard Bank Group", est="244 participants", theme="Generative AI in banking", compl="D",
   notes="Two SA-based winners referenced without names.", src=["S42"])
ev(id="E041", name="Kuunda Disrupt school series (Standard Bank)", edition="2015-2024 (10 editions, consolidated)", year="2015-2024", host="Standard Bank",
   compl="E", notes="'10th annual' in 2024 implies editions since ~2015; only the 2024 schools competition edition independently covered here (separate row). Consolidated probable-editions row.", src=["S41","S43"])
ev(id="E042", name="Standard Bank Kuunda Disrupt Competition (schools STEAM)", edition="2024", year="2024", city="Durban", province="KwaZulu-Natal",
   venue="Gordon Road Girls' School", host="Standard Bank", theme="STEAM / sustainability", est="19 schools", winners="1 team (12 pupils)", compl="C",
   notes="Schools competition (project showcase format) — included under youth innovation challenge scope; pupil names not published.", src=["S43"])
ev(id="E043", name="MTN MoMo API Hackathon (South Africa)", edition="2023", year="2023", start="2023-07-31", end="2023-10-09", mode="Online/National",
   host="MTN (MoMo)", theme="Fintech / API", fin="12", winners="3", compl="C",
   notes="SA open to the hackathon for the first time in 2023; winning developers not named in located coverage.", src=["S44"])
ev(id="E044", name="#SS19Hack", edition="2019", year="2019", city="Johannesburg", province="Gauteng", venue=U,
   sponsors="Micro Focus, MTN, Snode, Tshimologong Digital Precinct (trophy)", theme="IoT security / CTF", est="50 developers", fin="3 + CTF", compl="C",
   notes="'SS' expansion and lead organiser not confirmed in located sources (coverage by ITWeb; Geekulcha figures pictured). 2nd-place team from Kimberley (Northern Cape residents — event held in JHB).", src=["S45"])
ev(id="E045", name="Absa Design Hackathon", edition="2021", year="2021", mode=U, host="Absa", theme="Design", winners="2 named teams", compl="B", src=["S47"])
ev(id="E046", name="Absa Technology Hackathon", edition="2024 (2nd annual)", year="2024", mode=U, host="Absa", theme="Banking technology",
   compl="D", notes="Internal multi-country employee hackathon; SA-based winning teams named as teams only.", src=["S46"])
ev(id="E047", name="Absa Technology Hackathon", edition="2025 (3rd annual)", year="2025", start="2025-10 (24 hours)", mode=U, host="Absa",
   compl="D", notes="SA winners (Mighty Pythons; Hustle Hub) named as teams only.", src=["S48"])
ev(id="E048", name="Absa Technology Hackathon", edition="2023 (1st annual — inferred)", year="2023", host="Absa", compl="E",
   notes="Existence inferred from 'second annual' phrasing in 2024 statement.", src=["S46"])
ev(id="E049", name="Vodacom Group Annual Hack-alympics", edition="2024", year="2024", mode=U, host="Vodacom Group", theme="Internal innovation across African markets",
   compl="E", notes="Internal hackathon incl. South African participants; winners per market not publicly named in located coverage.", src=["S49"])
ev(id="E050", name="Wits Minecraft Education Edition Challenge", edition="2018", year="2018", city="Johannesburg", province="Gauteng",
   host="Wits University", sponsors="Microsoft, Acer, Masterskill", theme="Game-based build challenge", compl="C",
   notes="Build/design challenge (game jam-adjacent scope); sponsors' staff attended prize-giving.", src=["S52"])
ev(id="E051", name="Wits supercomputing student competition awards", edition="2018", year="2018", city="Johannesburg", province="Gauteng",
   host="Wits University", theme="High-performance computing", compl="D",
   notes="Team awards ('most innovative', 'best teamwork') captured from Wits stories page; competition name/context not fully stated on page — verify before treating as cluster competition.", src=["S52"])
ev(id="E052", name="MICT SETA National Skills Challenge Hackathon — KZN Regionals", edition="2026", year="2026", start="2026-03-22", end="2026-03-23",
   city="Durban", province="KwaZulu-Natal", venue="MKRI offices", host="MICT SETA", theme="Digital skills", fin="3", winners="3 named teams", compl="A", src=["S53"])
ev(id="E053", name="MICT SETA National Skills Challenge Hackathon — Eastern Cape leg", edition="2026", year="2026", start="2026-03 (two days)",
   city="Gqeberha", province="Eastern Cape", host="MICT SETA", theme="Digital skills", winners="1 named team", compl="B",
   notes="Universities and TVET colleges across province participated.", src=["S54"])
ev(id="E054", name="MICT SETA National Skills Challenge Hackathon — National Finals", edition="2026", year="2026", start="2026-03-30", end="2026-03-31",
   city="Johannesburg", province="Gauteng", host="MICT SETA", compl="E",
   notes="Finals confirmed by two sources; national winners not located this pass.", src=["S53","S54"])
ev(id="E055", name="Beat the Banker Hackathon (UFS)", edition="2026", year="2026", start="2026-06", city="Bloemfontein", province="Free State",
   host="University of the Free State", sponsors="Standard Bank; BBD Software", theme="Fintech", winners="3 named teams + special prize", compl="A", src=["S55"])
ev(id="E056", name="Telkom 10X Hackathon — Free State leg", edition="2025", year="2025", start="2025-10", city="Botshabelo", province="Free State",
   venue="Botshabelo Digital Hub", host="Telkom (10X)", winners="1 named team", compl="B",
   notes="Winning duo advanced to national finals in Johannesburg (results not located).", src=["S56"])
ev(id="E057", name="Telkom 10X Hackathon — National Finals", edition="2025/2026", year="2025", city="Johannesburg", province="Gauteng", host="Telkom",
   compl="E", notes="Finals confirmed as upcoming/occurring in Johannesburg; results not located.", src=["S56"])
ev(id="E058", name="Limpopo Varsity Hackathon (LVH)", edition="2025 (4th annual)", year="2025", start="2025-10-10", end="2025-10-12",
   city="Mankweng/Polokwane", province="Limpopo", venue="University of Limpopo, VL Hall", host="TUT Polokwane with University of Limpopo, UNIVEN",
   sponsors="mLab (participation per 2026 coverage)", theme="Hack4Mzansi (AI/IoT)", fin="3", compl="C", src=["S57"])
ev(id="E059", name="Limpopo Varsity Hackathon (LVH)", edition="2026 (5th annual)", year="2026", city=U, province="Limpopo", host="TUT/UL/UNIVEN consortium",
   theme="Agriculture", compl="E", notes="Coverage of event existence; winners not located in accessed coverage.", src=["S57"])
ev(id="E060", name="Tshwane Varsity Hackathon (TVH)", edition="2025 (7th annual)", year="2025", start="2025-09 (three days)", city="Pretoria (+ TUT Polokwane participation)",
   province="Gauteng; Limpopo", host="TUT with City of Tshwane", sponsors="MTN SA, IQ Business, AWS, Nelekat, RMCERI",
   est="16 teams from TUT/UP/UNISA/SMU", fin="5 (top five)", winners="3", compl="C", src=["S58"])
ev(id="E061", name="CyberSecureTech Hackathon", edition="2025", year="2025", city="Thohoyandou", province="Limpopo", venue="University of Venda",
   host="UNIVEN", sponsors="Adapt IT (mentorship)", theme="Cybersecurity", est="18 teams -> 11 finalists", fin="11", winners="4", compl="C",
   notes="Prize amounts and first-place team composition conflict between two UNIVEN articles (see contradiction log).", src=["S59","S60"])
ev(id="E062", name="UCT Financial Innovation Hub x Interledger Foundation Hackathon", edition="2025", year="2025", start="2025-06-28", city="Cape Town",
   province="Western Cape", host="UCT Financial Innovation Hub", sponsors="Interledger Foundation", theme="Fintech / Interledger Protocol",
   est="12 teams from 4 universities", fin="12", winners="3", compl="B", src=["S62"])
ev(id="E063", name="UCT Financial Innovation Hub x Interledger Hackathon", edition="2026", year="2026", start="2026-06 (week-long bootcamp)", city="Cape Town",
   province="Western Cape", host="UCT Financial Innovation Hub", sponsors="Interledger Foundation", theme="Financial inclusion",
   est="8 students (UCT, Eduvos, SPU, UFS)", winners="1 named team (3 members)", compl="C",
   notes="Only one member of winning team named in coverage.", src=["S63"])
ev(id="E064", name="UCT Surgical Society x Harvard HSIL Surgical Hackathon", edition="2025", year="2025", start="2025-04-11", end="2025-04-12",
   city="Cape Town", province="Western Cape", host="UCT Surgical Society with Harvard Health Systems Innovation Lab; Global Surgery", theme="AI for healthcare systems",
   winners="1 named team", compl="B", src=["S64"])
ev(id="E065", name="Innovate Africa Fund Hackathon", edition="2025 (inaugural)", year="2025", city=U, province=U, host="Innovate Africa Fund (angel syndicate)",
   theme="Pan-African startups", est="10 teams from across Africa", winners="1 named team", compl="C",
   notes="Venue not stated in located coverage; winning team South African.", src=["S65"])
ev(id="E066", name="Hackathons for SA #GBV — Cape Town", edition="2020", year="2020", city="Cape Town", province="Western Cape",
   org="Silicon Cape (implementation partner)", theme="Gender-based violence prevention", winners="1 named team", compl="C", src=["S66"])
ev(id="E067", name="Township Tech Hackathon (CiTi)", edition="2021", year="2021", city="Cape Town", province="Western Cape", venue="Woodstock Bandwidth Barn (final)",
   mode="Hybrid", host="Cape Innovation and Technology Initiative (CiTi)", org="Western Cape Department of Economic Development and Tourism",
   theme="Township tech", est="40 participants", fin="6", winners="3", compl="C", src=["S67"])
ev(id="E068", name="AB4IR Hackathon", edition="2021", year="2021", start="2021-04 (three days)", city="Tshwane", province="Gauteng",
   venue="Tshwane South TVET College", mode="Hybrid (reported as online event at TVET college venue)", host="Africa Beyond 4IR (AB4IR)",
   sponsors="Liquid Intelligent Technologies", theme="Creative industries / township digital entrepreneurship", est="250 registrations; 20 selected", fin="20 participants", winners="3", compl="C", src=["S68"])
ev(id="E069", name="Eastern Cape Youth Digital Agrisec Hackathon", edition="2022", year="2022", city=U, province="Eastern Cape", host="PAICTA-linked programme",
   theme="Agritech", winners="1 named team", compl="C", notes="WSU Komani ITS students won; exact venue/date not captured.", src=["S69"])
ev(id="E070", name="PAICTA International Hackathon", edition="2022", year="2022", mode=U, host="Pan African ICT Association (PAICTA)",
   compl="D", notes="SA participation verified (4 WSU students qualified); placement in international event not located.", src=["S69"])
ev(id="E071", name="DIRISA Student Datathon", edition="2022", year="2022", start="2022-11-26", end="2022-12-02", city="Pretoria", province="Gauteng",
   venue="CSIR ICC", host="DIRISA (CSIR)", theme="Data science (social media data)", est="10 teams", winners="3 + special awards", compl="B", src=["S70"])
ev(id="E072", name="DIRISA Student Datathon", edition="2023", year="2023", end="2023-12-07 (awards)", city="Skukuza (awards)", province="Mpumalanga",
   venue="Nombolo Mdhli conference site, Skukuza Rest Camp (awards ceremony)", host="DIRISA (CSIR)", sponsors="Momentum, Spectra Logic, Korbicom Educational Trust",
   theme="Data science (youth unemployment)", winners="Named individual bursary winners + university teams", compl="B",
   notes="Only the awards ceremony venue is Mpumalanga; competition phases held at institutions/online (not fully specified).", src=["S71","S72"])
ev(id="E073", name="DIRISA Student Datathon — earlier editions", edition="2019-2021 (annual since 2019 — consolidated)", year="2019-2021", host="DIRISA (CSIR)",
   compl="E", notes="Organiser states datathon 'successfully held since 2019'; per-year 2019-2021 results not located this pass.", src=["S72"])
ev(id="E074", name="IEB-TechWays National AI Hackathon", edition="2026", year="2026", mode="National (schools)", host="IEB / TechWays", theme="AI (schools)",
   winners="7 school teams recognised", compl="C", notes="Learner names not published; school teams recorded in unresolved identities.", src=["S73"])
ev(id="E075", name="South Africa Space Design Competition — national finals", edition="2026 (inaugural)", year="2026", start="2026-03", city="Cape Town",
   province="Western Cape", venue="University of Cape Town", host="SA Space Design Competition (founded by Jagger Cooper-Doubell)",
   theme="Space engineering design sprint", est="109 learners from 9 schools", winners="7 learners selected (Team ZA)", compl="C",
   notes="Design-competition scope. Team ZA then won the International Space Settlement Design Competition global finals (Kennedy Space Center, 30 Jul–2 Aug 2026) — international outcome recorded in notes.", src=["S74","S83"])
ev(id="E076", name="HackAtom South Africa (national round)", edition="2026 (first SA round)", year="2026", city="Durban", province="KwaZulu-Natal",
   host="HackAtom international (Rosatom-linked programme)", theme="Energy / engineering", winners="1 named team", compl="C",
   notes="International final held in Moscow (outside SA scope) — SA national round recorded.", src=["S75"])
ev(id="E077", name="Gauteng Department of e-Government Youth Tech Challenge", edition="2026", year="2026", end="2026-07 (results announced)", city=U,
   province="Gauteng", host="Gauteng Department of e-Government", theme="AI for service delivery (youth)", est="5 finalist district teams (10 learners each)",
   fin="5", winners="5", compl="C", notes="Event name as described in coverage ('Gauteng's biggest youth tech challenge'); official programme name not confirmed.", src=["S76"])
ev(id="E078", name="Girls Game Jam (French Institute of South Africa)", edition="2025", year="2025", city=U, province=U, host="French Institute of South Africa",
   theme="Game jam (women/girls)", winners="1 named team", compl="C", notes="Event city not stated in located coverage.", src=["S77"])
ev(id="E079", name="Global Game Jam — South African sites", edition="2020 (Vega Cape Town & Vega Johannesburg)", year="2020", start="2020-01-31", end="2020-02-02",
   city="Cape Town; Johannesburg", province="Western Cape; Gauteng", host="MakeGamesSA (community); Global Game Jam", theme="Game jam",
   compl="D", notes="GGJ has run SA sites across multiple years (community-coordinated); participant lists exist per site on globalgamejam.org — bulk extraction scheduled for next pass. Series row for 2020 sites; other years to be enumerated.", src=["S78"])
ev(id="E080", name="Cloud DevJam Hackathon (Zaio)", edition=U, year=U, mode="Online (international)", host="Zaio (Cape Town)",
   theme="MERN stack coding gameshow", winners="top 10 incl. SA pair", compl="D",
   notes="Date not stated in located coverage (UNIZULU news index). SA participants connected via organiser + participant SA locations.", src=["S79"])
ev(id="E081", name="VUT Hackathon", edition="2026", year="2026", city="Vanderbijlpark", province="Gauteng", venue="Vaal University of Technology",
   host="VUT", theme="Community problem-solving", compl="D", notes="Winning team names not captured in accessed excerpt; regional follow-on at UFS QwaQwa campus.", src=["S80"])
ev(id="E082", name="IATF Healthcare Hackathon", edition="2025", year="2025", city=U, province=U, mode=U, host="Afrilabs + Afreximbank (at Intra-African Trade Fair 2025)",
   theme="Health", winners="1 named team", compl="D",
   notes="Physical venue outside SA (IATF 2025). Included per online/hybrid rule: SA connection documented for winner Jamie Wyngaard (SA entrepreneur). Verify venue country before treating as SA-hosted.", src=["S81"])
